### ISSUE TITLE
Replace `with_args` with `functools.partial`

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#100]
[utilities.py](https://github.com/lawsie/guizero/blob/dev/guizero/utilities.py):

```python
# Lambda-izer for making it easy to pass arguments with function calls
# without having to know what lambda does
def with_args( func_name, *args):
    return lambda: func_name(*args)
```

Instead of `with_args`, we could use [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial), which does the same thing, but is easier to extend.

**Comment by martinohanlon** [comment]
Is with_args causing issues? If not, I would not change.

Using the inbuilt lambda function is a low cost, efficient solution, I would only change if it didn't fulfil the requirement.

**Comment by Coal0** [comment]
Fair point.
