### ISSUE TITLE
`setuptools` may not be available

### ISSUE THREAD

**Issue by coal0** [lawsie/guizero#102]
There's no guarantee that `setuptools` is available on a target system. How about wrapping that in a `try: except:`:

```python
try:
    from setuptools import setup, find_packages
except ImportError:
    from distutils.core import setup, find_packages
```

**Comment by lawsie** [comment]
Whoops, this is a mistake on my part. It is extremely important to me that no other libraries are _required_ to be able to use guizero because it's such a pain in schools. If `distutils.core` is something that's always available then that sounds like a really good idea. I think I must have thought setuptools was a core library.

**Comment by martinohanlon** [comment]
Generally if you have a 'recent' version of pip then setuptools would be available. You would only be missing setuptools if you had an older version of pip installed.

If you are using pip to install guizero, you would also have the ability to upgrade pip using pip:

pip install --upgrade pip

Would an alternative be to include a troubleshooting or FAQs section? This will be a diminishing use case (as very few people would be installing older versions of python) and any new install would include setuptools.

Including distutils.core in the setup.py means you should really test it is also installable by distutils and for how long is that maintable?

**Comment by Coal0** [comment]
[`distutils.core.setup`](https://docs.python.org/3/distutils/apiref.html#distutils.core.setup) and `setuptools.setup` (reference unclear) are very similar, API-wise. `setuptools.setup` has some [changed or new arguments](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords), but, at least in the foreseeable future, none of these are required for Guizero. A FAQ section wouldn't be out of place, but I think for least hassle, we should build using `setuptools.setup` and fall back to `distutils.core.setup` where needed.

**Comment by Coal0** [comment]
Opened a pull request [here](https://github.com/lawsie/guizero/pull/105).

**Comment by martinohanlon** [comment]
I have no way of testing the effectiveness of this implementation, I dont think it is the 'right' thing to do, the established pattern for installing python modules is via setuptools and at the moment there are no open issues suggesting this is even a problem.

I will leave the issue open & PR and assess whether there is a need.

**Comment by martinohanlon** [comment]
There has been no reported issues of install problems as a result of setuptools not being available so I am going to close this issue. Thanks
