### ISSUE TITLE
PushButton change_command button does not remove initial command

### ISSUE THREAD

**Issue by penguintutor** [lawsie/guizero#103]
When creating a PushButton then the command to execute is a required parameter. It should be possible to change this using the change_command() method, but that does not remove the initial command which was provided during object creation.

The reason that this is happening is that the PushButton uses it's own internal method _on_release() which uses the object variable _command, however when change_command() is used instead it calls the tkinter config method to update the button instead. 

This means that the PushButton it will continue to call the command which was created when the instance was created through the _on_release() method even if the command has been changed. Either the self._command() line should be removed from the _on_release method and replaced by running the self.tk.config(command=_command) so that adds it to the tk button during init, or the change_command() method should be updated so that is stores the command as _command instead of using the button config method.

**Comment by lawsie** [comment]
Maybe I'm missing something, but I just tried this out and it seems to work fine:

```python
from guizero import App, PushButton, Text
import random

def command1():
    text.value = random.randint(1, 100)
    print("Button1 command: " + str(button1._command))

def command2():
    text2.value = "Command 2"
    print("Button1 command: " + str(button1._command))

def new_command():
    button1.change_command(command2)

app = App()

text = Text(app, text="First")
text2 = Text(app, text="Second")

button1 = PushButton(app, text="Command 1", command=command1)
button2 = PushButton(app, text="Change command", command=new_command)

app.display()
```

Once you press the second button to change the command, `command1` no longer executes when the top button is pressed. 

Also I am confused by the second part - `change_command()` doesn't use the tkinter config method:

```python
# Change command - needs the name of a function and optional args as a list
    def change_command(self, newcommand, args=None):
        if args is None:
            self._command = newcommand
        else:
            # If the args LIST was not blank, allow args
            self._command = utils.with_args(newcommand, *args)
```

I suspect that this is something @martinohanlon fixed in 0.4.1 - are you using that version or 0.4?

**Comment by penguintutor** [comment]
I was using code from 0.4.

It does look like this may have been fixed within the last couple of weeks as part of "fixed pushbutton being pressed when disabled "

I'll try pulling the latest updates and try again - sorry for the confusion.

**Comment by penguintutor** [comment]
Tested now using 0.4.1 and I can confirm it is fixed.

Apologies - but I didn't realise that 0.4.1 was out when I raised the request. I've now pulled the latest version and it's working as it should.

**Comment by martinohanlon** [comment]
Sorry a bit late to the party here..  Yes I can confirmed I fixed this in 0.4.1...

**Comment by robin48gx** [comment]
how do you pull updates for this on ubuntu linux

**Comment by robin48gx** [comment]
$ sudo pip3 install guizero --upgrade
Requirement already up-to-date: guizero in /usr/local/lib/python3.8/dist-packages (1.3.0)

**Comment by martinohanlon** [comment]
Version 1.3.0 is the latest version.

**Comment by robin48gx** [comment]
> Version 1.3.0 is the latest version.

Ah thanks! I am a bit python n00b. I realised what I had done wrong after a little diversion into anonymous lambda; don't put brackets on the command and use the args is the best way for PushButton....
