### ISSUE TITLE
Quandrant on screen or readings on four corners of the screen

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#104]
With Guizero is it possible to produce 4 boxes on the screen or a quadrant.

For example I have a Guizero program running that reads out data on a large screen, 4 lines of
data, is it possible to break that up into 4 corners of the screen.

Top left hand corner reading one temperature sensor, the top right hand corner reading a second 
temperature sensor, bottom left hand corner reading time, the bottom right hand corner showing the 
date.

I have this and other Guizero programs working very well, just want to break up the readings into 4 corners of the screen.

If there is any examples that would be great.

Thanks

**Comment by lawsie** [comment]
Hi James,

I think you mean something like this. It's not possible to do this entirely with guizero methods but you can cheat and use some `tk` methods on the `App` object's internal `Tk` object to give all available space to whatever is in the middle:

```python
from guizero import App, Text

app = App(layout="grid")

# Use tk methods to give all extra space to the middle bit
# (this is not part of guizero)
app.tk.grid_columnconfigure(1, weight=1)
app.tk.grid_rowconfigure(1, weight=1)

# Set up your text items
topleft = Text(app, text="Top left", grid=[0,0])
topright = Text(app, text="Top right", grid=[2,0])
bottomleft = Text(app, text="Bottom left", grid=[0,2])
bottomright = Text(app, text="Bottom right", grid=[2,2])
middle = Text(app, text="Stuff in middle", grid=[1, 1])

app.display()
```

**Comment by James100000** [comment]
Thanks for doing all that work, it has worked wonders.

Thanks
