### ISSUE TITLE
Repository contains no license file

### ISSUE THREAD

**Issue by ukBaz** [lawsie/guizero#11]
I notice that there is no license on the repository which generally speaking, the absence of a license means that the default copyright laws apply. This is probably not the intention of this repository.

More information at:
https://help.github.com/articles/open-source-licensing/

**Comment by GadgetSteve** [comment]
Second this! Laura (@codebloom) please select an applicable licence such as [PSFL ](https://docs.python.org/3/license.html) and add it as soon as possible - many institutions & organisations will **not** allow the use of packages without clear, accessible, licences.

**Comment by lawsie** [comment]
Done!
