### ISSUE TITLE
PushButton command should be optional

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#111]
At the moment PushButton(command) is mandatory. Its the only widget which has a mandatory command and to gain consistency and a common interface it should be made optional.

**Comment by lawsie** [comment]
What's the point of a button that doesn't do anything though?

**Comment by martinohanlon** [comment]
Nothing, but you want to implement the functionality in a different way.

You may want to review its .value from within a different method, or register events so that action is taken when it is pressed rather then released, or only set a command a particular points during execution.

**Comment by martinohanlon** [comment]
In 0.4.4
