### ISSUE TITLE
Waffle - selected_color property and "auto" click

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#115]
Should waffle implement a selected_color property which if not None when the waffle is clicked automatically update the cell?

**Comment by martinohanlon** [comment]
maybe it should be `clicked_color`?

**Comment by Coal0** [comment]
Hmm, maybe. I can't think of any real use cases for this...?

**Comment by martinohanlon** [comment]
The use case is "when I click the waffle I want to pixel I have clicked to be selected", there is an example for it `clickable_waffle.py`:

The clickable waffle example:

```python
from guizero import App, Waffle

def change_pixel(x,y):
    if big_waffle.get_pixel(x,y) == 'white':
        big_waffle.set_pixel(x, y, "red")
    else:
        big_waffle.set_pixel(x, y, "white")

app = App("Waffle!", height=50*20, width=50*20)

big_waffle = Waffle(app, height=40, width=40, dim=10, pad=2, dotty=True, command=change_pixel)

app.display()
```

I am envisaging would look something like this:

```python

from guizero import App, Waffle

app = App("Waffle!", height=50*20, width=50*20)
big_waffle = Waffle(app, height=40, width=40, dim=10, pad=2, dotty=True, selected_color="red")
app.display()

```

The complexity of turning pixels on and off is abstracted.

**Comment by Coal0** [comment]
Ah, right. I think you mean an attribute (method) rather than a property? (Considering it should probably be private)

**Comment by martinohanlon** [comment]
I am envisaging an additional parameter on the constructor `selected_color`, which is defaulted to None.

If `selected_color` is not None when the Waffle is clicked it sets the pixel which was clicked to that color, unless of course it is already that color, in which case it makes it the same color as the background.

Making `selected_color` a public property is a good idea as it allows the user to change the selected color at run time.

**Comment by martinohanlon** [comment]
In retrospect I am not convinced this is the right approach - closing.
