### ISSUE TITLE
add_command, change_command is inconsistent across widgets

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#116]
Slider has add_command(command)
PushButton has a change_command(command, args=[])

All widgets which have a `command` should allow the command to be changed/added.

I would propose renaming it to `update_command`, this works if you are adding and changing.

**Comment by lawsie** [comment]
I thought there was a problem with this but maybe you have fixed it. If I remember correctly with `Combo` I couldn't work out how to change the command associated with changing the option at all once the widget has been created. However having looked at the code, it appears that you have got rid of a nasty tk internal method hack I used so maybe you have found a way to do this!

**Comment by martinohanlon** [comment]
I think this was changed in all the 0.4 work.

**Comment by martinohanlon** [comment]
added `update_command` to `ButtonGroup`

**Comment by martinohanlon** [comment]
in dev for v0.4.4
