### ISSUE TITLE
`PushButton.value` doesn't work as expected

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#123]
`PushButton.value` seems to always return `0`, no matter whether or not the button is being pressed. For example, try running this script and pressing the button:

```python
import guizero as gz
import time


def main():
    app = gz.App(height=200, width=200)
    app.tk.geometry("+200+200")
    # For screen recording, don't mind this
    button = gz.PushButton(app, lambda: None)
    while True:
        time.sleep(0.1)
        app.tk.update()
        print(button.value)

if __name__ == "__main__":
    main()
```

Notice that the `update` call blocks.
For what it's worth, here's a GIF of what I mean (no, I don't type so slowly, conversion problems):

![buttonvalue](https://user-images.githubusercontent.com/29181648/35275109-e766ad2c-003e-11e8-9381-8e8053acafcb.gif)

Anybody got ideas on how to solve this? I'm rather clueless. Threading may be an option, but requires managing a shared queue, because otherwise tkinter explodes.

**Comment by bsimmo** [comment]
As a note,that code works fine for me in Thonny and IDLE3 on the Pi (python 3.5.3)
0 and 1 appear.

**Comment by bsimmo** [comment]
What happens if you run in this style

`
import guizero as gz

def button_value():
    print(button.value)

if __name__ == "__main__":
    app = gz.App(height=200, width=200)
    button = gz.PushButton(app, lambda: None)

    app.repeat(100, button_value)

    app.display()
`

**Comment by martinohanlon** [comment]
I just ran your example and I didnt have a problem. Python 3.6.1. 

Very strange.

Did @bsimmo 's example work?

**Comment by martinohanlon** [comment]
I thought I would create a gif too :)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2329501/35288501-c6c6db6e-005c-11e8-81db-937c56c1a4cc.gif)

**Comment by martinohanlon** [comment]
I wonder whether tk needs you to call app.display() before it starts managing the events?

**Comment by Coal0** [comment]
Interesting. I'm running Python 3.6.0 on macOS Sierra, guizero v0.4.3. I'm on Tcl 8.5:

```shell
$ python3 -c "import tkinter; print(tkinter.TclVersion)"
8.5
```

@bsimmo 's code worked as expected. It most likely has to do with the underlying event model of tkinter (which I do *not* understand) and an odd setup on my part. Tkinter doesn't seem to register the button press as an event, only the release. This may be an issue with the macOS install.

This is simply a healthy reminder that event-driven programming requires you to think twice before writing anything. :)

I'll leave this open for any more thoughts on the matter.

---

Regarding `app.display`, if I'm not mistaken, [`tk.Tk.mainloop` blocks](https://www.tcl.tk/man/tcl8.6/TkLib/MainLoop.htm), so procedural code following the call will not be executed until the `tk.Tk` instance is destroyed.

**Comment by martinohanlon** [comment]
I checked and I am running v 8.6 of tk

**Comment by martinohanlon** [comment]
I am closing this, I havent been able to reproduce and no other issues have been raised.
