### ISSUE TITLE
Waffle properties don't redraw the Waffle

### ISSUE THREAD

**Issue by lawsie** [lawsie/guizero#125]
Changing the properties of the waffle only change the values of the internal variables (e.g. `_width` and `_height`). The grid itself does not redraw as you might expect it to. 

For example:

```python
from guizero import App, Waffle, Slider, Text

def change_dim(slider):
    print("Changing width to " + str(g_width.value))
    grid.width = g_width.value
    print("Grid width is " + str(grid.width))

app = App("Changing size", layout="grid")

grid = Waffle(app, width=4, height=4, pad=0, grid=[1,0])

# Width
width_text = Text(app, text="Width", grid=[0,3])
g_width = Slider(app, start=0, end=20, command=change_dim, grid=[1,3])
g_width.value = 4


app.display()
```

When you change the slider, the properties change but the grid never redraws.

**Comment by scotty3785** [comment]
Try my branch with this prototype functionality 
https://github.com/scotty3785/guizero/tree/waffle_resize
Example is included in examples/waffle_resize.py to allow changing both height and width.

**Comment by martinohanlon** [comment]
changing the following properties should redraw the waffle:
 - width
 - height
 - pad
 - color
 - pixel_size
 - dotty

**Comment by martinohanlon** [comment]
I would say that when the waffle is redrawn it should maintain its state.

Given this, its probably worth adding a `reset` method.

**Comment by martinohanlon** [comment]
In 0.4.5, major refactor of Waffle

@scotty3785 - thanks a lot for your prototype, it was really useful.

Added `reset` and `pixel` methods.

Docs need updating

**Comment by martinohanlon** [comment]
Updated docs, provided an example `resize_waffle.py` (mostly robbed from @lawsie 's code above)

It'll be in 0.4.5.
