### ISSUE TITLE
Is there a way to disable the buttons highlighted state?

### ISSUE THREAD

**Issue by aphex3k** [lawsie/guizero#129]
As the PushButton class is a tkinter button widget subclass, is there an easy way to manipulate its highlighted state for when the mouse cursor is hovering over the button? I basically want to avoid that the button is changing colors to a highlighted state when the mouse cursor is over it...

**Comment by Coal0** [comment]
Hey, would you mind creating a GIF file demonstrating what you mean? At least on macOS, hovering over a button doesn't change its state.

**Comment by martinohanlon** [comment]
do you mean when you press the pushbutton with a mouse click?

have a look at http://effbot.org/tkinterbook/button.htm and the PushButton.tk property which will give you access to the tk Button class.

i am going to close the issue as it is not a 'problem' with guizero.
