### ISSUE TITLE
Possibility to stick a Box to a specific part of the app.

### ISSUE THREAD

**Issue by yeyeto2788** [lawsie/guizero#133]
Hello guys!

I'm using this amazing module to build an application but I have discovered that I cannot arrange the Box (es) within an app to a specific location. 

Here you have part of the code:
```
# Box for the buttons
buttonContainer = guizero.Box(app, layout="grid", grid=[0, 2], align="bottom")
buttonContainer.bg = backgroundColor
playButton = guizero.PushButton(buttonContainer,
                                command=executeCommand,
                                align="left",
                                grid=[0, 0, 2, 1],
                                padx=68,
                                text="Play Game!")
playButton.bg = buttonColor
playButton.text_color = backgroundColor
playButton.color = backgroundColor
playButton.text_size = buttonTextSize
exitButton = guizero.PushButton(buttonContainer,
                                command=exitCode,
                                align="right",
                                grid=[2, 0, 3, 1],
                                padx=70,
                                text="   Exit   ")
exitButton.bg = buttonColor
exitButton.text_color = backgroundColor
exitButton.text_size = buttonTextSize
```

[Here ](https://github.com/yeyeto2788/PocketCHIP_Retro/blob/master/PocketRetro.py)you have the complete code.

and this is how it looks like: 
![1](https://user-images.githubusercontent.com/6363686/35920844-58150524-0c19-11e8-9ec8-e7499f68cf3b.png)

The problem is that I'm trying to stick the buttons (Play Game, Exit) to the bottom of the app but it seems not to be working or I'm using the module in a wrong way.

I would highly appreciate if you could help here.

Best Regards.

**Comment by martinohanlon** [comment]
You may be able to do this using the underlying tk layout manager, have a look http://zetcode.com/gui/tkinter/layout/ for some info. You can access the using the tk Frame object using the Box.tk property.

Ill leave the issue open as an example for potential future improvements to guizero's layout.

**Comment by martinohanlon** [comment]
Created issue https://github.com/lawsie/guizero/issues/223 to discuss layouts and sizes in v 0.6

**Comment by yeyeto2788** [comment]
So every single issue will be handle on the #223? As a group?

**Comment by martinohanlon** [comment]
No, I will leave this issue open, but I as this issue is related to layouts I wanted to tag it.

**Comment by yeyeto2788** [comment]
Ohhh ok, just making sure the issue has a possible fix. It is great to have the #223 open since it is not very clear the usage of the layout or at least that's what I have experienced.

Regards.

**Comment by martinohanlon** [comment]
This will be in 0.6

You will be able to do:

```python
from guizero import App, Text
a = App()
Text(a, text="stuck to the bottom", align="bottom")
a.display()
```

... or use a Box if you want to stick multiple widgets:

```python
from guizero import App, Box, Text

b = Box(a, align="bottom")
Text(b, text="stuck to the bottom")

a.display()
```

**Comment by yeyeto2788** [comment]
@martinohanlon that's a great improvement. Do you know by any chance the ETA for the version 0.6?

**Comment by martinohanlon** [comment]
2nd week of Feb (probably)

There is a project for 0.6 in the repo which you can check progress against.
