### ISSUE TITLE
Input for GUIZero

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#150]
In this practice code I have C = 8 and D = 2, I would like to replace this with a input function that 
GuiZero recognize.

Been having great success with GuiZero I have just overlooked the input function.

Thanks

``````
from guizero import App, Text
def update_writing():    
 
    C = 8
    D = 2
    A = C + D
    B = A/2
   
    writing1.value = A
    writing2.value = B
    
    
    
    app.after(200, update_writing)

app = App(height=500, width=500,bg="black")

writing1 = Text(app, text="A", color="green",size=50,bg="black")
writing2 = Text(app, text="B", color="green",size=50,bg="black")


app.after(200, update_writing)
app.display()


``````

**Comment by martinohanlon** [comment]
guizero has several widgets for getting input from the user e.g. TextBox, Combo, ButtonGroup, Slider.

You can see examples of how to use them in the documentation https://lawsie.github.io/guizero

Is this what you were asking or do you think there is an input missing?

**Comment by James100000** [comment]
I am looking at how to input variables for formulas.

**Comment by martinohanlon** [comment]
I am still not sure what you are trying to do or why there is an issue, however:

You can create a TextBox to get an input from the user.

e.g:
```
my_input = TextBox(app)
```

You can then use the value in the TextBox to feed into a formula.

```
a = 2 + my_input.value
```

As the TextBox contains a string you will have to convert it to an int if you want to do any calculations e.g:

```
a = 2 + int(my_input.value)
```

**Comment by James100000** [comment]
Dose the input command only work on these,TextBox, Combo, ButtonGroup, Slider?
Would  "my_input.value" work on the import Text?

I am trying to obtain user input with the above program.

**Comment by martinohanlon** [comment]
To get some input from a user using a GUI you need to put something on the screen for them to either type into or click. There is an example of how to use a TextBox here -
 https ://lawsie.github.io/guizero/textbox/

Have a look at this tutorial https://projects.raspberrypi.org/en/projects/getting-started-with-guis it was created by @lawsie who created guizero and recently updated by me. It will take you through the how to create a GUI which displays output , gets input from a user and reacts to events.
