### ISSUE TITLE
Graphics read out to Centre of Screen

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#152]
With this program I use it for general applications.

Since GUIZERO has been up graded and how can I  center the graphics to the middle of the GUI.
From advise before I was using a program line from Tinker which was  **"writing.pack(fill="none", expand=True) "***

Thanks, any info most valued.

``````
from guizero import App, Text
def update_writing():    

    
     A = 100
     B = 200
   


    
     writing1.value = A
     writing2.value = B
    
    
    
     app.after(200, update_writing)

app = App(height=1000, width=1000,bg="black")

writing1 = Text(app, text="A", color="green",size=100,bg="black")
writing2 = Text(app, text="B", color="green",size=100,bg="black")


app.after(200, update_writing)
app.display()

**Comment by martinohanlon** [comment]
Since v0.4.0 tk methods such as `pack` are accessed via the `widget.tk` property. See https://lawsie.github.io/guizero/usingtk/
