### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#155]
Currently guizero only supports single window application, it was noted in #130 that creating multiple `App` objects results in odd behaviour.

My thoughts on extending the guizero api to support multiple windows are:

+ `App` remains the 'main' window / application and is launched first.
+ A new class would be introduced called `Window`, this would be used to create other windows
+ `Window` would support a similar set of methods to `App` and widgets would be used in the same way (I am actually thinking App would inherit from Window)
+ `App` and `Window` objects can open and close `Window` objects via `open(window)` and `close(window)` methods.
+ `open` would accept an optional `wait` parameter which when set to false would force the calling window to wait until it was closed (so by creating a modal window).

Something a bit like this:

```python
from guizero import App, Window, PushButton

app = App(title="main app window")
window = Window(app, title = "another window")
modal = Window(app, title = "a modal window")

def open_window():
    app.open(window)

window_button = PushButton(app, text = "open window", command = open_window)

def open_modal():
    app.open(model, wait = True)

modal_button = PushButton(app, text = "open model", command = open_modal)

app.display()

```

Thoughts?

**Comment by martinohanlon** [comment]
An alternative could be that the Window objects themselves have open and close methods e.g.


```python
from guizero import App, Window, PushButton

app = App(title="main app window")
window = Window(app, title = "another window")
modal = Window(app, title = "a modal window")

def open_window():
    window.open()

window_button = PushButton(app, text = "open window")

def open_modal():
    modal.open(wait = True)

modal_button = PushButton(app, text = "open model")

app.display()

```

**Comment by martinohanlon** [comment]
Another option

Is creating a separate class for Window just adding more complexity.

If a learner had been happily using guizero to create single window programs using `App`, it would seem obvious that to create a 2nd Window you would create a 2nd `App`.

Would extending `App` to make it a little more 'intelligent' be a better approach?

I would also reuse the `show`, `hide` and `destroy` methods for dealing with 2nd windows.

Something like this:

```python
from guizero import App, PushButton

app = App(title="main app window")
window = App(title = "another window")
modal = App(title = "a modal window")

def open_window():
    window.show()

window_button = PushButton(app, text = "open window", command = open_window)

def open_modal():
    modal.show(wait = True)

modal_button = PushButton(app, text = "open modal", command = open_modal)

app.display()

```

Internally `guizero` could keep track of the App objects and invoke tk as appropriate.

**Comment by bsimmo** [comment]
Errm.

1st method seems logical at first.
App controls the launch as that is where it comes from, but then what happens if you have a window created from another window?

2nd mirrors App in a way and keeps it contained within itself. 

3rd is probably my the most flexible, but looses APP as the main program (from a thinking perspective they are all the same, no hiaracy).
Would that then mean all three could be the main window and App could be closed and one of the other windows can take over?  

All should inherit from the window/app they are contained within.
Otherwise colours, styles will always need setting.
My thoughts anyway.

**Comment by martinohanlon** [comment]
OK...  

So this is what I have done:

+ You can create more than 1 `App` objectin a guizero program and it acts 'normally'
+ However you receive a warning when creating multiple App objects (there should only really be 1)
+ There is a new `Window` class which when needs to be passed the an `App` when created
+ `Windows` belong to `App`'s
+ `Windows` can be made `visible` using `show` and `hide`
+ `Window.show()` accepts an optional `wait` parameter which will force the calling application to have to `wait` until this window is closed (creating a modal window)
+ in other ways `Window` acts very much like an `App`

To create a multi window application you would:

```python
from guizero import App, Window, PushButton

# app
app = App(title="Main window")

# 2nd window
window = Window(app, title="2nd window")
window.hide()

# modal window
modal_window = Window(app, title="modal window")
modal_window.hide()

# buttons to open windows
open_window_button = PushButton(app, text="Open window", command=window.show)
open_modal_button = PushButton(app, text="Open modal window", command=modal_window.show, args = [True])

# buttons to close windows
close_window_button = PushButton(window, text="Close", command=window.hide)
close_modal_button = PushButton(modal_window, text="Close", command=modal_window.hide)

app.display()

```

**Comment by martinohanlon** [comment]
in dev - targetted for 0.5.0

**Comment by lawsie** [comment]
Did I mention that you are fabulous @martinohanlon ? This looks all very logical. Do the Window objects open in the same place as the App?

**Comment by martinohanlon** [comment]
@lawsie well thank you very much. 

Its up to the window manager in the OS to decide where to put the new window, but generally they are opened overlapping the window which opened up, so you can still see the title bar.

Like this:

![image](https://user-images.githubusercontent.com/2329501/37932628-ec706050-3140-11e8-9464-d810e27e13f6.png)

**Comment by martinohanlon** [comment]
resolved in v0.5.0

**Comment by Raghavan468** [comment]
How to create application in 2nd window?@martinohanlon

**Comment by martinohanlon** [comment]
@Raghavan468 - I dont really understand your question, but you can find detail on how to use Windows in the documentation - https://lawsie.github.io/guizero/window/
