### ISSUE TITLE
Center text to the middle of the GUI 

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#163]
When a GUI is created with the simple program below the text is centered by default to the middle of the screen at the top.

Is there a way of centering it to the middle of  the GUI.

Thanks

``

from guizero import App, Text
def update_writing():    

    
     A = 100
     B = 200
   

    
     writing1.value = A
     writing2.value = B
    
    
    
     app.after(200, update_writing)

app = App(height=1000, width=1000,bg="black")

writing1 = Text(app, text="A", color="green",size=100,bg="black")
writing2 = Text(app, text="B", color="green",size=100,bg="black")

app.after(200, update_writing)
app.display()

``

**Comment by martinohanlon** [comment]
You can find information about how to change the layouts here - https://lawsie.github.io/guizero/layout/

And information about the Text widgets layout properties here - https://lawsie.github.io/guizero/text/

I dont believe there is a pre-built function to do what you want, I suspect you will have to experiment with tk's layouts.
