### ISSUE TITLE
ButtonGroup values are strings indexes from 1, should it be?

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#178]
When a ButtonGroup is created and no option values are defined, values are defined from "1" as strings.

Could this be made more consistent with other python standards by making this an integer from 0. 

It is an interface breaking change though....

**Comment by martinohanlon** [comment]
Or should `ButtonGroup.value` just return the text of the item which is selected, this is consistent with the behaviour of Combo and ListBox (when its implemented).

**Comment by lawsie** [comment]
I think there was a reason for this (otherwise as you say it's a bit weird). I think it's because I wanted it to be possible for the hidden values to be strings, so I thought that for consistency all of the hidden values should be strings. I wanted this option because I remembered it being extremely useful when I was a web dev to be able to put radio buttons on a page and for them to have a different option value to the option text. However I do remember coding this part late one night in a Cambridge hotel room so the method in my madness might be limited!!

**Comment by martinohanlon** [comment]
I like the idea of supporting "hidden" values or "id's" or "keys" (whatever they need to be called) for ButtonGroup, Combo and ListBox. They are particularly useful when presenting values from lookup lists, enums or dicts. i.e. the text shown to user is different to the id which is used internally.

An approach would be that widgets can accept either:
+ a 1d list of items which would be shown to the user and returned by `value`
+ a 2d list of items and keys, the item would be shown to the user and the key returned by `value`

e.g.

```python
combo1 = Combo(a, ["mr", "mrs", "miss"], selected="mr")
assert combo1.value == "mr"

combo2 = Combo(a, [["mr", "0"], ["mrs", "1"], ["miss", "2"]], selected="1")
assert combo2.value == "1"
```

This is similar to ButtonGroup, but at the moment if you setup ButtonGroup with a 1d list of values it creates its own set of keys (starting at "1") rather than using the item text.

I suspect the vast majority of people would use a 1d list as returning the value you set seems a simpler model and would fulfil most people's needs.

**Comment by martinohanlon** [comment]
I am implementing #180 for ButtonGroup I am coming to the conclusion that changing ButtonGroup so that if you dont provide a "key" or a "hidden value" it uses the text as the value is the right thing to do.

Leaving it as is seems at odds with the rest of guizero, for all other components the value returned is the value which is shown on the user interface.

Its also creates some oddities when you add functionality to insert or remove options from the ButtonGroup - if you insert or remove an option do you renumber the rest or leaving them as is? 

I think the functionality to have a "hidden value" is a good idea and should be left in place and also implemented for other components particular Combo and ListBox, but with the same rules, if a hidden value isn't passed the text value is used.

I hope this is ok with your @lawsie .

**Comment by martinohanlon** [comment]
This is interesting...

This comment in the ButtonGroup code:
```python
        # Loop through the list given, creating a RadioButton object from each
        # Defaults to setting the hidden value to the same as the text
```

suggests it was the original intention to set the hidden value to the same as the text.

**Comment by martinohanlon** [comment]
in v0.5.2

**Comment by lawsie** [comment]
See, I told you there was limited method in my madness. I don't know why I changed it, I can't remember, but this seems like a good solution.
