### ISSUE TITLE
example education resources

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#179]
I was looking through the example resource to check new features and noticed the request.

Here is my ramblings for GuiZero & SenseHAT.
Is that the sort of thing you want, or simpler things?

https://www.raspberrypi.org/forums/viewtopic.php?f=49&t=202386

Two example, controlling the LED array and a waffle
and
Displaying sensor data

Pi specific with a SenseHAT or Sense_emu
or x86 Desktop version with sense_emu
 unless they can get sense_emu on other platforms
Is that a problem ?

**Comment by martinohanlon** [comment]
I just had a look through your forum post. 

I like sense hat example, if you could send me a PR that would be great.

I have also added some recipes into the docs (they will go live in the next release) https://github.com/lawsie/guizero/blob/0.5.2/docs-src/docs/recipes.md if you have some simple ideas that you think would be good again it would be good to get a PR

p.s. I also updated the docs for TextBox to include 'height' (live in the next release) after seeing your comment.

**Comment by lawsie** [comment]
Nice recipes! 👍
