### ISSUE TITLE
Add recipes to documentation?

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#187]
I think it would be nice to add some recipes to the documentation.

**Comment by bennuttall** [comment]
Yes! I think snippets of useful ways of achieving something could be really useful, rather than full complete projects.

**Comment by bennuttall** [comment]
Would be happy to contribute some

**Comment by martinohanlon** [comment]
@bennuttall contributions welcome. I have already started (they arent in the documentation yet tho) - https://github.com/lawsie/guizero/blob/master/docs-src/docs/recipes.md
