### ISSUE TITLE
Investigate using python "warnings" module

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#189]
Rather than writing strings for warnings, which cannot be tested for, could the Python warnings module be used?

https://docs.python.org/2/library/warnings.html

**Comment by bennuttall** [comment]
https://docs.python.org/3/library/warnings.html

**Comment by lawsie** [comment]
I've already looked into this but the trouble with this is that the warnings look horrible in IDLE and kids don't read them.

e.g.
```python
warnings.warn('guizero warning: you are too orangey for crows')
```

...results in this:
<img width="392" alt="warning" src="https://user-images.githubusercontent.com/5183697/41543386-a33c3bb0-730e-11e8-9c37-926a84eff24d.png">

This is going to get ignored by most younger kids as "a load of boring error text". You could argue that they should be taught not to ignore it, or that it's IDLE's fault, but at the end of the day it's like that, and that's the way it is. Any thoughts on how to get around this would be most welcome!

Edit: Damn, I'll post this there then.

**Comment by martinohanlon** [comment]
I suppose the counter to this is that the majority of issues children will face when writing any code (guizero or otherwise) will be reported as red text. Should they be consistent?! 

Also this guizero program will present an error in red text.

```python
from guizero import App
a = App()
t = TextBox()
a.display()
```

![image](https://user-images.githubusercontent.com/2329501/41544077-edb68636-730f-11e8-894e-067ad274cf7a.png)

I wonder - if they are reported in black text are they any more likely to read them?

Just because its in red text it doesn't mean that the wording cant be verbose, including big old banners like the current guizero warnings.

**Comment by lawsie** [comment]
I think that in my experience it's more a case of kids seeing the first two lines of the stack trace, not having a clue what they are on about and then giving up. Also, in my program above the line throwing the error seems to be given twice - once as the line that caused the error and the string once again below as the warning. This looks horrific if you add lots of dashes and newlines like the current warnings - but maybe I'm using it wrong?

**Comment by martinohanlon** [comment]
I think its worth investigating even if to rule it out. 

The reason I suggested it, is that it very difficult to trap the warnings at the moment, which was effecting the automated testing, but there will be reasons why a user would want to trap or know "programmatically" that a warning had occurred.

**Comment by Coal0** [comment]
Just my two cents with regards to testing; trapping warnings could be done by redirecting them to a stream and then reading from the stream to see if a warning occurred (maybe by redirecting stdout, but that seems a bit messy).

**Comment by martinohanlon** [comment]
I am going to close.
