### ISSUE TITLE
pillow version

### ISSUE THREAD

**Issue by slavkoja** [lawsie/guizero#194]
In `setup.py` you have stated:
```python
install_requires=["pillow>=5"],
```
The `pillow` 5.x series has some problems with (eg. [Debian #887752](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887752)) images and then it is not in Debian (nor in Gentoo) yet. I try it with `pillow-4.3` and it works with both JPEGs & PNGs images.

I didn't inspect your code in depth (then i don't know if it is possible), but please consider to lower the version in dependencies, which will allow to use system's packages without installing the new one:
```python
install_requires=["pillow>=4.3"],
```
This will allow to package it without patching the `setup.py`.

**Comment by martinohanlon** [comment]
Ill do some tests and providing I dont find any issues I will reduce the pillow version requirement in the next release.

**Comment by martinohanlon** [comment]
In 0.5.3
