### ISSUE TITLE
Add support for fullscreen to App and Window

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#197]

**Comment by lawsie** [comment]
I used fullscreen for the all seeing Pi and it was HORRIFIC for closing down programs (a la Picamera without alpha transparency). If there is support for this then there needs to be an "ARGH close this window" key built in automatically.

**Comment by martinohanlon** [comment]
This is where I saw it. It definitely feels like an advanced feature...

**Comment by lidong-melo** [comment]
try these code as follow.

app = App(title = 'meeting console', width = 320, height = 240)
app.tk.attributes("-fullscreen",True)

**Comment by martinohanlon** [comment]
What about binding the `ESC` key to the App when it goes into full screen mode to exit?

**Comment by lawsie** [comment]
In dev.

**Comment by cdog78** [comment]
**Thankyou for the fullscreen method @lidong-melo!**
