### ISSUE TITLE
CheckBox not displaying, nothing displays after

### ISSUE THREAD

**Issue by sspence65** [lawsie/guizero#20]
from guizero import App, CheckBox
app = App()
checkbox = CheckBox(app, text="Add extra glitter")
app.display()

no checkbox displays, and any elements added after checkbox do not display either.

Python 3.5.2

**Comment by sspence65** [comment]
RESTART: C:/Users/sspence/AppData/Local/Programs/Python/Python36-32/gztest1.py 
Traceback (most recent call last):
  File "C:/Users/sspence/AppData/Local/Programs/Python/Python36-32/gztest1.py", line 3, in <module>
    checkbox = CheckBox(app, text="Add extra glitter")
  File "C:\Users\sspence\AppData\Local\Programs\Python\Python36-32\lib\site-packages\guizero\CheckBox.py", line 11, in __init__
    self.value = IntVar()
NameError: name 'IntVar' is not defined

**Comment by DougieLawson** [comment]
Simple hack to fix it is
```
--- CheckBox.py~        2017-04-22 09:36:19.640651001 +0100
+++ CheckBox.py 2017-04-22 09:37:27.260683770 +0100
@@ -1,4 +1,4 @@
-from tkinter import Checkbutton
+from tkinter import Checkbutton, IntVar

 from . import utilities as utils
```

**Comment by lawsie** [comment]
This should now be fixed (got a bit muddled up with version numbers so its 0.3.2!) Thanks for reporting :)
