### ISSUE TITLE
Add a scrollbar to a text with GUIzero

### ISSUE THREAD

**Issue by LeoLeDiouron** [lawsie/guizero#200]
Hello,

I've a little question :
I've seen we can add a scrollbar to a textbox, but not to a text

Do you have an idea how I can add this to my text with Tkinter

thanks !

Léo

**Comment by martinohanlon** [comment]
It would be useful to know what you are trying to achieve.

Text is meant to be used like a label, not really for displaying large amounts of text which you could scroll through.

If you want to have some "readonly" text on the gui which you could scroll through I would use a multi-line TextBox but disable it.

**Comment by LeoLeDiouron** [comment]
ah ok, I will continue to try with the TextBox, thank you :)

**Comment by LeoLeDiouron** [comment]
I have another question,

I currently use the textbox widget to display some datas which are updated each second,
so each second, i had new datas in my textbox,
but the textbox shows me always the firsts datas, I have to scroll to see the lasts

Do you know a way in Guizero (or in Tkinter maybe) to have the last datas displayed in the textbox ?

thx very much

**Comment by martinohanlon** [comment]
A quick google search told me that you can use the tk `.see()` method to move to the end of a tkinter Text widget.

I knocked up a quick demo, each time text is added to the TextBox it called `TextBox.tk.see(END)`:

```python
from guizero import App, TextBox
from time import time
from tkinter import END

def add_text():
    tb.value = tb.value + str(time())    
    tb.tk.see(END)
    
a = App()
tb = TextBox(a, multiline=True, scrollbar=True, width=30, height=10)
tb.repeat(1000, add_text)
tb.line_no = 1
a.display()
```

I am going to close this issue as it isnt an issue with guizero.
