### ISSUE TITLE
pip install on Raspbian 2018-06-27 Fails

### ISSUE THREAD

**Issue by MrYsLab** [lawsie/guizero#202]
Pillow fails to install. The fix is to first install libjpeg-dev with:
```
sudo apt-get libjpeg-dev
```
Once completed, the pip3 install runs without issue.

**Comment by martinohanlon** [comment]
Thanks for submitting the issue.

I just ran a test on the latest Raspbian image and didnt experience the same error.

![image](https://user-images.githubusercontent.com/2329501/42264197-dc16aa8c-7f67-11e8-95e0-63009d313d8a.png)

Is there anything special about the image your using? Lite maybe?

I will do some more tests but any additional info would be useful.

**Comment by bsimmo** [comment]
Might be the problem I had, I posted in Twitter at the last release iirc.
I forgot to find out more as it seemed to still work anyway.

**Comment by MrYsLab** [comment]
I am going to close this issue since I am now not able to reproduce it. Sorry to bother you, but I saw the error on 2 of my machines. Perhaps, I installed some other software first that hosed things for guizero - very curious ;-).

**Comment by martinohanlon** [comment]
Just tested on a complete clean install..

Could it be that you used `pip` and not `pip3` to install guizero? i.e installing for python 2 not 3?

I just tested that and it does indeed fail to compile (perhaps not unsurprisingly).

**Comment by MrYsLab** [comment]
Anything is possible, but I am pretty certain I used pip3. Again, thanks for taking the time.
