### ISSUE TITLE
word wrapping text

### ISSUE THREAD

**Issue by whodo1voodoo** [lawsie/guizero#203]
Hi,

I've been using the module to learn how to create a GUI to display tweets and was wondering if there is an easy way to word wrap text using either Text() or TextBox()? With Text() messages just extend off the edge of the windows while with TextBox the multiline uses up all the available space so often splits a word over individual lines.

Thanks,

Craig

**Comment by scotty3785** [comment]
Can be done manually with 

    from tkinter import WORD
    ...........
    textbox = TextBox(app, multiline=True, height=10, width=50, scrollbar=True, text="a multiline\ntextbox")
    textbox.tk['wrap'] = WORD

Perhaps it would be worth modifying TextBox.py to set wrapping to word by default.

**Comment by martinohanlon** [comment]
In 0.5.3. multiline TextBox wraps by "word" by default.
