### ISSUE TITLE
Font size on buttons

### ISSUE THREAD

**Issue by lawsie** [lawsie/guizero#21]
Can it be changed?

**Comment by Piece-of-pi** [comment]
It can definitely be changed.I am no expert in tkinter but a bit of research by me found the following sites that should help:
[](https://heritagerobotics.wordpress.com/2013/01/17/how-to-change-the-size-colour-and-font-of-text-in-tkinter-widgets/)
[](http://effbot.org/tkinterbook/tkinter-widget-styling.htm)
[](http://www.java2s.com/Code/Python/GUI-Tk/Buttonbackgroundforegroundandfont.htm)
Hopefully a Tkinter expert will find this and help.

**Comment by Piece-of-pi** [comment]
Oops! The links didn't work! Just copy and paste them instead:
http://www.java2s.com/Code/Python/GUI-Tk/Buttonbackgroundforegroundandfont.htm
http://effbot.org/tkinterbook/tkinter-widget-styling.htm
https://heritagerobotics.wordpress.com/2013/01/17/how-to-change-the-size-colour-and-font-of-text-in-tkinter-widgets/
By the way: as a programming amateur, i am loving being able to easily create GUIs with Python and I have already made some great programs using it already!

**Comment by Coal0** [comment]
You can change the font size on buttons just like with `Label` objects:
```python
import tkinter as tk

frame = tk.Frame()
button = tk.Button(frame, text="Click me!", font="Verdana 19 bold")
frame.pack()
button.pack()
```

**Comment by lawsie** [comment]
Added in 757beea24c8a91abe61dbd8fba0e201c03680518
