### ISSUE TITLE
ImportError: cannot import name 'Textbox' from 'guizero'

### ISSUE THREAD

**Issue by Raghavan468** [lawsie/guizero#214]
**I am using the following to import text box from guizero**
`from guizero import App, Text, Textbox

app=App(title="Hello World")

welcome_message= Text(app,text="Welcome to my app",size=40,font="Times New Roman",color="lightblue")

input_box = TextBox(app, width=30)

app.display()
`
But i am getting an error message: File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\Gui_test.py", line 1, in <module>
    from guizero import App, Text, Textbox
ImportError: cannot import name 'Textbox' from 'guizero' (C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\guizero\__init__.py)

**Comment by martinohanlon** [comment]
Capital B in TextBox

e.g.

from guizero import App, Text, TextBox

:)

**Comment by Raghavan468** [comment]
Thanks,so silly of me. It worked.
