### ISSUE TITLE
help:  button command is executed before button is pressed

### ISSUE THREAD

**Issue by Raekon** [lawsie/guizero#217]
Hi.
This is my first issue submit on Github. I hope it is allright.
I made a code with a box, in which is a couple of textboxes, a slider and a pushbutton.
the pushbutton, is behaving strangely, because the 'command' is being executed before the button (or anything else) is pushed or changed, ie. on load. 
However, if I put a lambda in the command, it works just fine... what am I doing wrong?

def photoUpload():
    global width_text
    box1=guizero.Box(app, layout="grid")
    text1=guizero.Text(box1,text="Hvor mange minutter skal der filmes? ", grid=[0,0])
    minutes=guizero.TextBox(box1,text="", grid=[1,0])
    minutes.focus()
    text2=guizero.Text(box1, text="hvor mange sekunder mellem hvert billede? ",grid=[0,1])
    timelapse=guizero.TextBox(box1,text="", grid=[1,1])
    text3=guizero.Text(box1, text="filnavn ? ",grid=[0,2])
    filename=guizero.TextBox(box1,text="", grid=[1,2])
    text4=guizero.Text(box1, text=("størrelse: "),grid=[0,3])
    picsize=guizero.Slider(box1, start=640, end=3280, grid=[1,3], command=update_size)
    slider_text=guizero.TextBox(box1,grid=[1,4])
    **button1=guizero.PushButton(app, command=printit(minutes.get(),timelapse.get(),filename.get()), text="Submit")**

def printit(minutes,timelapse,filename):
    print("virker knappen? {0},{1},{2}".format(minutes,timelapse,filename))

Best Regards.
Raekon

**Comment by martinohanlon** [comment]
When you create the PushButton you should pass the reference (i.e. the name) of the function to `command`

When you use the following code:

```python
button1=guizero.PushButton(app, command=printit(minutes.get(),timelapse.get(),filename.get()), text="Submit")
```

You are not passing a reference to `printit` you are actually running `printit()` and passing the return value to the `command` parameter.

**Comment by martinohanlon** [comment]
Its always useful if you submit code in an issue to use code tags (click the `<>` on the tool bar, so it is formatted correctly :)

**Comment by MrYsLab** [comment]
I think what you may want to do,  is to do the get's in your printint function. I took the liberty to rewrite your code as a class (I hate globals ;-) ) Take a look and I hope you find it useful:

```
class print_up:
    def __init__(self):
        app = App()
        box1 = Box(app, layout="grid")
        Text(box1, text="Hvor mange minutter skal der filmes? ", grid=[0, 0])
        self.minutes = TextBox(box1, text="", grid=[1, 0])
        self.minutes.focus()
        Text(box1, text="hvor mange sekunder mellem hvert billede? ", grid=[0, 1])
        self.timelapse = TextBox(box1, text="", grid=[1, 1])
        Text(box1, text="filnavn ? ", grid=[0, 2])
        self.filename = TextBox(box1, text="", grid=[1, 2])
        Text(box1, text=("størrelse: "), grid=[0, 3])
        self.picsize = Slider(box1, start=640, end=3280, grid=[1, 3], command=self.update_size)
        slider_text = TextBox(box1, grid=[1, 4])
        PushButton(app, command=self.printit, text="Submit")
        app.display()

    def printit(self):
        print("virker knappen? {0},{1},{2}".format(self.minutes.get(), self.timelapse.get(), self.filename.get()))

    def update_size(self):
        print('do something here')

print_up()
```

**Comment by Raekon** [comment]
Thank you both for the help.
@martinohanlon, I tried pasting the code as <code> with the toolbar, but when i previewed it, it was all in a single line.  I assumed, that maybe it had something to do with the formatting in Thonny, so I chose not to <code> it.... :-)

now, on your tip with not running the function, but referencing it, how will I pass the needed parameters to the function? Or am I going the completely wrong way around this? (I think I am... I am a complete self-made coder-noob, so I have not learned that many different "styles" of programming.
Originally I come from Basic on the C64, som I am quite procedurally minded.)

**Comment by MrYsLab** [comment]
I believe you can use the args parameter when you define the button. Something like args=[param1, param2].

To paste multiple line of code, I find it is easier to place the code between a set of 3 back ticks:
\```
Your pasted code goes here
\```
Then when you click on the preview tab, you should see the code formatted properly.
