### ISSUE TITLE
Flashing Text with GUI ZERO

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#218]
Would there be any possible way of getting text to flash on and off with GUI ZERO.

Thanks James

``````
from guizero import App, Text

def update_writing():    

    writing1.value = ('HELLO WORLD')   
    
app = App(height=2000, width=2020,bg="black")
writing1 = Text(app, text="", color="red",size=120,bg="black")
app.repeat(1000, update_writing)
app.display()

``````

**Comment by bsimmo** [comment]
I don't know if there is a tkinter method. And don't see anything in guizero
But you could create a function with the text changing to the background
colour and back again. Then use the 'after' method to keep it running after
a set time that gives a good flash speed
?

**Comment by James100000** [comment]
I will give that a try.
