### ISSUE TITLE
picture won't change grid posistion

### ISSUE THREAD

**Issue by Raekon** [lawsie/guizero#219]
Hi.

I have been playing around with events, and tried to make a picture move by clicking.
but when I click the picture (the man), the porgram carries out the first two commands, and then the console makes this error report:

> Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/guizero/event.py", line 99, in _event_callback
    callback(EventData(self._widget, tk_event))
  File "/home/pi/pythonfiles/testprogrammer/game1/game1.py", line 18, in clicked
    self.man.grid=[1, 1]
AttributeError: can't set attribute

the code is this:

```
from guizero import *

class game (object):
    def __init__(self):
        self.app=App()
        self.box1=Box(self.app, layout='grid')
        for x in range(3):  #distributing background fields making 3x3 grid
            for y in range(3):
                Picture(self.box1,image='bg150.png',grid=[x,y])
                
        self.man=Picture(self.box1,image='man_left.png',grid=[1,1])
           
        def clicked(event_data):
            print("The man was clicked")
            self.man.visible=False
            self.man.grid=[1,1]
        
        self.man.when_clicked=clicked
       
game1=game()
```
should i type the change in position differently?

thanks (and please let me know if this is the wrong forum for this kind of help)
Raekon

**Comment by martinohanlon** [comment]
The reason you are receiving an error is that you cant change the position of a widget once it has been created. 

If I was looking to move an image around I would create it in the position I wanted to, when I wanted to move it, I would destroy the old one and create it in the new position.

Raising issues against this repository is for when you believe there is a fault with guizero or you are requesting new features.

You are still welcome to raise requests for information here, but you are not likely to get a quick response as typically it is only myself and @lawsie who will answer questions.

I would recommend a Python language forum if you are looking for this type of support, you will reach a larger audience and probably get a quicker response.  The Raspberry Pi forums have a Python section who are normally very helpful. https://www.raspberrypi.org/forums/viewforum.php?f=32&sid=c3546402bca27306735c39dd6946a521
