### ISSUE TITLE
Rendering of https://lawsie.github.io/guizero/start/ broken?

### ISSUE THREAD

**Issue by DeeJay** [lawsie/guizero#22]
Rendering of https://lawsie.github.io/guizero/start/ in Firefox looks 'broken'. The second pre-formatted block seems to contain too much detail.

Source is here, but I don't know how to fix it: https://github.com/lawsie/guizero/tree/master/docs/start

**Comment by lawsie** [comment]
Oh whoops, that's weird. I'll take a look when I get a minute. The docs are auto generated from md files.

**Comment by DeeJay** [comment]
Possibly just a missing Newline between Slider and the backticks?

**Comment by DeeJay** [comment]
Confirmed. Attempting to generate a PR for this.

**Comment by lawsie** [comment]
Thanks for the PR, should now be merged and fixed :)
