### ISSUE TITLE
Can't justify text within Text widget

### ISSUE THREAD

**Issue by elimbaum** [lawsie/guizero#220]
If I create a text widget with a fixed width:

```
t = Text(app, grid=[0,0], align="left", text="testing")
t.width = 10
```

the text is centered within the widget, not aligned left. Is there some way to align/justify text within _fixed width_ text widgets?

**Comment by elimbaum** [comment]
Workaround: Create a `Box`, align that left, and align `Text` left within the box. Seems a bit hackish. Seems that there should still be a way to align not just widgets, but also text within that element.

**Comment by martinohanlon** [comment]
The grids are autosizing, so I suspect what is happening here is that when you align left it aligns it to the left of the grid, but as the grid is only as big as it needs to be to hold the text, it still ends up in the middle!  Not helpful I know

Improvements to layouts is targeted for release 0.6 and the alignment of widgets will be included.

I'll leave this issue open as a reference, but I dont intend on "fixing" anything until after 0.6.

**Comment by martinohanlon** [comment]
Text widgets (or indeed any Widget) can now be made to align to the left, right, top, bottom with the changes made in 0.6.

The solution may not be exactly what you were imagining but you can now align Text in the same way you can any other widget, see https://lawsie.github.io/guizero/layout/.
