### ISSUE TITLE
Add a "getting help" section to the documentation

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#221]
Pointers to forums where people can find help.

Including notes about raising issues in github.

**Comment by Antavatech** [comment]
Hello, has a location for getting help been defined yet?  I have a working program but I need help getting a new function to work.  Please let me know where I should raise my questions, thanks.

**Comment by martinohanlon** [comment]
I created this as lots of people were creating GitHub issues with questions like 'how do I do this'? This isn't the best place to raise them as it's only monitored by myself and @lawsie. 

I was going to add some public 'friendly' Python forums to the documentation. 

Perhaps try the Raspberry Pi Python forum. https://www.raspberrypi.org/forums/viewforum.php?f=32

**Comment by bsimmo** [comment]
We'll help you (the pi community forum) getting things working.

How close is GuiZero tied to the RaspberryPi Foundation, if it is supported
by them, I've always wondered why these projects never make use of the
forum (gpiozero etc included).

**Comment by martinohanlon** [comment]
Thank you.

The only tie between guizero and the foundation is that myself and @lawsie both work there. The dev of guizero has been completed outside of 'work time' though. The situation with gpiozero is very similar.

I often recommend the RPi forums because I really believe they are the most positive, friendly and helpful forums.

**Comment by lawsie** [comment]
Yup. I've added some stuff to the docs about getting help, but as you can see from no releases since October, Martin and I have been pretty busy and haven't had time to do much work on this. And yes, it's written mostly (my bit at least) whilst on trains or staying over in hotels on a work trip, not as part of work itself! :)

**Comment by Antavatech** [comment]
Thanks everyone for the replies.  I will open a new discussion on the RPI Forums.
