### ISSUE TITLE
Should Box have a border by default?

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#222]
Box can be a bit abstract, would it be better if it had a border? That way users will be able to see it, understand where it is placed and then decide whether to hide it or not.

**Comment by martinohanlon** [comment]
If not, it should have to ability to set a border.

**Comment by lawsie** [comment]
Maaaybe. That is actually a pretty good idea. It's always a pain in the neck to try to explain why a `<div>` is invisible so why should a box be invisible?

**Comment by martinohanlon** [comment]
included in 0.5.4
