### ISSUE TITLE
Layouts and sizes...

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#223]
So I am creating this issue to discuss layouts and sizes how to provide an easy to use (but flexible api).

**Comment by martinohanlon** [comment]
Make `auto` layout support `align` so you can make elements go to the left, right, top, bottom.

**Comment by martinohanlon** [comment]
Have the ability to be able to make a widget fill the available space provided by its container.

**Comment by martinohanlon** [comment]
Should ever widget be encased inside a frame? 

This would allow text widgets to be sized by pixels as well as characters. If the widget was sized in pixels, the frame would be size and the widget expanded to fill it.

This would also make hiding and showing widgets better as you could unpack the widget from the frame but keep the frame "alive", when you wanted to show the widget you would pack it back into the frame.

**Comment by martinohanlon** [comment]
When using "grid" you should have the ability to turn on grid lines. This would be helpful in seeing the layout.

**Comment by winkleink** [comment]
Would it be possible to set the width/height of the PushButtons with text in pixels rather than characters.

**Comment by lawsie** [comment]
I think this is covered also in #146 @winkleink - Martin is looking into it but it's nasty!

**Comment by martinohanlon** [comment]
Closing after release of 0.6, leaving #146
