### ISSUE TITLE
Change location of widgets

### ISSUE THREAD

**Issue by Gkrier** [lawsie/guizero#224]
I am not able to put  a widget in a precise location but instead my only option is grid which I cannot use with this project. How can I achieve this?

**Comment by lawsie** [comment]
Hello @Gkrier . Guizero is intended for beginners and so at the moment we only have basic options for widget positioning. You can achieve absolute positioning for widgets using tkinter (which guizero is based on) - use the 'place' layout manager. Having said that, we do intend to improve the layouts in a future release as they are currently not great!
