### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by knowledgejunkie** [lawsie/guizero#225]
This is a tracking ticket to follow the Debian Intent to Package (ITP) ticket at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907700.

guizero is a dependency of the Mu editor; I therefore intend to package it for Debian users as part of the mu-editor packaging process.

**Comment by martinohanlon** [comment]
Excellent thank you very much :)

**Comment by knowledgejunkie** [comment]
Update: earlier this week I pushed my packaging of guizero to the Debian Python Modules repository for review.

**Comment by knowledgejunkie** [comment]
My packaging of guizero has been reviewed and uploaded to the Debian NEW queue.

**Comment by martinohanlon** [comment]
Thanks for the update @knowledgejunkie - you will have to excuse my lack of debian packaging experience but I'm guessing this is a good thing? It sounds like a good thing?

**Comment by knowledgejunkie** [comment]
It is a good thing :)

Once the guizero package has been reviewed by the Debian FTP Masters (the Debian archive gatekeepers) and accepted, it will be uploaded (initially into the Debian unstable branch) and be available to install as a regular package.

**Comment by martinohanlon** [comment]
Great news, thanks a lot for you help.

**Comment by knowledgejunkie** [comment]
My python-guizero source package was ACCEPTED into Debian unstable yesterday, so I'm happy for this ticket to be closed. The package will migrate into Debian testing in due course.

**Comment by lawsie** [comment]
Thank you for your hard work @knowledgejunkie :)

**Comment by martinohanlon** [comment]
@knowledgejunkie I was wondering if I could pull on your experience re Debian packaging.

This is an area of know very little about...

So just a few questions really:
+ `0.6` of guizero has just been released. I had tagged the released (as we previously discussed) - what other responsibilities do we have?
+ re maintenance of the debian package - again is there anything I should be doing?
+ in the future if the debian package needs to change, what would I need to do?

Thanks again for your help, super job.

**Comment by knowledgejunkie** [comment]
> @knowledgejunkie I was wondering if I could pull on your experience re Debian packaging.
> 
> This is an area of know very little about...
> 
> So just a few questions really:
> 
>     * `0.6` of guizero has just been released. I had tagged the released (as we previously discussed) - what other responsibilities do we have?

As an upstream developer with software packaged for Debian (and the source on e.g. Github), once you have tagged a new release the Debian servers should notice after a few days and flag it for the Debian package's maintainer/team.

It is then up to a Debian bod (e.g. me) to check and package the new upstream version and upload it to Debian. (I'll get the new 0.6 release packaged later)

There is no requirement for upstream developers to have any involvement in the packaging process for Debian. If you do include a debian/ directory (or other packaging scripts) in your upstream source it is discarded.

>     * re maintenance of the debian package - again is there anything I should be doing?

No. If a new release has been out for some time and you would like to see it packaged, you can always file a bug against the package in Debian and ask for the new release to be packaged. However, in active teams (e.g. Perl/Python) this is rarely required and a new release will be noticed.

There are some well-documented practices that upstreams can adopt that make life easier for packagers when packaging software for Debian/Ubuntu:

[Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide)

>     * in the future if the debian package needs to change, what would I need to do?

If it's due to a new release and it's been a few weeks without a new package appearing in Debian testing/unstable (remember new package versions don't migrate into Debian's stable releases once they are cut), feel free to ping me directly, or raise a bug against the package in Debian (using reportbug, or using bugs.debian.org).

> Thanks again for your help, super job.

My pleasure

**Comment by martinohanlon** [comment]
Thank you @knowledgejunkie super helpful.
