### ISSUE TITLE
GUI ZERO Fullscreen

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#228]
Is there any way of getting full screen with  Gui Zero.
The program below dose do full screen as a example but there is a task bar at the bottom, side or top of the screen depending what version of OS one is using.
I would imagine to have full screen without the task bar you would need a keyboard break to be inserted in to the program.

I am more then satisfied with GUI ZERO it dose every thing I expect and more.
Works well with reading sensor data in large format, dose away with not having to use numerical LEDs for digital readout and just use a LCD monitor or TV.

The developer or developers have done a great job on all of this.

   

``````
from datetime import datetime, date, time
from guizero import App, Text
def update_writing():    

    F = datetime.utcnow().strftime("%H:%M:%S")
    writing6.value = F
    
app = App(height=2000, width=2000,bg="black")
writing6 = Text(app, text="F", color="green",size=350,bg="black")
app.repeat(1000, update_writing)
app.display()

``````

**Comment by martinohanlon** [comment]
There is an issue open relating to fullscreen including a code example. #197
