### ISSUE TITLE
Can't import 'App' unless in shell.

### ISSUE THREAD

**Issue by hwd2002** [lawsie/guizero#231]
I have found that I can not import the App module/library thing unless I am in the python Shell for some reason. I am probably doing something wrong here. Thanks!

     Here is a clip from the shell where I did the import and then tried to run the file:
`>>>` from guizero import App, PushButton
`>>>` 
====================RESTART: /home/pi/Desktop/guizero.py ====================
Traceback (most recent call last):
`  `File "/home/pi/Desktop/guizero.py", line 1, in <module>
`    `from guizero import App, PushButton
`  `File "/home/pi/Desktop/guizero.py", line 1, in <module>
`    `from guizero import App, PushButton
ImportError: cannot import name 'App'
`>>>` 

     The import line is identical to the one in my code:
from guizero import App, PushButton
def do_nothing():
`    `print("Nothing happened")

app = App(title="Keypad example", width=100, height=90, layout="grid")
button1 = PushButton(app, command=do_nothing, text="1", grid=[0,0])
button2 = PushButton(app, command=do_nothing, text="2", grid=[1,0])
button3  = PushButton(app, command=do_nothing, text="3", grid=[2,0])
button4  = PushButton(app, command=do_nothing, text="4", grid=[0,1])
button5  = PushButton(app, command=do_nothing, text="5", grid=[1,1])
button6  = PushButton(app, command=do_nothing, text="6", grid=[2,1])
app.display()

P.S. I am just learning how to do things on GitHub, and i haven't yet figured out the styling stuff.

**Comment by lawsie** [comment]
Hello! The problem is that your file is called guizero.py - it's trying to import itself rather than the real guizero. You need to do two things:
1) Save a copy of your code with a different filename
2) Delete the file called guizero.py

That is why things are working in the shell (guizero is correctly installed) but not in your file.

**Comment by hwd2002** [comment]
That was it. Thank you!
