### ISSUE TITLE
error: unknown option "-label"

### ISSUE THREAD

**Issue by wwj718** [lawsie/guizero#232]
`self.menubar.tk.entryconfigure(1, label="help")` will trigger an error `unknown option "-label"` on windows 10

macOS is ok

**Comment by lawsie** [comment]
Are you using a menubar within another object? Just tested this code on Windows 10, creating and then configuring the menubar object, and it works:

```
from guizero import App, MenuBar
def file_function():
    print("File option")

def edit_function():
    print("Edit option")

app = App()
menubar = MenuBar(app,
                  toplevel=["File", "Edit"],
                  options=[
                      [ ["File option 1", file_function], ["File option 2", file_function] ],
                      [ ["Edit option 1", edit_function], ["Edit option 2", edit_function] ]
                  ])

menubar.tk.entryconfigure(1, label="help")
app.display()
```

**Comment by wwj718** [comment]
thanks a lot !
it works on Windows 10, but  on macOS, It has different behavior

![image](https://user-images.githubusercontent.com/3153878/45525442-84f81c00-b805-11e8-9ecd-1b6bb48d0942.png)


The initial value of the index is different：macOS begin with 0, but Windows 10 begin with 1
