### ISSUE TITLE
Guizero layout grid issue

### ISSUE THREAD

**Issue by danielallucard** [lawsie/guizero#235]
Dear all,

I'm starting a project using python to raspberry pi 3 and the guizero to create a graphical interface for my final project on the University.

Since I'm starting to put the logotype and my name and academic number but I'm facing some issues as below.

I want to set the image on the left side and put all the information on the right side but I get this blank space between the university name and the other name.

See the code below too.

> from guizero import *
> 
> app = App(title = "Página Inicial", layout = "grid")
> app.tk.attributes("-fullscreen",True)
> logo = Picture(app, image = "Logo.png", grid = [0,0])
> logo.width = 280
> logo.height = 96
> university = Text(app, text = "Centro Universitário de Brasília - UniCeub", grid = [1,0], align = "left")
> university1 = Text(app, text = "Faculdade de Tecnologia e Ciências Sociais", grid = [1,1], align = "left")
> student = Text(app, text = "Daniel Oliveira Barbosa", grid = [1,2], align = "left")
> academic_register = Text(app, text = " 21485122", grid = [1,3], align = "left")
> app.display()

![2018-09-18-192230_800x480_scrot](https://user-images.githubusercontent.com/43387673/45711210-587f2f80-bb78-11e8-8c7c-8ab850972f8b.png)

Kind regards.

**Comment by lawsie** [comment]
Hello! Try making the logo cell span all rows of text (a bit like colspan/rowspan in HTML):

```python
logo = Picture(app, image = "Logo.png", grid = [0,0,1,3])
```

Docs page for that is here:
https://lawsie.github.io/guizero/layout/

Also, sorry - the layouts are not the best at the moment. We're working on them! :)
