### ISSUE TITLE
Add progress bar to guizero

### ISSUE THREAD

**Issue by jvigliottaa** [lawsie/guizero#238]
Is there anyway to add progress bars with guizero? I know they are possible with ttk in tkinter but I cannot find a way to create them in guizero

**Comment by lawsie** [comment]
Hi @jvigliottaa . We don't have a progress bar at the moment in guizero, however you can combine the ttk one with guizero no problem at all. Here's an example:

```
from tkinter import *
from tkinter.ttk import *
from guizero import App, Text, PushButton

def bar():
    # progress['value'] is from ttk
    if progress['value'] < 100:
        progress['value'] += 20
        app.after(1000, bar)

app = App()

gz_text = Text(app, "This is a guizero widget")

# This bit comes from ttk
# --------------------------------------------------------------------------------
progress = Progressbar(app.tk,orient=HORIZONTAL,length=100,mode='determinate')
progress.pack()
# --------------------------------------------------------------------------------

start = PushButton(app, text="Start", command=bar)

app.display()
```

**Comment by jvigliottaa** [comment]
I was able to get that to work but is there anyway to use a ttk Notebook and add Guizero widgets to it? I am having problems when trying to do this

**Comment by lawsie** [comment]
I don't think so. guizero widgets will self pack and so will need their parent widget to also be a guizero widget.

**Comment by lawsie** [comment]
@martinohanlon What do you think - potential to attempt this or close the issue? I think this is the second time it's been requested that I can remember.

**Comment by martinohanlon** [comment]
@lawise I think a progress bar is a good idea. Its a common widget found in many guis.

**Comment by martinohanlon** [comment]
I did some experimenting with the ttk.progressbar widget. While on the surface it looks to be pretty good it doesn't support some of the standard properties you would expect like 'bg'. Which would mean it wouldn't work like the rest of guizeros widgets.

On the plus side though I think it would be relatively easy to construct on using the canvas, it's a pretty simple widget.

**Comment by martinohanlon** [comment]
@jvigliottaa fyi - after some recent changes to guizero you can now embed tk and ttk widgets into your guizero app, including the ttk.progressbar widget. You will find an example here https://github.com/lawsie/guizero/blob/master/examples/tk_widget.py

**Comment by martinohanlon** [comment]
Suggest we close this issue. The tkinter progress bar fulfills the requirement and creating one for guizero would require creating one from a canvas as the to progressbar doesn't support the base requirements (e.g. color changing, text, font, sizing).

**Comment by martinohanlon** [comment]
Closing.
