### ISSUE TITLE
PushButton.py missing Enable and Disable

### ISSUE THREAD

**Issue by JSchub90** [lawsie/guizero#24]
My code:

`create_story = PushButton(app, command=print_story, text="Tell me!")

if not player_name.get():
    create_story.disable()
elif player_name.get():
    create_story.enable()`

Error: 

`Traceback (most recent call last):
  File "/home/pi/Desktop/python/VisualAdventure.py", line 32, in <module>
    create_story.disable()
  File "/usr/local/lib/python3.4/dist-packages/guizero/PushButton.py", line 59, in disable
    self.config(state=DISABLED)
NameError: name 'DISABLED' is not defined`

**Comment by lawsie** [comment]
Thanks for this, that's a bug because I haven't properly imported the DISABLED (or indeed the NORMAL) constant from tkinter. I'll fix it in the next release.

**Comment by lawsie** [comment]
I've fixed this problem and it will be in the next release. However your program still won't work as you'll need to schedule an event to regularly check whether something is typed into the player name box. Try something like this:

```
from guizero import App, Text, PushButton, TextBox

def print_story():
    print( player_name.get() )

def check_button():
    if player_name.get() == "":
        create_story.disable()
        print("Disable")
    else:
        create_story.enable()
        print("Enable")
    # Re-schedule this function call
    app.after(200, check_button)
        
app = App("Add one to a number")

player_name = TextBox(app)
create_story = PushButton(app, command=print_story, text="Tell me!")

# Check after 200ms if anything was filled in
app.after(200, check_button)


app.display()
```
