### ISSUE TITLE
PushButton error on mac os 10.14

### ISSUE THREAD

**Issue by wwj718** [lawsie/guizero#243]
![image](https://user-images.githubusercontent.com/3153878/47356276-1fe1f100-d6f6-11e8-938e-f9051778435e.png)

**Comment by martinohanlon** [comment]
Can you share the code which creates this program please.

**Comment by wwj718** [comment]
The code copied from the [document](https://lawsie.github.io/guizero/pushbutton/):

```python
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")

app = App()
button = PushButton(app, command=do_nothing)
app.display()
```

**Comment by lawsie** [comment]
I'm a bit confused by this issue. I received an email notification from GitHub about it which contained a different image (presumably you changed the image to pixelate the tabs etc. and reuploaded it). However on the original image, the text "Button" appears as normal?

**Comment by wwj718** [comment]
hi @lawsie , It sometimes works fine, but most of the time it goes wrong. The previous picture is when it is running normally.

**Comment by lawsie** [comment]
And how about if you explicitly set some text for the button - does it display normally? I will do some testing on Mac OS Mojave later.

**Comment by martinohanlon** [comment]
So I tested on `10.13.6` - Ill upgrade to `10.14` later, but I didnt experience the same issues.

Running:

```python
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")

app = App()
button = PushButton(app, command=do_nothing)
app.display()
```

Which consistently resulted in:

![screen shot 2018-10-25 at 07 28 52](https://user-images.githubusercontent.com/2329501/47480234-a4805c80-d827-11e8-966a-ebed59304f5b.png)

@wwj718 Could you test the code below? Its the same Button code just using only tkinter (i.e. without the guizero wrapper around it). Im interested to see if the issue you are experiencing is a result of tk.

```python
from tkinter import *

master = Tk()

def do_nothing():
    print("Button was pressed")

b = Button(master, text="Button", command=do_nothing)
b.pack()

mainloop()
```

You should get a little window with a Button on it.

![screen shot 2018-10-25 at 07 27 19](https://user-images.githubusercontent.com/2329501/47480181-71d66400-d827-11e8-96ca-668b93ab2012.png)

**Comment by wwj718** [comment]
```
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")

app = App()
button = PushButton(app, command=do_nothing)
app.display()
```

@martinohanlon The results are as follows


![image](https://user-images.githubusercontent.com/3153878/47489163-87c04500-d878-11e8-8391-01e9222c8718.png)

Style is different from 10.13.5

**Comment by martinohanlon** [comment]
@wwj718 

@wwj718 if you tested this code:

```python
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")

app = App()
button = PushButton(app, command=do_nothing)
app.display()
```

(which I noted works)

could you also test this code please:

```python
from tkinter import *

master = Tk()

def do_nothing():
    print("Button was pressed")

b = Button(master, text="Button", command=do_nothing)
b.pack()

mainloop()
```

**Comment by wwj718** [comment]
@martinohanlon 
![image](https://user-images.githubusercontent.com/3153878/47493126-205ac300-d881-11e8-824b-65dd811edae0.png)

**Comment by martinohanlon** [comment]
Ok, I have tested this on macOS 10.14 and I can reproduce an error with Button.

I have run the code multiple times (20+) again with no issues.

@wwj718 its my turn to be confused.

You ran this guizero code:

```python
from guizero import App, PushButton
def do_nothing():
  print("Button was pressed")

app = App()
button = PushButton(app, command=do_nothing)
app.display()
```

... and got this outcome - i.e. it worked as [I would have] expected

![image](https://user-images.githubusercontent.com/2329501/47505756-a9183580-d866-11e8-9bf4-6b68842391e6.png)

Are you saying that you dont always get this result?

**Comment by wwj718** [comment]
@martinohanlon  sorry, it is my mistake. I closed the question.

This is the problem pyinstaller caused. Maybe it was caused by packaging(macOS tk).
