### ISSUE TITLE
Small Border around Box

### ISSUE THREAD

**Issue by baslati** [lawsie/guizero#247]
Hello I wrote a rather complex GUI for my Project, 
It requires that somedays a user can click on the main window to open a guest window. 
But I only want that a few people know where to click, that's the problem, I want to have a invisible button. 
I found a way to do this on my Mac 
```
box = Box(app, grid=[1,8,10,2])
tneu2=Picture(box, image=pfad+"Leere.png")
tneu2.when_clicked=open_window
```
But when I run the same programm on my Raspberry Pi with a 23" Touchscreen it has some borders, it looks like it's only 1 or 2 Pixel in grey, but with a white Background you notice them instantly. 
The same Problem appears on jpgs or gifs. 
I also tried to use a white border around the box but it doesn't help 
![img_4066](https://user-images.githubusercontent.com/25266305/48486554-29a1d480-e81c-11e8-906d-befb8e6fa956.JPG)

**Comment by baslati** [comment]
Well, even though he isn't supposed to do it, its not a problem if he does. I found another solution, I had a blue box on my background, as part of the corporate design, I replaced this blue box with a clickable Image. 
Thank you

**Comment by martinohanlon** [comment]
Im going to close this issue as resolved.
