### ISSUE TITLE
Add kwargs to GUI Components

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#26]
Could you add **kwargs to the constructor of your GUI components and then pass it to the __init__of the base Tk class?  This way you could pass variables direct to Tk.  e.g. setting a CheckBox to be disabled at initialisation  :

```
class CheckBox(Checkbutton):

    def __init__(self, master, text, command=None, grid=None, align=None, **kwargs):  
      
        self.text = str(text)
        self.description = "[CheckBox] object with text " + self.text
        self.value = IntVar()

        try:
            super().__init__(master, text=self.text, variable=self.value, kwargs)
.....

check = CheckBox(state = "disabled")

```

I havent tested this but I think it would work.  

It would allow you to open up the functionality of Tk without having to add all the variables to each of your components.

**Comment by DavidWhaleMEF** [comment]
Also you'd need to import the whole lot of tkinter to get access to all the constants that a true Tk program requires (like related tickets that suffer from missing of the END definition).

**Comment by lawsie** [comment]
Yeah - this was the commit which broke all the constants, haven't had time to sort that out yet but need to do it soon! https://github.com/lawsie/guizero/commit/a63cf45c4b56afddb8c5d1006cdc806190121507

**Comment by lawsie** [comment]
I am now doing #38 and putting the tk object inside the guizero object. Should I add kwargs to the guizero constructor and then pass that on when creating the tk object?

**Comment by martinohanlon** [comment]
It still feels like a useful function to be able to be able to set properties of the underlying tk class at initialisation, its the difference between:

```
check = CheckBox(state = "disabled")
```

and:

```
check = CheckBox()
check.tk.state = "disabled"
```

However access to the tk object makes this less important and you would have to make a assumption / design constraint that all *kwargs would pass to the tk object.

**Comment by Coal0** [comment]
I think it'd be best to separate this- add `enable` and `disable` functions. I'll work on a PR that implements this.

**Comment by martinohanlon** [comment]
I'm happy to close this now, the interface in 0.4 is much simpler to understand and use.
