### ISSUE TITLE
"repeat" & "after" functions documentation is missing args

### ISSUE THREAD

**Issue by HaakonSvane** [lawsie/guizero#260]
I noticed that when using the _repeat()_ function and event listeners, the callback function is not allowed to take in any arguments. This can get quite frustrating when there are a lots of widgets to manage.

Example code:

```python
from guizero import App, Text


def counter(color):
    text.text_color = color
    text.value = int(text.value) + 1

app = App("Hello world")
text = Text(app, text="1")
text.repeat(1000, counter("blue"))

app.display()
```

Giving the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 608, in callit
    func(*args)
  File "/home/pi/.local/lib/python3.5/site-packages/guizero/tkmixins.py", line 30, in _call_wrapper
    function(*args)
TypeError: 'NoneType' object is not callable
^C
Process finished with exit code -1

```

**Comment by martinohanlon** [comment]
You could use lambda to do this e.g.

```
text.repeat(1000, lambda: counter("blue"))
```

**Comment by lawsie** [comment]
They do support arguments. You're using the repeat function wrong because the code you've got actually calls the function with the argument instead of setting it as the callback. Here is how you can use it with arguments:

```python
from guizero import App, Text


def counter(color):
    text.text_color = color
    text.value = int(text.value) + 1

app = App("Hello world")
text = Text(app, text="1")
text.repeat(1000, counter, args=["blue"])

app.display()
```

@martinohanlon This is in the code but isn't documented!

**Comment by martinohanlon** [comment]
@lawsie - this I just realised :)

I have changed the title of the issue.

Thanks

**Comment by bsimmo** [comment]
The function call styling is easier on the brain though and must be
beginner friendly compared to the splitting and args styling.

For me it looks easier to remember and follows the style of calling a
function that kids starting learn know about.
The args style is usually a lot lot further down the road when they learn
classes and then that's only for the really interested.
So far they terms are hidden away.

Unless that 'args' can be changed to something else to blend in with the
widget styling, from a kids point of view, the only argument they know is
their mum and dad 'discussing' how to fill a dishwashers.

**Comment by lawsie** [comment]
@bsimmo Regardless of whether it's more friendly or not, I don't think it is actually possible to use the style from the original post, because that results in the function being evaluated inline and not set as a callback. That's why he's got the error message about "NoneType" object not being callable - the code sets the return value of the function (None) as the callback. Maybe @martinohanlon knows of something I don't, but the original reason I did it in this less nice way is because the other way isn't possible.

Also, I hear you re: the dishwasher 😉

**Comment by martinohanlon** [comment]
Fixed documentation in `dev`
