### ISSUE TITLE
Drawing widget

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#262]
How about a drawing widget? A widget where you can draw pictures and shapes? 

I created a quick prototype in this branch https://github.com/lawsie/guizero/tree/drawing

You could create a robot picture :)

![image](https://user-images.githubusercontent.com/2329501/53301650-5d45bf00-384d-11e9-9b0c-5e4762aabdc6.png)

```python
from guizero import App, Drawing

a = App()

# create drawing object
d = Drawing(a, width="fill", height="fill")
d.bg = "light blue"

# drawing the shapes
d.rectangle(10, 10, 200, 200, width=10, fill_color="grey")
d.circle(50, 50, 15, fill_color="blue")
d.circle(150, 50, 15, fill_color="blue")
d.rectangle(20, 160, 190, 170, color="red", fill_color="black")

a.display()
```

The Drawing class is here https://github.com/lawsie/guizero/blob/drawing/guizero/Drawing.py

Thoughts on the API to create shapes? 

Coordinates are pixels from the top left:
 - rectangle is `x1,y1,x2,y2`
 - circle is `x,y,radius` x and y being the centre of the circle

There are 3 values for manipulating the shapes:
 - `color` - the color of the line which is used to draw the shape, defaults to `"black"`, `None` would result in no line being used
 - `width` - the width of the line, defaults to `1`
 - `fill_color` - the color used to fill in the shape, defaults to `None`, no fill, setting to a color would result in the shape being filled.

Alternatives for coords could be:

```
rectangle(x,y,width, height)
circle(x1,y1,x2,y2) # as a bounding box
```

@lawsie thoughts?

**Comment by lawsie** [comment]
I like the idea, had thought of it before but not had time to do anything about it. The attribute "width" confused me because I thought it was the width of the shape. I also think that we would have to think carefully about the easiest way to specify positions for shapes. It's confusing that a rectangle is positioned by its top left corner and a circle is positioned by its centre and a triangle would no doubt be positioned by three given coords, and I had the same problems when I made the shapes.py on the OOP course.

**Comment by martinohanlon** [comment]
I was having a think about this and specifically about if I asked "something" to create a shape what it would look like.

In summary:
+ That I could give it the least number of positions to be able to create that shape.
+ That if I gave a shape a `color`, the whole shape would be that color.
+ That I could say whether I wanted the shape to have an outline and how thick that outline should be.
+ That I could change the color of the outline of the shape.

^ given this I went back to the drawing board (pun intended) and came up with this API to draw a rectangle.

```python
def rectangle(self, x1, y1, x2, y2, color="black", outline=False, outline_color="black")
```

`x1,y1,x2,y2` are the co-ordinates of where the rectangle should be positioned.
`color` is the colour of the shape
`outline` is whether the shape should have an outline, `False` - no outline, `True` - 1 pixel outline, `2+` - specify the width of the outline
`outline_color` - the color of the outline

So this program:

```python
from guizero import App, Drawing

a = App()

# create drawing object
d = Drawing(a, width="fill", height="fill")
d.bg = "light blue"

# drawing the shapes
d.rectangle(10, 10, 60, 60)
d.rectangle(70, 10, 120, 60, color="yellow")
d.rectangle(130, 10, 180, 60, color="yellow", outline=True)
d.rectangle(190, 10, 240, 60, color="yellow", outline=5)
d.rectangle(250, 10, 300, 60, color="yellow", outline=5, outline_color="green")
d.rectangle(310, 10, 360, 60, color=None, outline=5, outline_color="red")

a.display()
```

Creates this output:

![image](https://user-images.githubusercontent.com/2329501/53450279-b3fcf580-3a13-11e9-8bc1-08c9b4727ff2.png)

As a set of principles and an API this makes sense to me.

**Comment by martinohanlon** [comment]
I have created the drawing widget, it is currently in dev waiting to be released. Super pleased with the paint app I made with it :) https://github.com/lawsie/guizero/blob/dev/examples/paint.py
