### ISSUE TITLE
Remove depreciated methods

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#265]
Several methods & properties have been depreciated in guizero over the past 12 month, pre v1.0 release they should be removed.

**Comment by lawsie** [comment]
Let's do this soon, those methods have been deprecated for at least a year.

**Comment by martinohanlon** [comment]
Removed deprecated functions, other than app.on_close which has only just been deprecated.

**Comment by martinohanlon** [comment]
in v1.0.0
