### ISSUE TITLE
Button that is called by a button performs by it self 

### ISSUE THREAD

**Issue by emistery** [lawsie/guizero#266]
Hi, I'm new to guizero (and relatively new to python) but I have the following code: 

    def delete_item(text):
        f = open("todofile.txt", "w")
        lines = f.readlines()
        for line in lines:
            if line != text + "\n":
                f.write(line)
        f.close()
    def get_items():
        i = 0
        f = open("todofile.txt", "r")
        lines = f.readlines()
    
        for object in lines:
            print(object)
            text = object
            Text(content_box, grid=[0, i], text=text, align="left")
            Text(content_box, grid=[1, i], text="                                                           ", align="left")
            PushButton(content_box, text=str(i), align="right", command=delete_item(text), grid=[1, i])
            f.close()
            i = i + 1
    
    
    app = App(title="To-Do List Proto", width=480, height=320)
    
    
    options_box = Box(app, height="fill", align="right", border=True, width=70)
    Refresh = PushButton(options_box, text="Refresh", align="top", command=get_items)
    
    content_box = Box(app, align="top", width="fill", border=True, layout="grid")

the function delete_item in the button delete_button gets called when refreshing using the refresh button.

**Comment by martinohanlon** [comment]
Your problem is here:

`command=delete_item(text),`

You are calling the `delete_item` function and setting `command` to be whatever `delete_item` returns (in this case `None`) rather than setting `command` to `delete_item`.

You can use the `args` parameter to pass the `text` parameter to the `delete_item` function e.g.

```python
PushButton(content_box, text=str(i), align="right", command=delete_item, args=[text], grid=[1, i])
```

**Comment by emistery** [comment]
Ah I see, thanks!
