### ISSUE TITLE
slider.value - print - args not working as expected

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#267]
My son has just been trying this (so I've put a quick demo to show what he was trying)

he would like to know why it's not doing what he expected. I don't know the answer

```
from guizero import App, PushButton, Slider

def message_with_args(msg):
    print(msg)
    
def message():
    print(slider.value)

app = App()

slider = Slider(app, start=10, end=100)

button = PushButton(app, command=message, text="Normal")
button_with_args = PushButton(app, command=message_with_args, text="With Args", args=[slider.value])
button_direct_args = PushButton(app, command=print, text="direct Args", args=[slider.value])

app.display()
```

using _args_ to pass to the command, rather than print(slider.value), is not reading the current value from slider, but using its original value.

I hope that explains it enough, or at least the program does.  It should print the value of the slider at the console (IDLE3) that it is currently set to, not what it was set at.

**Comment by ukBaz** [comment]
It appears that each time `slider.value` is called there is a different objectid. So when you pass `slider.value` to `args` that objectid reference is not getting updated and why you see the same value.

I've done an additional function called `message_wit_ref` that takes the reference to the slider object. The function then gets the value.

```python
from guizero import App, PushButton, Slider


def message_with_args(msg):
    print(msg, id(msg))


def message():
    print(slider.value, id(slider.value))


def message_with_ref(slider_id):
    print(slider.value, id(slider_id.value))


app = App()

slider = Slider(app, start=10, end=100)
print(slider.value, id(slider.value))
button = PushButton(app,
                    command=message,
                    text="Normal")
button_with_args = PushButton(app,
                              command=message_with_args,
                              text="With Args",
                              args=[slider.value])
button_direct_args = PushButton(app,
                                command=print,
                                text="direct Args",
                                args=[slider.value, id(slider.value)])
button_with_ref = PushButton(app,
                              command=message_with_ref,
                              text="With Ref",
                              args=[slider])

app.display()
```

Not sure if that is helpful or clear

**Comment by martinohanlon** [comment]
When this code is run:

```
button_direct_args = PushButton(app, command=print, text="direct Args", args=[slider.value])
```

A callback is created (using a lambda) of `print` and `slider.value`... 

However it doesnt work in the way of you expecting as `slider.value` is evaluated at runtime so you don't get:

```
print(slider.value)
```

You get:

```
print(10)
```

So each time the button is pressed `print(10)` is run.
