### ISSUE TITLE
How to center a window on the screen?

### ISSUE THREAD

**Issue by VonHirsch** [lawsie/guizero#279]
Is there a way to center the guizero window on the screen when launched?  I [found a solution for Tkinter](https://yagisanatode.com/2018/02/24/how-to-center-the-main-window-on-the-screen-in-tkinter-with-python-3/) involving root.geometry, but I don't see an API for that in guizero.

**Comment by martinohanlon** [comment]
There is a section in the documentation about how to use tkinter methods
