### ISSUE TITLE
Repeat loop interval time increases spontaneously

### ISSUE THREAD

**Issue by babavers** [lawsie/guizero#280]
I haven an app using 'reapeat' to refresh the GUI. The repeat interval is set to 200 ms but it slows down after a while (hours). I added print commands at the first and last line of my function in order to see where the programs 'looses' time. The function that has to be executed only takes a few thousends of a second, but the time between the exit of my function and the restart of it increases slowly without any reason. 200 ms becomes about 1,5 seconds after 8 hours.
I can see also that the CPU load increases and that extra load is taken by a process called 'Xorg' (linux on a raspberry pi). After a restart of the program everything normalises but it slowly comes back and after hours I see each time the same situation.

**Comment by bsimmo** [comment]
Pop along to the RaspberryPi Forum and the Python section there and post up
the problem and the code and people will have a look at it for you.
For the code you'll need to wrap it in [code]my code
If I = do it correctly:
    Etc
[/code]
code tags, it in the formatting menu.

https://www.raspberrypi.org/forums/viewforum.php?f=32

**Comment by martinohanlon** [comment]
Thanks @bsimmo I was going to suggest similar.

It's unlikely this is an issue with guizero. All guizero does is call tk.after.

My suspicion would be something in your program not being destroyed and resources overtime being used up. I think Xorg is the X windows manager process.

I will leave the issue open for the time being.

**Comment by babavers** [comment]
Thanks for the hint.
It's posted on the forum now with code and output.

**Comment by martinohanlon** [comment]
I replied to your forum post. Closing this issue.
