### ISSUE TITLE
updating on Raspian -U not --upgrade ?

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#29]
I think, i.e. I had to use, 
`sudo pip3 install -U guizero
`to update the package on the latest Raspbian _not_
`sudo pip3 install guizero --upgrade
`it say unknown command.

**Comment by lawsie** [comment]
Hmm...I think that command might be a muddle up between the Windows and Linux commands. On Windows it's `pip install guizero --upgrade`! Thanks for spotting, I'll update it.

**Comment by bsimmo** [comment]
might not be...  
I just tried it on another setup and it worked, 
so egg on my face... probably.   
I spent quite a while trying to find the -U command yesterday as well 

pip 9.0.1 python 3.4 (pip3 -V)
