### ISSUE TITLE
Issues with adding tkinter widget

### ISSUE THREAD

**Issue by lr10** [lawsie/guizero#291]
A tkinter widget when added always shows in the main container even if it is added to another container.

app = App("Test")
window = Window(app, "New Window")
spinbox = Spinbox(from_=0, to=10)
window.add_tk_widget(spinbox)

app.display()

In the following code, the Spinbox widget doesn't show in the New window but rather in the main window

**Comment by martinohanlon** [comment]
Ok,

In summary - when I documented `add_tk_widget` I was keen to make it as simple as possible and in doing so have not given all the information regarding multiple windows.

Typically when you create a tk widget you should include the "master" (window) that a tk widget is associated with e.g. use `app.tk` when creating the tk widget...

```
from guizero import App
from tkinter import Spinbox

app = App("Test")
spinbox = Spinbox(app.tk, from_=0, to=10)
app.add_tk_widget(spinbox)

app.display()
```

Happily if you dont, tkinter defaults this to the root toplevel (the App object) meaning you can make it simpler. 

However... If you want to put the tk widget into a container which isnt the a App (Box, Window, etc) you will need to specify it explicitly.

To fix your code you would specify `window.tk` when creating the spinbox widget:

```
from guizero import App, Window
from tkinter import Spinbox
app = App("Test")

window = Window(app, "New Window")
spinbox = Spinbox(window.tk, from_=0, to=10)
window.add_tk_widget(spinbox)

app.display()
```

The documentation should be updated to explicitly state this.

I will look at whether it is possible to dynamically set the tk widgets master after it has been created, but I tried when I first created this and it wasnt possible.

**Comment by lr10** [comment]
Thanks for the clarification. 
I have been able to fix the issue.
Thanks a lot!

**Comment by martinohanlon** [comment]
As I thought, its not possible to modify a tk widgets master after it has been created so you cannot use

```
spinbox = Spinbox(from_=0, to=10)
window.add_tk_widget(spinbox)
```

I looked at other options including clone the tk widget when its created but it leads to unpredictable results as you have to create a new object reference for the tk widget.

What I think we can do though is raise and error (or warning) if you try and add a tk widget to a container which isnt its master. e.g. creating a tk widget against the window but adding it to the app.

```python
from guizero import App, Window
from tkinter import Spinbox
app = App("Test")

window = Window(app, "New Window")
spinbox = Spinbox(window.tk, from_=0, to=10)
app.add_tk_widget(spinbox)

app.display()
```

"You can only add a tk widget to the App, Window or Box it was created for"

**Comment by lr10** [comment]
I understand. Giving a warning is not a bad idea or even making it compulsory to add the master when creating the tk widget. e.g. spinbox = Spinbox(from_=0, to=10) will be invalid if the master is not added

**Comment by martinohanlon** [comment]
Change is in `dev`

**Comment by lr10** [comment]
Great. Will check it out!
Thanks

**Comment by martinohanlon** [comment]
in 0.6.4

**Comment by lr10** [comment]
Checked it out. 
Getting a warning message when the master is not specified when creating the tkinter object.
Congrats!!!
