### ISSUE TITLE
Suggestion: when two options are available, use True/False over strings

### ISSUE THREAD

**Issue by bennuttall** [lawsie/guizero#3]
Just a suggestion, but it's something we we do with gpiozero.

In RPi.GPIO, setting up an input pin looks like:

```python
GPIO.setup(pin, GPIO.IN, GPIO.PUD_UP)
```

or:

```python
GPIO.setup(pin, GPIO.IN, GPIO.PUD_DOWN)
```

where `PUD_UP` means "pull-up or down: up" and `PUD_DOWN` means "pull-up or down: down".

In gpiozero, we assume pull-up by default, so a button created like this:

```python
button = Button(17)
```

is pulled-up. To use pull-down:

```python
button = Button(17, pull_up=False)
```

So the init parameter is `pull_up=True` by default. The logic of calling the parameter "pull_up" (after the default) rather than the name of the two options (e.g. "pull_direction") means it's unused when set to default, and to do the lesser used behaviour, it's just `pull_up=False` rather than `pull_direction="down"`.

I wondered if you might do this with things like `orient="horizontal"` as there are only two options, so it would become `horizontal=True` by default. This also removes the need to worry about casing (beyond True/true False/false of course...)

Feel free to ignore!

**Comment by lawsie** [comment]
Changed orient parameter to boolean in ButtonGroup and Slider objects for next release
