### ISSUE TITLE
App resize

### ISSUE THREAD

**Issue by bralax** [lawsie/guizero#304]
When the app goes into fullscreen mode it does not change the size(width and height) properties of the app. This makes it hard to set the size of objects based on the size of the screen. Similarly in grid mode, if the screen becomes full screen, the whole program stays in the small area.

**Comment by martinohanlon** [comment]
guizero just returns the `width` and `height` as presented by tkinter which obviously stays at the "window" size when you go full screen.

You can get the screen size from the `App`'s tk object using:

```python
from guizero import App
a = App()
screen_width = a.tk.winfo_screenwidth()
screen_height = a.tk.winfo_screenheight()
```

Im not sure what to do about this, it would be possible to modify the `App` and `Window` classes to return this value when in "full screen" mode but I wonder if this is the right thing to do.

@bralax - in regard to your question about setting the size of objects based on the size of the screen I would recommend you look to create a layout for your GUI which is dynamic and "automatically" sizes itself. Have a look at the layout section of the guizero documentation https://lawsie.github.io/guizero/layout/

**Comment by lawsie** [comment]
I think this seems to be a case where if someone wants to do this they could use the tk functionality as described above, rather than making this the default behaviour when full screen mode is activated.

**Comment by martinohanlon** [comment]
Given our comments, im going to close this then.
