### ISSUE TITLE
guizero warning***

### ISSUE THREAD

**Issue by raprap97** [lawsie/guizero#309]
good eevening, I'm a bit new at using raspberry, I usually use my friends raspberry, but when I got mine.. I copy pasted the program I made using my friends r-pi to my r-pi, then I get and error, image resizing - cannot scale the image as pil is not available.. need help please

**Comment by lawsie** [comment]
Hello @raprap97 :)

To be able to use the additional image features you will have to install them. Please read this section of the documentation for instructions on how to do this.

https://lawsie.github.io/guizero/#additional-features-install
