### ISSUE TITLE
Colour as R,G,B

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#31]
Would it be possible to implement colour/color as R,G,B values.
For instance in waffle.getpixel will return 'white', that means nothing to me, neither would blue or green or pink etc.
Hex values also mean little to me, but I do know what 200, 100, 178 means and I would then easily know and implement reducing the Green colour darker and return it back easily.

I could then set the colour pink to be any shade of pink I wanted, for example
pink=(255,190,200)

Perhaps look at the RPF SenseHat / gpiozero implementations if the have them to keep it consistant*?

**Comment by lawsie** [comment]
Hex colours are RGB, they are just represented using hexadecimal! For example, red is (255, 0, 0) in RGB format, and in hex that would be #FF0000 (FF = 255)

You can convert a RGB colour to hex like this:
`rgb = '#%02x%02x%02x' % (red, green, blue)`

(where red, green and blue are the red green and blue values you want).

The `getPixel` function returns whatever the pixel was set to - if it was set as white, it would return white. If it was set as a hex value, it would return the hex value.

**Comment by bsimmo** [comment]
I appreciate that but could it be a feature built-in so the kids don't have to create and call a conversion function everytime each way.

Having to teach the kids some funny python formatting and hex numbers isn't easy.
That's for further down the line, (I don't get all the formatting yet.)

Given this is a simplified easy to access GUI coding and like gpiozero and SenseHat, most of the faff is nicely hidden away for beginners who just need and can understand the basics.

Of course it depends what your mission aim for it is.
But there may be a good chance it'll be used alongside sense_emu and gpiozero to combine a nice all in lesson.

**Comment by lawsie** [comment]
I think I can probably add "set as RGB" and "get as RGB" functions without too much bother if that helps!

**Comment by scotty3785** [comment]
I'm happy to implement this feature in waffle.
Just need to consider what the best implementation is.
I can either replace the existing set_pixel/get_pixel/set_all/get_all methods to accept and return RGB values or I can add new methods for example `set_rgb_pixel` 
Alternative is that each method can take an optional argument letting it know that the colour is rgb. For example `set_pixel(1,1, (255,255,0), mode='rgb')`

**Comment by bsimmo** [comment]
I believe it would need to be implemented guizero wide to keep with the
ethos of how these things work.
Currently I'm using the simple method above as a function (as per the forum
thread https://www.raspberrypi.org/forums/viewtopic.php?f=49&t=202386 that
restarted this :-))

Personally I also think
guizero / gpiozero / sensehat (and sense_emu) should all share similarities
and methods of working.
Possbly give SenseHAT base colours/hex code for example, even if I don't
like them, hahaha
It just make it easy to use (which kids and teachers need).

**Comment by martinohanlon** [comment]
I agree that this should be implemented guizero wide, a number of widgets already support changing their color usually by the `bg` (background) property or specific `color` properties (e.g. PushButton.text_color).

Natively tkinter works with #rgb so it makes sense that guizero uses those values.

So, how to make it simpler and support the requirement...

I see 2 options:

1. create a color utility within guizero to allow you to easily create colors which guizero understands e.g.

```
from guizero import Color, App
a = App()
a.bg = Color(red, green, blue)
```

A `Color` helper could be intelligent with its input and also accept different variations:

e.g:

```
a.bg = Color("pink")
a.bg = Color("#ffffff")
# or any other variation you could think of
```  

2. The individual setters are capable of accepting other colors formats :

e.g:

```
a.bg = (red, green, blue)
a.bg = pink
a.bg = "#ffffff" 
```

Its worth noting that if you were to get a color from guizero it would still be represented as #rgb

I would favour option 2.

Looking at Waffle specifically, I think it should implement:

 - a `bg` property which will get or set the background.
 - set_pixel - could accept a color as either a single text variable or as a tuple of (red, green, blue). set_pixel would integrate the color variable at run time and if found to be a tuple convert it to a `#rgb`

This way you create a flexible interface and the user doesnt have to be explicit.

**Comment by martinohanlon** [comment]
linked to #95

**Comment by lawsie** [comment]
I like option 2 as well. I think it's important to be able to specify colours in both formats, plus the keyword format.

**Comment by martinohanlon** [comment]
This change is in dev, it will go in 0.4.5.

See [https://github.com/lawsie/guizero/blob/dev/docs-src/docs/colors.md](https://github.com/lawsie/guizero/blob/dev/docs-src/docs/colors.md)

**Comment by scotty3785** [comment]
Just an additional "far too late" suggestion on this one. There is a tkinter method to get an RGB color from a named color.  tk.winfo_rgb('white') will return (65535, 65535, 65535) divide that by 256 to get (255,255,255).
Might be useful if the end user expects to always get an RGB value from the waffle.
