### ISSUE TITLE
Scrollbar option on Boxes and windows

### ISSUE THREAD

**Issue by MateusVDT** [lawsie/guizero#310]
I had to tweak with pagination on my calculator app, it would have looked much better if I could just scroll trough my work.

**Comment by martinohanlon** [comment]
A guizero Box is essentially a tkinter Frame and there is unfortunately no way of attaching a scrollbar to a Frame.

I would look for other ways of achieving the same thing (like pagination), but you could potentially achieve this by using a native tkinter Canvas. There is some details in the documentation about using tk widgets and guizero https://lawsie.github.io/guizero/usingtk/
