### ISSUE TITLE
Options in the menu bar should be able to have arguments

### ISSUE THREAD

**Issue by PilleniusMC** [lawsie/guizero#312]
I'm currently working on something and I saw that you can't use function arguments in the menu bar, is tkinter the limiting factor there or is it just not built into guizero. If it is just guizero, that might be a nice to have feature.

**Comment by martinohanlon** [comment]
I'm not sure this should made part of guizero it would complicate the API and you could use a lambda to do the same thing e.g. 

```python
from guizero import App, MenuBar
def file_function(somedata):
    print("File option")

def edit_function():
    print("Edit option")

app = App()
menubar = MenuBar(app,
                  toplevel=["File", "Edit"],
                  options=[
                      [ ["File option 1", lambda: file_function("somedata")] ],
                      [ ["Edit option 1", edit_function], ["Edit option 2", edit_function] ]
                  ])
app.display()
```

**Comment by PilleniusMC** [comment]
Somehow I completely forgot lamda is a thing, that can be used. That seems easy enough.

**Comment by martinohanlon** [comment]
thanks, im going to close this then.
