### ISSUE TITLE
Add file dialogs

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#316]
Tk has some really useful dialogs (popups) for getting file / folder names.

https://pythonspot.com/tk-file-dialogs/

These would be a nice addition to guizero allow people to use the standard operating system dialogs for working with files.

Top level I think it looks like 3 new popups:
 - `open_file` - show the file dialog with an "open" button
 - `open_folder` - show the file dialog with an "open" button but you can only select a folder
 - `save_file` - show the file dialog with a "save" button

All these 3 would return the path of the file / folder and `None` is cancel was pressed.

I have some concerns that the method names suggest that the app would actually **open** / **save** the file. Some alternative which spring to mind, but im not sure i like them anymore:
 - `get_file_name`
 - `show_open_file`
 - `open_file_popup`

**Comment by lawsie** [comment]
What about
- `select_file`
- `select_folder`
- `select_save_location` 

...or similar? Otherwise I agree, people may get confused with thinking we have implemented the functionality for them too.

**Comment by scotty3785** [comment]
I had this same internal debate when adding these on a local branch of guizero. I like @lawsie's suggestions of select_file etc.

**Comment by martinohanlon** [comment]
I have made a prototype, its in https://github.com/lawsie/guizero/tree/file-dialogs

I went with `select_file` and `select_folder`.

```python
def select_file(title="Select file", folder=".", filetypes=[["All files", "*.*"]], save=False, master=None):
    """
    Display a box to select a file to open or save.

    If Open or Save is pressed the filename path is returned.

    If Cancel is pressed `None` is returned.

    :param string title:
        The title to be displayed on the box. Defaults to 'Select file'.
    :param string folder:
        The initial folder to open. Defaults to '.'.
    :param list filetypes:
        A list of file descriptions and wildcards of file types to display. 
        Provide as a list of lists e.g. ::
            filetypes=[["Text documents", "*.txt"], ["CSV files", "*.csv"]]
    :param boolean save:
        The default value for the response box.
    :param App master:
        Optional guizero master which the popup will be placed over. Defaults
        to `None`.
    :return:
        The path of filename selected or `None`.
    """

def select_folder(title="Select folder", folder=".", master=None):
    """
    Display a box to select a folder.

    If a folder is selected the folder path is returned, otherwise `None` is returned.

    :param string title:
        The title to be displayed on the box. Defaults to 'Select file'.
    :param string folder:
        The initial folder to open. Defaults to '.'.
    :param App master:
        Optional guizero master which the popup will be placed over. Defaults
        to `None`.
    :return:
        The path of folder selected or `None`.
    """
```

To select a file and "open it":

```python
app.select_file()
```

To select a file and "save it":

```python
app.select_file(save=True)
```

To select a folder:

```python
app.select_folder()
```

Thoughts?

**Comment by martinohanlon** [comment]
Added into `dev`. Ready

**Comment by martinohanlon** [comment]
in v1.1.0
