### ISSUE TITLE
Current combo box values not correctly passed over as args to other functions?

### ISSUE THREAD

**Issue by sierrajulietromeo** [lawsie/guizero#317]
Firstly, this I want to say this is great and props for all your hard work  (and other contributors). I am having great fun with it and am hoping to use it with students in September.  

I am making an application which starts with an initial app.  Upon pressing a button, this calls a function that then creates a window.

This new window has a 3 combo boxes, a text box and a button. My intention was that when the button was pressed, this would call a function to insert a record into an sqlite db. I was passing over as: 

button = PushButton(booking_window, text='Confirm booking', grid=[2,7], command=confirm_booking, args=[client_dropdown.value,trip_dropdown.value,int(num_pass.value),request_box.value])

My issue was that the values that were being passed over to the function (confirm booking) were the default values of the combo boxes, no matter if I had changed the value of the combo boxes.   I know I can call a function when a different option is selected from a combo, but this seemed like an unnecessary step. When I push a button it should (imo) take the value of the combos there and then.

My workaround for this was to create the windows initially on startup of the application (outside of functions), then immediately hide them.  The widgets for the windows were then created outside of functions at the bottom of my code.   Then, combo.value was then in global scope to my other functions, and then when I used combo.value, the correct value of what I had selected from the combo was available.

To me this just seems to create more complex code, I'd rather create windows via functions, rather than declaring all the details globally.  This may be a current limitation of guizero, or it may be a limitation of my knowledge (or my reading).       I hope this all makes some sense, and I thank you again for your efforts

**Comment by lawsie** [comment]
Hi Steve. If you pass the actual widgets as the args and not their value, then inside the command function you can query the current value of that widget and use it in your db query. Here's an example:

```
from guizero import App, Combo, PushButton, Window, TextBox

def confirm_booking(combo1, combo2, combo3, textbox1):
    print("I am writing these database values")
    print(combo1.value, combo2.value,int(textbox1.value),combo3.value)

def make_window():
    booking_window = Window(app)
    client_dropdown = Combo(booking_window, options=["Original 1", "New 2"])
    trip_dropdown = Combo(booking_window, options=["Original 2", "New 2"])
    request_box = Combo(booking_window, options=["Original 3", "New 3"])
    num_pass = TextBox(booking_window, text="1")
    
    button = PushButton(booking_window, text='Confirm booking', command=confirm_booking, args=[client_dropdown, trip_dropdown, request_box, num_pass])


app = App()

open_window = PushButton(app, text="Open booking window", command=make_window)
original_text = TextBox(app)


app.display()
```

I believe that the reason it doesn't work the way you originally did it, is that when you create the PushButton with the command and the args, guizero secretly makes a lambda behind the scenes of the function name + the args, so it's frozen at the original values. If the original values are just references to the widgets, that is still useful, and so you can use that reference to then query the current values.

**Comment by sierrajulietromeo** [comment]
Ahhhhhhhhh. :-)   Thank you for the prompt support! Sorted.   :-)
