### ISSUE TITLE
AttributeError: 'App' object has no attribute 'question'

### ISSUE THREAD

**Issue by BoxOfCereal** [lawsie/guizero#318]
This error appears with the example code from the documentation

```
from guizero import App, PushButton, Text

def button_pressed():
    name = app.question("Hello", "What's your name?")
    # If cancel is pressed, None is returned
    # so check a name was entered
    if name is not None:
        hello.value = "Hello " + name

app = App()
button = PushButton(app, command=button_pressed, text="Hello")
hello = Text(app)
app.display()
```

**Comment by lawsie** [comment]
Hi @BoxOfCereal this isn't an error. I suspect you haven't upgraded guizero and you're running an earlier version - this functionality was added in 1.0.

**Comment by BoxOfCereal** [comment]
Hi, I am sorry for the unnecessary issue.

**Comment by lawsie** [comment]
No problem at all - did this fix the problem for you? :)

**Comment by lawsie** [comment]
(Sorry, I realised that my original comment sounded quite abrupt - it wasn't meant to sound rude, I was actually just writing it really quickly in between looking after a small child!!)
