### ISSUE TITLE
License for Docs

### ISSUE THREAD

**Issue by LouisPi** [lawsie/guizero#32]
Just a question/issue concerning the license for the documentation. Am I allowed to use a quote from the documentation? If the answer is yes, is there a bit of text I have to insert to show this is not my work? Thanks in advance, 
LouisPi

**Comment by lawsie** [comment]
That's fine. The license for the project is here - https://github.com/lawsie/guizero/blob/master/license.txt - you could just link to that if you quote something.

**Comment by LouisPi** [comment]
Okay, thanks for the help. Perhaps rewording this so it says that it include the docs not just the code would be useful in the future. 
Thanks,
LouisPi

**Comment by lawsie** [comment]
The license text is a standardised BSD 3-clause license. I didn't write it! :)
