### ISSUE TITLE
Add 'show' to TextBox so it can be used for passwords

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#320]
So that characters can be stars *

from guizero import App, TextBox

app = App()
textbox = TextBox(app)
textbox.tk.config(show="*")
app.display()

**Comment by lawsie** [comment]
Derp, that's an obvious omission, sounds like an excellent plan. We obviously can't call it show though, but trying to think of what to call it is hard!

**Comment by martinohanlon** [comment]
I was thinking about a `password` property which could be set as `True` or `False` or the character to be used.

Setting to `True` would set the `show` character to `"*"`, setting it to a character would set it to the character to be used. e.g.

Use the default * character.

```python
password_box = TextBox(app, password=True)
```

Use an alternative character.

```python
password_box = TextBox(app, password="#")
```

**Comment by lawsie** [comment]
I am just wondering whether kids or inexperienced programmers might think that putting`password=True` might somehow create a log in system. I can't think of anything else sensible to call it though. Let's do it.

**Comment by ukBaz** [comment]
Would `HideText` or `HideCharacters` be a better parameter name?

**Comment by martinohanlon** [comment]
`hide_text` is a reasonable alternative. Set to `True` / `False` or a character.

**Comment by lawsie** [comment]
Great, thanks for the suggestion @ukBaz :)

**Comment by martinohanlon** [comment]
Added `hide_text` to `TextBox`. In `dev`. Ready

**Comment by martinohanlon** [comment]
in v1.1.0
