### ISSUE TITLE
Allow application icon to be set

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#321]

**Comment by winderlopezg** [comment]
@martinohanlon in the meantime you can add the **iconbitmap** property of tkinter to the App object
`app = App(title)`
`app.tk.iconbitmap('icons8.ico')`
`app.display()`
the only drawback is that it must be with extension .ico

**Comment by martinohanlon** [comment]
Thank you @winderlopezg .
My intention would be that guizero would automatically scale and convert any image to an .ico if pillow (PIL) was available otherwise you would only be able to specify an ico. This is similar to how images work.

**Comment by k1ffx** [comment]
I'm a GitHub novice and a recent devotee of guizero, but nevertheless thought this might be relevant:
`app.tk.call('wm', 'iconphoto', app.tk._w, tkinter.PhotoImage(file='./appicon.png'))`

**Comment by martinohanlon** [comment]
The change is in dev. Target v1.2.0

```python
app.icon = "filename.gif"
window.icon = "filename.gif"
```

If PIL is installed you can use other filetypes outside of GIF.
If the `icon` is set on an `App` it will cascade to all child windows.
If the `icon` is set on a `Window` it will NOT cascade to other `Window` objects or the `App`.

Needs testing on macOS and Linux.

**Comment by martinohanlon** [comment]
Tested on macOS. Nothing "breaks". Although there is no icon visiable because macOS doesnt have app icon. I would deem that a success then :)

**Comment by martinohanlon** [comment]
I was wrong about macOS.  There is a visible icon. Its on the bottom bar (I forget what its called). So whats cool.

![image](https://user-images.githubusercontent.com/2329501/100717340-d161af00-33b1-11eb-918d-281fccbfab02.png)

**Comment by martinohanlon** [comment]
Tested on Linux. It also works. Happy dayz. Ready for live.

**Comment by martinohanlon** [comment]
Merged in dev branch
