### ISSUE TITLE
Latest version in pip is outdated

### ISSUE THREAD

**Issue by WAUthethird** [lawsie/guizero#322]
I was installing guizero through pip on Windows, and it seems that the latest version being installed is 0.6.4, when the actual latest version is 1.0.0. Should be an easy fix, though.

**Comment by lawsie** [comment]
I think it's likely that your version of pip is out of date, because the version on PyPI is 1.0. Try running this command to update pip and then try again and see if it works?

`python -m pip install --upgrade pip setuptools wheel`

**Comment by martinohanlon** [comment]
1.0.0 is definitely available 

![image](https://user-images.githubusercontent.com/2329501/62538281-508cb480-b84a-11e9-8301-c6044047bc42.png)

You may also need to tell pip to upgrade if you have previously install guizero

```
pip3 install guizero --upgrade
```

**Comment by WAUthethird** [comment]
That seems to have been the problem -- pip was outdated. Thanks!
