### ISSUE TITLE
Add a summary of all the widgets to the documentation

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#323]
A simple table where people can browse all the widgets / popups available and link out to the specific page with all the details.

Kind of like a cheat sheet.

**Comment by martinohanlon** [comment]
It was suggestion from the FL course.

**Comment by lawsie** [comment]
It's a thumbs up from me. With pictures! This is something I could do in my copious amounts of free time (ha ha) :D

**Comment by martinohanlon** [comment]
I did this...  Closing
