### ISSUE TITLE
guizero 1.00 not workin in a venv environment

### ISSUE THREAD

**Issue by lstromeyer** [lawsie/guizero#324]
I have noticed an issue where guizero 1.0.0 will not properly function in a python venv environment. I have a window pop-up but nothing displays on it. However, it functions just fine on guizero 0.6.4. Wondering why this is and if it could be fixed?

**Comment by martinohanlon** [comment]
Can you provide some additional information about what you are doing, including instructions on how you create the virtual env and your code.

1.0.0 was developed in a virtual environment and there is no significant difference between 0.6.4 and 1.0.0 so I'm not sure what might be your issue.

**Comment by lstromeyer** [comment]
Sorry did a little more digging. It seems that one of the callback functions hangs on 1.0.0 versus 0.6.4 (nothing to do with virtual environment). It cannot seem to read from a serial port in 1.0.0 (and just gets stuck there) but functions just fine 0.6.4. Any thoughts on why and how to fix it?

**Comment by martinohanlon** [comment]
Can you share your code? Or can you give some more information. What is the callback? When is / should it be triggered. 

I don't have enough information to suggest a solution.

There was a change in v1.0.0 to resolve a race condition in after / repeat so if you are using that you code might have been inadvertently been affected https://github.com/lawsie/guizero/issues/296

**Comment by martinohanlon** [comment]
Closing.
