### ISSUE TITLE
ListBox not being set correctly

### ISSUE THREAD

**Issue by WAUthethird** [lawsie/guizero#326]
I have a list that has lots of data in it, each in its own entry. I want to display each entry in this list in a ListBox on separate items without giving `items` the explicit list; however, there ends up being a single item with the names of each entry, separated by a single space, which is not the behavior I expected. What follows is some sample code to illustrate my point:

```python
from guizero import App, ListBox

templist = ["red", "green", "blue", "yellow", "purple", "turquoise", "pink", "orange", "black", "brown", "cyan"]

app = App(title='ListBoxTest')
listbox = ListBox(app, items=[templist])

app.display()
```

The expected behavior is this:
![expected](https://user-images.githubusercontent.com/17788745/62825882-d755d000-bb6f-11e9-972b-c2c69e8db3cc.PNG)

But what actually happens is this:
![whathappens](https://user-images.githubusercontent.com/17788745/62825888-f7858f00-bb6f-11e9-9e16-c44c0adca0cb.PNG)

**Comment by ukBaz** [comment]
It appears you had a bracket around `templist` when defining `listbox` that was causing the change in behaviour.
I made the following change:

```python
from guizero import App, ListBox

templist = ["red", "green", "blue", "yellow", "purple", "turquoise", "pink", "orange", "black", "brown", "cyan"]

app = App(title='ListBoxTest')
listbox = ListBox(app, items=templist)

app.display()
```

which gave me:

![Screenshot from 2019-08-10 20-49-30](https://user-images.githubusercontent.com/8608260/62826267-67b40500-bbb0-11e9-927e-c76a57838627.png)

**Comment by WAUthethird** [comment]
@ukBaz Alright, that seems to have worked. Thanks!

**Comment by martinohanlon** [comment]
Thank you @ukBaz
