### ISSUE TITLE
Event to track when a window/widget is resized.

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#327]
```
app.when_resized = my_func
```

Im not sure its possible but worth looking into.

**Comment by meltwater2000** [comment]
This would be very helpful to allow adjustments of widget items dimensions when window is resized.

**Comment by martinohanlon** [comment]
> This would be very helpful to allow adjustments of widget items dimensions when window is resized.

Maybe. Generally my advice for creating "dynamic" UIs is to use the auto layout and aligns. This way they should auto size.

There is more info in the layout section in the docs https://lawsie.github.io/guizero/layout/

**Comment by martinohanlon** [comment]
I think this is the event which is needed.

```
bind("<Configure>", resize)
```

Examples suggest it will work for widgets and windows.

**Comment by martinohanlon** [comment]
Some more investigation into this.

The <configure> event is called for a whole host of different events, not just resizing the window. In order to create an event just for `when_resized`, the events would have to be filtered. To filter them the event manager would have to hold in state the size of the widget and if the size had changed update the widget.

**Comment by martinohanlon** [comment]
To keep this simple I recommend we create a `when_configured` which maps directly to the tk `<Configure>`. It is getting really complex to do a `when_resized` and I am concerned about compatibility across different operating systems.

**Comment by martinohanlon** [comment]
When you bind to <Configure> to a container (say the App) it returns all the events for all the widgets inside that container. 

For things like <Click> that makes a lot of sense, you want to know the App has been clicked even if its actually a Text widgets inside the App. 

For <Configure> what this means is that you get multiple events each time a container is changed returns different values e.g. the App is resized, this will generate 1 event for the app returning its new size (cool), but also an event for every widget inside the App with their new sizes, but you couldnt tell which was which (not cool).

**Comment by martinohanlon** [comment]
I have created a prototype for `when_resized` - https://github.com/lawsie/guizero/commit/2c17a04e4b921d2382018d820dc8d818dda2da5f

I think its a bit "messy". The code is in the `Base` class whereas I feel it would be better managed within the `EventManager` code The need to "filter" configure events so they are just resize events means that the EventManager cant be used as is.

**Comment by martinohanlon** [comment]
In retrospect I think this is ok. To do anything else would be adding boilerplate for the sake of it. If new functionality requires something similar in the future, it can be refactored.

Pushing to dev. Ready for release.
