### ISSUE TITLE
Create templates for issues

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#333]
We should create templates for raising issues. 

The default "Bug report" and "feature request" are pretty good templates.

I couple of things I think we should ask/add to the "Bug report" template are:

- what operating system (macOS, Windows, Linux, Raspbian) are you using?
- have version of guizero are you using?

**Comment by ukBaz** [comment]
To state what you have probably thought of: It often helps to give people instructions on how to get the answers to those sort of questions as part of the template

**Comment by lawsie** [comment]
I've just done this. I committed it straight to master and now I'm running away in case that causes a merge conflict. :D

**Comment by martinohanlon** [comment]
Merging changes back into dev to avoid future merge conflicts...

**Comment by martinohanlon** [comment]
This looks great :)
