### ISSUE TITLE
Text overflowing from Combo widgets

### ISSUE THREAD

**Issue by PilleniusMC** [lawsie/guizero#334]
This is a question and request at the same time, is there a way to manage text overflow and text alignment in a combo widget, and if there is not, could a method for that maybe get added?

**Comment by martinohanlon** [comment]
Do you mean where the text within the combo is longer than will fit in the combo? e.g.

![image](https://user-images.githubusercontent.com/2329501/63939144-d923fc80-ca66-11e9-85bd-9aea53994c3e.png)

I dont think there is a mechanism within tkinter (what guizero uses to render the GUI) for managing overflow. I did notice that you can put "\n" characters in the text to break it up though. e.g.

![image](https://user-images.githubusercontent.com/2329501/63939301-3ddf5700-ca67-11e9-9a47-125b85795517.png)

**Comment by PilleniusMC** [comment]
My main issue is the alignment of the text inside the widget. But yes, with overflow I do mean when the text is too long to fit.

**Comment by martinohanlon** [comment]
Some googling led me to this "solution". You can set the `wraplength` and the `justify` config in tk. e.g.

```python
from guizero import App, Combo

app = App()
combo = Combo(app, ["Some reallly realllllly reallllllllllly realllllllllllllllly long loooooonnnnnggggg lonnnnnnnnnnnnnnngggggggggggggggg text."])

combo.tk.config(wraplength=200)
combo.tk.config(justify="left")

app.display()
```

![image](https://user-images.githubusercontent.com/2329501/63940557-0920cf00-ca6a-11e9-9f37-c6959fecf3e0.png)

You have to specify the wraplength in pixels, even though a combo size is set in chars, *shrug* seems to be yet another example of tk weirdness, but it works as expected.

Given the relatively complicated nature of the implementation and the fact it can be done through tk,  I dont think this could be implemented into the guizero API.

**Comment by PilleniusMC** [comment]
Now for me the only question is, if it is possible to just not show any text after a certain threshold. So not even wrapping anymore but just cutting off.

**Comment by martinohanlon** [comment]
I dont think there is anything in tkinter which will help you do this. 

You could however simply truncate the text to the right length before you put it into the Combo.

**Comment by PilleniusMC** [comment]
Through googling I found out, that the module supports styles that might do that automatically, I'll be looking into that more later.

**Comment by martinohanlon** [comment]
Closing
