### ISSUE TITLE
Sample Code Typo - Recipes Page

### ISSUE THREAD

**Issue by DZisopoulos** [lawsie/guizero#339]
Typo under your [Recipes page](https://lawsie.github.io/guizero/recipes/)

In the "Get Some Text" section code

`name = TextBox(app. text="Enter your name")`

needs a comma instead of a full stop

`name = TextBox(app, text="Enter your name")`

**Comment by martinohanlon** [comment]
Thanks for letting us know. It will be fixed in the next release.

**Comment by martinohanlon** [comment]
In `dev`, ready.

**Comment by martinohanlon** [comment]
in v1.1.0
