### ISSUE TITLE
Have drawing function that requires x, y integers accept (x, y) tuple

### ISSUE THREAD

**Issue by emailman** [lawsie/guizero#340]
All of the drawing elements require one or more x, y pairs to be provided as integers.  I can see some instances where providing a tuple with two integers would be more convenient.  For instance, I could have a function calculate a point and return a tuple, then use the tuple to draw something.

**Comment by martinohanlon** [comment]
Couldn't you just use * i.e.

```python
coords = (x1, y1, x2, y2)
drawing.line(*coords)
```

**Comment by emailman** [comment]
Martin,
Good idea.  Thanks,
Eric
