### ISSUE TITLE
Wrap in a TextBox is inconsistent and immutable

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#343]
When a multiline TextBox is created, the 'wrap' is set to word if it has scrollbars and none if it doesnt.

It should be consistent.

`wrap` is also immutable (without changing the tk config), should a property be created?

**Comment by GoodClover** [comment]
Having the ability to change the wrapping would be great,
I'm using a `TextBox` with scrollbars and it doesn't seem possible to disable the wrapping which is annoying for what I want to do.

Having the option for a horizontal scrollbar would be a must.

**Comment by martinohanlon** [comment]
Change is in dev. `wrap` is consistently set to `"word"` by default. Added a `wrap` property which can be set to `True` / `False` to turn wrapping on / off.
