### ISSUE TITLE
Cant set the value of a TextBox if its disabled

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#344]
**Describe the bug**
If a `TextBox` widget is disabled, a programmer cannot set the `value` when it is disabled.

**To Reproduce**

Running the following program will result in an empty TextBox being displayed as it is not possible to set the value when it is disabled. No errors will be displayed.

```python
from guizero import App, TextBox
a = App()
tb = TextBox(a, enabled=False)
tb.value = "some text"
app.display()
```

**Expected behaviour**

That the text in the TextBox is updated. While the TextBox is disabled for user entry, the API should still be able to manipulate the value.

**Screenshots**

**System information:**
 - OS: Windows
 - guizero version: 1.1

**Comment by meltwater2000** [comment]
I can confirm I've experienced this issue.  This also occurs when using the tb.append() and tb.clear() too, no changes are made when the TextBox is disabled.

**Comment by martinohanlon** [comment]
in v1.1.1
