### ISSUE TITLE
Question: Is guizero threadsafe?

### ISSUE THREAD

**Issue by pootle** [lawsie/guizero#347]
I want to use it for a simple UI that communicates with an app I wrote driven through a socket. Would be nice to have a separate thread that waits for messages on the socket, and updates the UI appropriately

**Comment by martinohanlon** [comment]
The question you need to research is 'is tkinter threadsafe'? guizero doesn't use threads exclusively, although it does make use of tkinter's `after` function to queue tasks to happen 'later'.

From past experience the thing you need to be careful of is making sure that a single thread updates the GUI, so you may need to implement some sort of IPC to talk between your socket thread and your GUI thread. I would use either Queue or Event.

**Comment by pootle** [comment]
Ah! same as tkinter then - I've written a little wrapper for sockets that uses tkinter's createfilehandler so I can run in a single thread
