### ISSUE TITLE
Add a color chooser box to widget App

### ISSUE THREAD

**Issue by maroph** [lawsie/guizero#349]
Would like to have a color chooser box as method on the App widget. Seems to be pretty simple. In fact I have already tested it on the dev branch in my local git but can't create a pull request.

    Source dialog.py:
    def select_color(color=None, master=None):
        ret_color = colorchooser.askcolor(color=color, parent=None if master is None else master.tk)
        if ret_color is None:
            return None
        return ret_color[1]

    Source base.py:
    def select_color(self, color=None):
        return dialog.select_color(color, master=self)

**Comment by lawsie** [comment]
Sorry, not ignoring this. Must have missed it over Christmas! Seems perfectly reasonable - @martinohanlon ?

**Comment by martinohanlon** [comment]
I agree. I wasn't aware there was a color chooser dialog.

@maroph was there a particular reason you couldn't send a PR? It would be good to keep the history.

Doc's will need updating and it would be good to have a test (if possible)

**Comment by maroph** [comment]
@martinohanlon  when creating a Pull Request in my PyCharm IDE I get "Permission denied". See my attached snapshot
![snapshot](https://user-images.githubusercontent.com/1909126/74667426-90423a80-51a3-11ea-8f7e-d4fcc8b21464.png)

**Comment by ukBaz** [comment]
Hi @maroph ,

It looks like you didn't create a `fork` of `guizero` to your user. It would be from the copy/fork in your account that you would submit the `pull request`.

Links to a couple of tutorials that might help:
https://guides.github.com/activities/forking/
https://www.jetbrains.com/help/pycharm/contribute-to-projects.html#

**Comment by maroph** [comment]
@ukBaz My fault: seems that PyCharm can only clone repositories :-( To make it a fork I have to fork the project on my GitHub account and than import "my" project into PyCharm. Will give it a try at next weekend

**Comment by lawsie** [comment]
Thanks @ukBaz :) Yes, it looks like you're directly trying to push to the main repo which it won't let you do. Would love to have a PR! :)

**Comment by martinohanlon** [comment]
#352

**Comment by martinohanlon** [comment]
added to v1.2.0. :)
