### ISSUE TITLE
Attribute Error Text Object with Guizero

### ISSUE THREAD

**Issue by mrusherwood01** [lawsie/guizero#350]
**Describe the bug**
AttributeError: 'Text' object has no attribute 'set'

I have copied the code for the cat generator app under the help section of the guizero main website.

Code is below:

# What is your cat name?
# Randomly generates a cat name and displays it on a gui
# Requires guizero - sudo pip3 install guizero

from guizero import App, Text, Picture, PushButton
import random

def cat_name():
    first_name = random.choice(["Mr", "Fluffy", "Whiskers", "Ginger", "Tiddles", "Tabitha", "Princess"])
    last_name = random.choice(["Bigglesworth", "Snugglybottom", "Padfoot", "McTickles", 
  "Floofyface", "Longtail", "Fluffball", "Hairball", "Fishbreath"])
    cat_name.set(first_name + " " + last_name)

app = App("What's your cat name?")

greeting = Text(app, "Your cat name is...", color="green", size="36")

pic = Picture(app, "cat.gif")
generate_name = PushButton(app, cat_name, text="Tell me")

cat_name = Text(app, text="...")

app.display()

**System information:**
OS Windows and OS MAC - tried this on both
![guizero issue](https://user-images.githubusercontent.com/60692185/73833085-46e80780-4801-11ea-8688-cd18815b9358.PNG)

**Comment by lawsie** [comment]
Hi @mrusherwood01 - the resource that is based on is from 2017, and since then the `set` method has been deprecated and then removed from guizero. There is now a new property you can use called value, which is consistent across all widgets. Change the line to:

```
cat_name.value = first_name + " " + last_name
```

:)
