### ISSUE TITLE
Fill and sizing behaviour with Grid unpredictable 

### ISSUE THREAD

**Issue by meltwater2000** [lawsie/guizero#354]
**Describe the bug**
When using Grid the position and size of widgets are not consistent.

**To Reproduce**
Run the following code with GRID=True:
- Widgets are not centred or resized to fit window (from start or when resized).
- width="fill" does not fit the window (defaults to fixed value width~650)

```python
from guizero import App, TextBox, Text
GRID=True
if GRID:
    a = App(width=300, layout="grid")
    TextBox(a, text="Single No Fill", grid=[0,0])
    TextBox(a, text="Single Fill", width="fill", grid=[0,2])
    TextBox(a, text="Multiline No Fill", multiline= True, grid=[0,3])
    TextBox(a, text="Multiline Fill", multiline= True, width="fill", grid=[0,4])
else:
    a = App(width=300)
    TextBox(a, text="Single No Fill")
    TextBox(a, text="Single Fill", width="fill")
    TextBox(a, text="Multiline No Fill", multiline= True)
    TextBox(a, text="Multiline Fill", multiline= True, width="fill")
a.display()
```

**Expected behaviour**
Behaviour is expected to be similar to auto layout, widgets are centred and filled to edges.  Layout is scaled to fit window, even when resized.

**System information:**
 - OS: Windows
 - guizero version: 1.1.0

**Additional context**
Advice on getting nice layouts are welcome.
Currently trying to display 3x3 widgets with two filled TextBoxes below (using grid span).

It looks like using Box objects will allow a mix of layouts (grid in one Box object and then fill within a separate Box object).

**Comment by martinohanlon** [comment]
There is probably nothing that can be done to make your "grid" layout work the same as the "auto" layout. It is up to the window manager (OS) to distribute the space on the screen and you have only "limited" control.

I suspect as you are using a grid layout the OS is "reserving space" to the right which you never fill. You wouldnt use a grid if you only expected to have 1 column.

![image](https://user-images.githubusercontent.com/2329501/75100802-af3d3400-55ca-11ea-86ea-79d56c93d2ff.png)

grid layouts are typically used to create left or right justified tables or forms of data where you want to align widgets of different sizes together e.g.

![image](https://user-images.githubusercontent.com/2329501/75100940-d137b600-55cc-11ea-835b-9b3304428ce3.png)

If you want your widgets to fill the screen, auto layout is the way to go, separating differing sections with Boxes.

Here is an example of creating a 3x3 matrix of buttons with 2 text boxes across the bottom using auto layout, fill, align and boxes.

```python
from guizero import App, Box, TextBox, PushButton

app = App()

# create the matrix of buttons
for y in range(3):
    # create a box which spans the width of the app
    button_box = Box(app, align="top", width="fill")
    for z in range(3):
        # put 3 buttons in, aligned to the left edge, filling the available space
        PushButton(button_box, align="left", width="fill")

# create a box for the buttons
textboxes_box = Box(app, align="top", width="fill")

TextBox(textboxes_box, width="fill")
TextBox(textboxes_box, width="fill")

app.display()
```

![image](https://user-images.githubusercontent.com/2329501/75100966-6c309000-55cd-11ea-94a9-35022762b106.png)

There is a lot of information and tips on using layouts in the documentation https://lawsie.github.io/guizero/layout/

**Comment by meltwater2000** [comment]
Many thanks for your response.
Aligning all to one side in auto layout works nicely, thank you for your help.
