### ISSUE TITLE
matplotlib inside guizero?

### ISSUE THREAD

**Issue by JamesFordV3** [lawsie/guizero#356]
**Hello everyone!**
It is possible to add figure inside box/windows of guizero?

```python
for example:
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

i want to add this inside of this box inside app:
```python
from guizero import App, Box, Text
app = App(title="My app")
box = Box(app)
text1 = Text(box, text="Plot:", size=14, text_color="red", font="Arial")
app.display()
```

or is there other math plot library which i can add inside guizero?

**Comment by martinohanlon** [comment]
This has been asked before. https://github.com/lawsie/guizero/issues/351

**Comment by JamesFordV3** [comment]
Thank you very much, i couldnt find nothing about it (in google also).
