### ISSUE TITLE
Register "when_closed" Callback - Run function when app is closed

### ISSUE THREAD

**Issue by scotty3785** [lawsie/guizero#358]
**Is your feature request related to a problem? Please describe.**
Would be helpful to have a `when_exit` event to register a callback when the application/window is closed

**Describe the solution you'd like**
Add a `window.when_closed = myCallback` feature to guizero

**Describe alternatives you've considered**
This can currently be done with `app.tk.protocol('WM_DELETE_WINDOW', myCallback)` but this isn't a 'noob' friendly method.

**Comment by martinohanlon** [comment]
You mean like this one :)

https://lawsie.github.io/guizero/alerts/#examples

```
from guizero import App, Text

# Ask the user if they really want to close the window
def do_this_when_closed():
    if app.yesno("Close", "Do you want to quit?"):
        app.destroy()

app = App()

title = Text(app, text="blank app")

# When the user tries to close the window, run the function do_this_when_closed()
app.when_closed = do_this_when_closed

app.display()
```

**Comment by scotty3785** [comment]
Monday morning fail....
Should have looked there rather than the events page. 
Closed! Sorry Martin!

**Comment by lawsie** [comment]
*resists the opportunity to make a 'do this when closed' joke about this issue* :D
