### ISSUE TITLE
Image does not fill pushbutton on when app runs on MacOS

### ISSUE THREAD

**Issue by emailman** [lawsie/guizero#359]
**Describe the bug**
When the attached program is run on MacOS, the image only fills the bottom, right quarter of the button.  When run on Windows, the image fills the button.

**To Reproduce**
Run the attached program with Pillow available.

**Expected behaviour**
The image should fill the pushbutton.

**Screenshots**
See attached.

**System information:**
 - OS: MacOS
 - guizero version: on MacOS: 1.0.0
 - Pillow version on Mac 6.2.1

[p1.zip](https://github.com/lawsie/guizero/files/4376321/p1.zip)

<img width="271" alt="Mac Image Problem" src="https://user-images.githubusercontent.com/11335689/77447975-b1133680-6dc6-11ea-85a7-9a803077af99.png">

**Additional context**

**Comment by martinohanlon** [comment]
This was a pain to diagnose. For some reason (just on macOS) if a button has a non empty textvariable when an image is applied the images top left corner of the text.

Fix will be in v1.1.1. I also refactored some of the image handling code so images can be removed and reapplied to buttons.
