### ISSUE TITLE
Improve documentation and install process for use in school environments

### ISSUE THREAD

**Issue by whaleygeek** [lawsie/guizero#36]
The problem with pip is it will by default try to install the package in a 'dist directory' which is mostly in a protected directory on school setups, so that means they can't use this lovely package.

If you documented other install procedures, more schools that have locked down IT systems will be able to use this.

I believe based on discussions just now on twitter that guizero is zero dependency. That means you ca do any of the following:

1. from github press the clone or download button, then download as zip. Unzip the zip file and copy the guizero folder into the students home folder, and then they should be able to just write python and import guizero and it *should* all work. This completely avoids bumping into any school protected directory issues.

2. If the school PC has write access to the distdir on the computer C drive, you might be able to run this from a command line:

python setup.py

My preference is (1) as in all the schools I work in, the dist-dir of python is in a read-only folder on the network or on the local disk and cannot be modified. 

The fact that the guizero folder is in the same folder as the children's code means that when you 'import guizero' it will find it (That's the purpose of the __init__.py in  guizero so it is recognised as a package folder).

Hope this helps - but it would be great if someone could update the README to describe this as the preferred method of installation, and offer the pip install option as an alternative route for schools that have much less locked-down environment.

**Comment by tjguk** [comment]
@whaleygeek does pip --user work in the constrained environments you describe, or is that just pushing the bump along the carpet?

**Comment by whaleygeek** [comment]
Interesting thought. I'll give it a go next time I am in the school with the super locked down environment! Thanks

**Comment by martinohanlon** [comment]
Included in v0.4 - closing
