### ISSUE TITLE
model win doesn't release grab if we destroy it

### ISSUE THREAD

**Issue by Richard0610** [lawsie/guizero#365]
**Describe the bug**
model win doesn't release grab if we destroy it

**To Reproduce**
from guizero import App, Window, TextBox, PushButton

def winDestroy():
    # win.tk.grab_release()
    win.destroy()

app = App()
# app.set_full_screen()
textBox = TextBox(app, text='123')
win = Window(app, title='modal')
PushButton(win, text='close', command=winDestroy)
win.show(True)
app.display()

----------
1. run the program
2.push the button, not close by the left-up side of window
3.the button will run function: winDestroy

then the focus can't give back to textBox

**Expected behaviour**
release grab, give back the focus

to fix it, just unmark # win.tk.grab_release()

**System information:**
 - OS: Mac
 - guizero version: 1.1.0

**Comment by martinohanlon** [comment]
It probably shouldn't behave in this way but you could use win.hide rather than win.destoy 

```python
PushButton(win, text='close', command=win.hide)
```

**Comment by Richard0610** [comment]
yes, but for little system, I'm afraid of resource insufficient.
so I always try to release them all.

**Comment by martinohanlon** [comment]
I would suggest you use:

```
win.hide()
win.destroy()
```

The call to `.destroy` does as it says, stops the execution of the widget regardless of the current state. It can leave the application the an unknown state (hence why you experienced problems with modal windows).

Also note once an widget has been destroyed it can no longer be used within an application, so if you wanted to show the win again, the call will fail because it has been destroyed.

**Comment by martinohanlon** [comment]
I was just thinking about this.

I dont think the `destroy` method of `Window` should be changed to close the modal window if its still open. `destroy` should remain a discrete call to tk which does as it says "destroys" the window regardless of its state. There may be use cases where its useful to do this. 

Its the programmers job to ensure that the application's state is managed correctly.

The documentation should be updated to make this clear that "destroy terminates the widget regardless of current state of the application".

**Comment by martinohanlon** [comment]
closing in favour of #367
