### ISSUE TITLE
ListBox tk Functionality not Usable

### ISSUE THREAD

**Issue by philCFG** [lawsie/guizero#366]
Attempting to use ListBox.tk functionality fails with the message:
  File "/home/pi/DF/DF_Prog/listbox test guizero.py", line 15, in <module>
    listbox.tk.selection_set(3)
AttributeError: 'Frame' object has no attribute 'selection_set'

According to the ListBox documentation ListBox "Contains a tkinter.Listbox object"
Reading the source code it appears that ListBox.tk points to a tk Frame object but should point to the _listbox object. 
Replacing 
listbox.tk.selection_set(3)
by
listbox._listbox.tk.selection_set(3)
does work but is not mentioned in the guide to using .tk functionality

**To Reproduce**
Run the attached code

**Expected behaviour**
The list box selection should be set to item  3 ("three") and the background colour to red.

**System information:**
 - OS: Lubuntu 18.04
 - guizero version: 1.1.0
 - python version: 3.6.9
[listbox test guizero.txt](https://github.com/lawsie/guizero/files/4528302/listbox.test.guizero.txt)

**Comment by martinohanlon** [comment]
It looks like the documentation is incorrect. the master tk widget in ListBox is a frame. This is because ListBox actually contains a listbox and a scrollbar wrapped in a frame.

You can use the private property to get to the internal listbox widget. I havent tested but something like this.

```python
listbox._listbox.tk.selection_set(3)
```

**Comment by martinohanlon** [comment]
@philCFG I am assuming you are using `selection_set()` to select one (or more) items in the ListBox?

This seems like a reasonable thing to want to do. I suggest we had a `select` method to the ListBox widget to do this.

**Comment by philCFG** [comment]
listbox._listbox.tk.selection_set(3)
does work, as I mentioned in my report.
I am using selection_set() to highlight items in the listbox. 
   listbox.value = itemstring
also works but it seems clumsy to use the string.

**Comment by martinohanlon** [comment]
I have been reviewing this and I think this is mainly a documentation exercise.

Some Widgets (ListBox included) are compound "widgets" (i.e. they contain multiple widgets, normally encased in a tk frame).

All the "internal" widgets can be accessed via the `.children` property which returns a list of all the child widgets contain in the `ListBox` compound widget

So, in this example to gain access to the `tk` property of the internal listbox you would use.

```
listbox.children[0].tk
```

I think we should change the documentation to:

1) remove the `contains a [tk thing]` at the top of the description for each widget. It reinforces the misconception that each guizero widget only hold 1 widget + in the ListBox example its incorrect.

![image](https://user-images.githubusercontent.com/2329501/100104723-733b4600-2e5e-11eb-94fb-2f2952df551f.png)

2) include the `tk` property in the list of properties for each widget showing which type tk object is returned

3) include the `children` property in the documentation for the `ListBox` and `ButtonGroup` compound widgets which describes what widgets are returned in the list.

4) document the "internal" widgets for `ListBox` and `ButtonGroup` compound widgets so users can interact with them directly

**Comment by martinohanlon** [comment]
>4. document the "internal" widgets for ListBox and ButtonGroup compound widgets so users can interact with them directly

I decided against this. I would generate a lot of documentation which I couldn't think of a reason anyone would need (them being internal widgets). Instead I will add a section on "Using ListBox/ButtonGroup tk widgets"

**Comment by martinohanlon** [comment]
I did however make some minor changes to create discrete class names for the internal objects so their `.description`'s are more representative.

**Comment by martinohanlon** [comment]
Document changes made in branch v1_1_1

**Comment by ethanpil** [comment]
I have been faced with similar frustratingquestions this week while working with guizero. I think the "Working with Tkinter" section on the page with the Listbox widget should be added to every page with, at minimum the name of the Tkinter widget being used and a link to the tkinter documentation page for it... Can I help with this?

**Comment by lawsie** [comment]
> > 4. document the "internal" widgets for ListBox and ButtonGroup compound widgets so users can interact with them directly
> 
> I decided against this. I would generate a lot of documentation which I couldn't think of a reason anyone would need (them being internal widgets). Instead I will add a section on "Using ListBox/ButtonGroup tk widgets"

See Martin's earlier comment, I think he decided against this as it would add extra complexity to the docs pages when what we're aiming for with guizero is simplicity for beginners. Using an internal tkinter widget is something that we don't prevent you from doing, but is something that more advanced users do, and I think that for most people if they've got to the stage where they are starting to ask 'but what tkinter widget is inside here' they can probably fairly happily find the code repo and have a look? Unless I've got the wrong end of the stick and that's not what you mean?
