### ISSUE TITLE
pytest machine dependend errors

### ISSUE THREAD

**Issue by maroph** [lawsie/guizero#370]
**Describe the bug**
I have configured the guizero development environment on 2 machines: a Raspberry Pi 3b with Raspian 10 and a Debian 10 system running as WSL on my Windows 10 notebook. When I run pytest I have 16 failed tests on both machines. Most of the failures depend on the default font in use. On Raspbian the default font seems to be Tinos and on the WLS Debian system DejaVu. Both fonts aren't in the list of expected fonts so the tests fail.

Additional I have on both machines the following failure:

test_window.py::test_getters_setters - assert 500 == 666

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to direcory tests
2. Run 'pytest -v' and then 'pytest --lf -v'  to see only the failed tests

**System information:**
 - OS: Raspbian 10 and WLS Debian 10
 - guizero version: current sources in the dev branch

**Additional context**
The error log for both machines are added.
[pytest_raspbian10.log](https://github.com/lawsie/guizero/files/4667735/pytest_raspbian10.log)
[pytest_wls-debian10.log](https://github.com/lawsie/guizero/files/4667736/pytest_wls-debian10.log)

**Comment by martinohanlon** [comment]
I have seen these issues in the past. In comes down to the fonts being available and tkinter trying to be helpful in mapping fonts. 

e.g.

`.font = "Arial"` sets the font, but tkinter then changes this to `Helvetica` so doing `assert .font == "Arial"` fails.

I found this article which might be useful about font available in tkinter https://www.xspdf.com/resolution/50958509.html#:~:text=List%20available%20font%20families%20in%20%60tkinter%60%2C%20Arial%20(corresponds,and%20Verdana%3A%20Font%20object%20Fonts.

I wonder if we could use some of the TK default fonts? To look at in 1.2

**Comment by martinohanlon** [comment]
Modified the tests to pick a font from a list of "suitable fonts" at startup. All tests pass on Windows, macOS, Raspberry Pi OS. If a suitable font cannot be found the tests exit reporting "no suitable test font found".

In `dev` for release with 1.2
