### ISSUE TITLE
Border attribute to PushButton

### ISSUE THREAD

**Issue by Grizzly09** [lawsie/guizero#371]
Hello 
I'm working on simple GUI and my problem is I want my buttons to be borderless.
I might have missed some possible any help will be appreciated.

**Comment by martinohanlon** [comment]
There might be styling you can do via tkinter. 
There is info on the tkinter button widget here https://effbot.org/tkinterbook/button.htm

And info on how to use the underlying tkinter widgets from guizero here. https://lawsie.github.io/guizero/usingtk/

Other than that, you could create your own button images.

**Comment by Grizzly09** [comment]
> There might be styling you can do via tkinter.
> There is info on the tkinter button widget here https://effbot.org/tkinterbook/button.htm
> 
> And info on how to use the underlying tkinter widgets from guizero here. https://lawsie.github.io/guizero/usingtk/
> 
> Other than that, you could create your own button images.

I tried borderwidth and bd also highlightthickness configs but no success so far.
