### ISSUE TITLE
interpreter mode PNG image display (only)

### ISSUE THREAD

**Issue by dgn1** [lawsie/guizero#372]
Using the image recipe provided in interpreter mode works great and as expected. 
When I try to incorporate this into a programme (to show an image and update it periodically), this does not. (no picture at all -- just app window with grey background. 
Note: Only attempting to display one image...same directory...being updated and annotated once every 6 seconds (ish). 

![image](https://user-images.githubusercontent.com/42422593/84729132-f3c95280-af60-11ea-950e-c4cd4800b701.png)

Any advice appreciated...

**Comment by martinohanlon** [comment]
Can you share your program code pls.

**Comment by dgn1** [comment]
Hi Martin, 
Thanks for responding. Below is an abridged version of the code used. There are a lot of statements relating to the other ADC values assigned to variables for display which I have removed for purposes of clarity. If you would like the entire code, let me know and I'll provide it. 

Thanks in advance. 
-------------------------------------abridged code----------------------------
# cha (Cantonese = 'difference')
#
# Note: abbridged version to foster troubleshooting collaboration
#
# desired: GUI to indicate various parameters measured by sensors positioned throughout a box
# 
# get function libraries
#
import time                             # used for time (ontological)
import subprocess                       # used to make system calls
import serial                           # used to communicate with USB devices (relay8,gpio32)
import os,sys					        # allow operating system functions
import subprocess				        # allow comm conduits (pipes) to other programmes
import datetime                         # user for time-stamping
from guizero import App, Picture        # gui bits
#
#
# for the test date
#
test_date = str(datetime.datetime.now().date())
#
app = App()                             # establish display
#
punits = " kPa"                         # pressure units (for display)
funits = " cm^3/min"                             # uncertain if flow units are calibrated
#
# NOTE: basis.png is the basis picture (diagram of unit -- yet to be drawn for and provided to me...so using any picture (a T.A.R.D.I.S will do) from web as sample)
#
# differentiate between usbgpio units?
#
try:
  result0 = subprocess.check_output("ls /dev/ttyACM* | wc -l",shell=True)
except:
  result0="0"
#
try:
  result1 = subprocess.check_output("ls /dev/ttyACM0",shell=True)
  result1 = result1.decode("utf-8")         # from bytes 2 string type
except:
  result1=""
#
# missing anything?
#
if int(result0)==0:
  print("NO ADC units apparently plugged in. Please plug in and restart (prog).\n Continuing will be fruitless - terminiating execution now.")
  exit(0)
#
# make sense of the results (assign s/w to hardware-stamped value to reduce entropy)
#
if len(result1) > 0:
  print("checking acm0....")
  test0 = serial.Serial(result1.rstrip())
  test0.timeout=1
  temp = test0.readline()
  test0.write('id get\r'.encode())              # manually set previously
  temp = test0.read(19)                         # get ID
  if len(temp) < 10:
    temp = test0.readline()
    test0.write('id get\r'.encode())
    temp = test0.read(19) 
    print("2nd try temp="+temp.decode("utf-8"))
  test0.close()
  temp = temp.decode("utf-8")
  if ( str(temp.split("\r")[1]).rstrip()=='unit0001' ):
    print("unit 1 found at ...."+result1.rstrip())
    test1 = serial.Serial(result1.rstrip())
    test1.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0002' ):
    print( "unit 2 found at ...."+result1.rstrip())
    test2 = serial.Serial(result1.rstrip())
    test2.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0003' ):
    print( "unit 3 found at ...."+result1.rstrip())
    test3 = serial.Serial(result1.rstrip())
    test3.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0004' ):
    print( "unit 4 found at ...."+result1.rstrip())
    test4 = serial.Serial(result1.rstrip())
    test4.timeout=1
print("Prepratory Success: ADC device interrogated and assigned. Proceeding...")
#
# minimize bogusness
#
try:
  len(str(test1))
except:
  test1=""    
#
# start with the basis
#
pic = Picture(app, image="basis.png")
#
#
temp = ''
pfan1in = ''
#
while (1):
  if len(str(test1)) > 0:                           # go to unit #1
    test1.write('adc read 1\r'.encode())            # read the adc value
    temp = test1.read(19)                         
    if len(temp) < 10:                              # if bogus, then try again
      temp = test1.readline()
      test1.write('adc read 1\r'.encode())
      temp = test1.read(19) 
    temp = temp.decode("utf-8").split("\n\r")[1]    
    pfan1in = temp                                  # assign to variable
    print("pfan1in="+temp)
    #
  print("...got a value for Pressure Fan 1 Input....now to plot....")
  # annotate using this imagemajik:
  # composite label:{label as string} -geometry {+x+y} {basis image} {resulting image with overlay}
  # add pfan1in
  xoff=10
  yoff=10
  cmd_str = "composite label:"+pfan1in+punits+" -geometry +"+str(xoff)+"+"+str(yoff)+" basis.png "+"basis2.png"
  #print(cmd_str)
  result0 = subprocess.check_output(cmd_str,shell=True)
  #
  pic = Picture(app, image="basis2.png")
  # hoping this (above) would update for every updated picture
  # - this is done for 16 values in total...slow ADC hardware, so cycle every 6 seconds
  # - want to have image with updated overlay'd values displayed (replacing any former)
  # 




-------------------------------------abridged code----------------------------

**Comment by dgn1** [comment]
?!? Regarding the above: this was from unformatted ASCII ...Sorry....

 `# cha (Cantonese = 'difference')
#
# Note: abbridged version to foster troubleshooting collaboration
#
# desired: GUI to indicate various parameters measured by sensors positioned throughout a box
# 
# get function libraries
#
import time                             # used for time (ontological)
import subprocess                       # used to make system calls
import serial                           # used to communicate with USB devices (relay8,gpio32)
import os,sys					        # allow operating system functions
import subprocess				        # allow comm conduits (pipes) to other programmes
import datetime                         # user for time-stamping
from guizero import App, Picture        # gui bits
#
#
# for the test date
#
test_date = str(datetime.datetime.now().date())
#
app = App()                             # establish display
#
punits = " kPa"                         # pressure units (for display)
funits = " cm^3/min"                             # uncertain if flow units are calibrated
#
# NOTE: basis.png is the basis picture (diagram of unit -- yet to be drawn for and provided to me...so using any picture (a T.A.R.D.I.S will do) from web as sample)
#
# differentiate between usbgpio units?
#
try:
  result0 = subprocess.check_output("ls /dev/ttyACM* | wc -l",shell=True)
except:
  result0="0"
#
try:
  result1 = subprocess.check_output("ls /dev/ttyACM0",shell=True)
  result1 = result1.decode("utf-8")         # from bytes 2 string type
except:
  result1=""
#
# missing anything?
#
if int(result0)==0:
  print("NO ADC units apparently plugged in. Please plug in and restart (prog).\n Continuing will be fruitless - terminiating execution now.")
  exit(0)
#
# make sense of the results (assign s/w to hardware-stamped value to reduce entropy)
#
if len(result1) > 0:
  print("checking acm0....")
  test0 = serial.Serial(result1.rstrip())
  test0.timeout=1
  temp = test0.readline()
  test0.write('id get\r'.encode())              # manually set previously
  temp = test0.read(19)                         # get ID
  if len(temp) < 10:
    temp = test0.readline()
    test0.write('id get\r'.encode())
    temp = test0.read(19) 
    print("2nd try temp="+temp.decode("utf-8"))
  test0.close()
  temp = temp.decode("utf-8")
  if ( str(temp.split("\r")[1]).rstrip()=='unit0001' ):
    print("unit 1 found at ...."+result1.rstrip())
    test1 = serial.Serial(result1.rstrip())
    test1.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0002' ):
    print( "unit 2 found at ...."+result1.rstrip())
    test2 = serial.Serial(result1.rstrip())
    test2.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0003' ):
    print( "unit 3 found at ...."+result1.rstrip())
    test3 = serial.Serial(result1.rstrip())
    test3.timeout=1
  if ( str(temp.split("\r")[1]).rstrip()=='unit0004' ):
    print( "unit 4 found at ...."+result1.rstrip())
    test4 = serial.Serial(result1.rstrip())
    test4.timeout=1
print("Prepratory Success: ADC device interrogated and assigned. Proceeding...")
#
# minimize bogusness
#
try:
  len(str(test1))
except:
  test1=""    
#
# start with the basis
#
pic = Picture(app, image="basis.png")
#
#
temp = ''
pfan1in = ''
#
while (1):
  if len(str(test1)) > 0:                           # go to unit #1
    test1.write('adc read 1\r'.encode())            # read the adc value
    temp = test1.read(19)                         
    if len(temp) < 10:                              # if bogus, then try again
      temp = test1.readline()
      test1.write('adc read 1\r'.encode())
      temp = test1.read(19) 
    temp = temp.decode("utf-8").split("\n\r")[1]    
    pfan1in = temp                                  # assign to variable
    print("pfan1in="+temp)
    #
  print("...got a value for Pressure Fan 1 Input....now to plot....")
  # annotate using this imagemajik:
  # composite label:{label as string} -geometry {+x+y} {basis image} {resulting image with overlay}
  # add pfan1in
  xoff=10
  yoff=10
  cmd_str = "composite label:"+pfan1in+punits+" -geometry +"+str(xoff)+"+"+str(yoff)+" basis.png "+"basis2.png"
  #print(cmd_str)
  result0 = subprocess.check_output(cmd_str,shell=True)
  #
  pic = Picture(app, image="basis18.png")
  # hoping this (above) would update for every updated picture
  # - this is done for 16 values in total...slow ADC hardware, so cycle every 6 seconds
  # - want to have image with updated overlay'd values displayed (replacing any former)
  # 



`

**Comment by martinohanlon** [comment]
Ok, I can't debug your code because it is incomplete. If you can recreate the issue in a shareable program I can debug the problem.

However... the first thing I noticed is that you have an infinite loop in your code.

while (1)

It's very likely this is stopping your GUI from working. There is an article in the guizero docs about this https://lawsie.github.io/guizero/blocking/

I am going to close the issue as it is not a big with guizero.

**Comment by dgn1** [comment]
Hi Martin,

The code was complete and worked for me...but I accept that my 
environment is likely different from yours.

The infinite loop was in order to continue to acquire data from the ADCs.

Your hint provided was very informative and appreciated.

I've since simplified the programme more and attempted to incorporate 
non-blocking code:

import time
import subprocess
from guizero import App, Picture
n=0
cmd_str = "composite label:"+str(n)+" -geometry +10+10 basis.png 
basis2a.png"

def counter():
   global n
   cmd_str = "composite label:"+str(n)+" -geometry +10+10 basis.png 
basis2a.png"
   result0 = subprocess.check_output(cmd_str,shell=True)
   n=n+1
   print(n)

app = App("cha")                             # establish display
pic = Picture(app, image="basis2a.png")   # use any picture ..call basis.png
pic.repeat(5000, counter)
app.display()

But, the updated picture is still not being shown in the window.

Included are the two basis and basis 2a images I'm using for testing.

**Comment by dgn1** [comment]
p.s. Fair enough (your call to close this). Sorry for any bother. 
If you do get some time, feel free to provide further advice.

**Comment by martinohanlon** [comment]
The first thing I would try is expressing the full path when assigning the image.

```
pic = Picture(app, image="/path/to/image/basis2a.png")
```

The default path used by python isn't the path where the .py file is located is where the program is being run from.

**Comment by dgn1** [comment]
Thanks. Just tried specifying the absolute path...but no effect (I had 
them all in the same directory) / output remains unchanged.

**Comment by martinohanlon** [comment]
Just ran a test, I had to change a few things (command being run, image being displayed) and I could see no issues.

There is nothing "wrong" with your program. I can only assume its environmental.

![image](https://user-images.githubusercontent.com/2329501/85011679-cc89a580-b159-11ea-94e7-36c8dbf52daf.png)

**Comment by dgn1** [comment]
Hi Martin,

Thanks.

My example also works when I adjust the programme as you have.

The issue is updating. Your code does not update the picture (as the 
command you run is 'dir' (to list the directory contents), rather than 
compose (which was intended to overlay the current count over the 
picture to display).

in my case 'composite' is part of the imagemagick (www.imagemagick.org 
<http://www.imagemagick.org/>) suite. I'm running this on the latest 
Debian. (It overlays the count atop the (basis) image file and renders 
into a new file).

The problem I'm having is that once pic is displayed in the app, it can 
not or does not change (update)...even when the image IS changed.

Please let me know anything else I could try...

M

**Comment by martinohanlon** [comment]
Ok. I think I see what you are trying to do.

If the image file on disk has changed a Picture widget which displays that image file won't 'automatically' reload it. The GUI doesn't know there is a new file. 

You could tell the Picture widget to load the "new" image by setting the `.image` property each time in your counter function.

```python
def counter():
    ... create new file
    pic.image = "basis2a.png"
```

**Comment by dgn1** [comment]
Super!! Thanks: That's solved it for me!
