### ISSUE TITLE
resource leak

### ISSUE THREAD

**Issue by Richard0610** [lawsie/guizero#375]
**Describe the bug**
Window object will not auto release

**To Reproduce**
Steps to reproduce the behaviour:

----- with short code ------

import weakref
from guizero import App, Window

app = App()
win = Window(app, title='win')
b = weakref.ref(win)
app.display()
app = win = None
print(b())

**Expected behaviour**
just run and close app
b() must be none since the ui is close and win = None

**System information:**
 - OS: MAC
 - guizero version: 1.1.0

**Comment by martinohanlon** [comment]
Is this an issue with guizero or with tkinter? What happens if you use `win.destroy()`

**Comment by Richard0610** [comment]
import weakref
from guizero import App

app = App()
app.destroy()
app.display()
a = weakref.ref(app)
app = None
print(a())

it will not release a, either.



martinohanlon <notifications@github.com> 於 2020年7月9日 週四 上午4:17寫道：

**Comment by martinohanlon** [comment]
Garbage collection hasnt run by the time you print the weakref `a`.

If you force garbage collection to run, a is `None`.

```python
import weakref
from guizero import App
import gc

app = App()
app.destroy()
app.display()
a = weakref.ref(app)
app = None
gc.collect()
print(a())
```

Closing.

**Comment by Richard0610** [comment]
Thanks

gc.collect()
