### ISSUE TITLE
UI update lag

### ISSUE THREAD

**Issue by Richard0610** [lawsie/guizero#376]
**Describe the solution you'd like**
a command to wait/force ui change

--------------
severa days before
I raise an issue about destory window 
https://github.com/lawsie/guizero/issues/365

Author answer that we suggest hide, not to destroy it.
then I wrote a new program which hide window,reuse it.
but the 2nd time I show the window I need to change some data in it.
After I change it then show it
the old data were lag on the window

is there any function can change it soon?

Window.update() ?

**Comment by martinohanlon** [comment]
It is the window managers responsibility to update the window (normally this happens when you program releases) you can force and update with

App.update()
Window.update()
