### ISSUE TITLE
Install script accepts Pillow v5.4.1 but it doesn't work

### ISSUE THREAD

**Issue by Direl** [lawsie/guizero#378]
I installed guizero version 1.1.0 using sudo pip3 install guizero[images] but it couldn't resize images complaining that PIL was not available.  This appeared to be because it can't import ImageTk from that version of Pillow.

Upgrading Pillow to version 7.2.0 solves the problem.

While I accept that both my computers were seriously out of date I thought I would report it anyway just in case someone else hits this problem.

pi@Pi02:~ $ sudo pip3 install guizero[images]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting guizero[images]
  Downloading https://files.pythonhosted.org/packages/b0/eb/c58693afb94bc1e5f5f77d0f8e6b4e6dc84006fbfcb66b10fb81aef39f69/guizero-1.1.0-py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
Requirement already satisfied: pillow>=4.3.0; extra == "images" in /usr/lib/python3/dist-packages (from guizero[images]) (5.4.1)
Installing collected packages: guizero
Successfully installed guizero-1.1.0
pi@Pi02:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageTk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
>>> 

pi@Pi02:~ $ sudo pip3 install --upgrade Pillow
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Pillow
  Downloading https://www.piwheels.org/simple/pillow/Pillow-7.2.0-cp37-cp37m-linux_armv7l.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 329kB/s 
Installing collected packages: Pillow
  Found existing installation: Pillow 5.4.1
    Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Pillow'. No files were found to uninstall.
Successfully installed Pillow-7.2.0
pi@Pi02:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageTk
>>> 
pi@Pi02:~ $

**Comment by martinohanlon** [comment]
Interesting. ImageTk existed in pillow v5.4.1.

When you say your computers were out of date can you give me a little more information. It looks like you are running on a raspberry pi? Do you know which version of Debian? Stretch, Jessie, etc?

I remember back in the day experiencing some odd issues with weird builds of PIL on Linux.

**Comment by martinohanlon** [comment]
There is an issue here which relates to pillow versions and the use of 4.3.0 as the minimum requirement. 

https://github.com/lawsie/guizero/issues/251

@direl i will leave the issue open until the next release but I suspect it's a single issue.

**Comment by Direl** [comment]
I first noticed the problem on a Dell desktop running Ubuntu 20.04 (after
upgrades from 18 to 19 to 20) but I know that has some oddities in the PIP
and Python area so I did the investigations on what I thought was a "clean"
Raspberry Pi 4.  This was running Buster and had been updated recently but
had the same problem which is why I wondered if it was a more general
problem.

As I said it is not a real problem and I don't think you need to worry
about it although it looks as though I need to have a serious look at the
state of my computers.

Thanks

     Michael

**Comment by Direl** [comment]
I have just installed Raspberry Pi OS (Buster with Pillow 5.4.1) in a VM
and it works perfectly on that.

It must be something I have done/installed that is causing the problem.  On
that basis I am happy for you to close the issue.

Thanks for your time and the library which is very useful.

Regards

     Michael
