### ISSUE TITLE
PyCharm warning when setting "command=" parameter for PushButton widget

### ISSUE THREAD

**Issue by emailman** [lawsie/guizero#382]
**Describe the bug**
PyCharm gives this warning:
Expected type 'function', got '() -> None' instead

on this statement:
PushButton(app, text='push', command=push)

**Expected behaviour**
This statement is correct and should not result in a PyCharm warning.

**System information:**
 - OS: Windows 10
 - guizero version: 1.1.0
 - PyCharm 2020.2
 - Python 3.8

**Additional context**
Based on a post in the Raspberry Pi Python forum, the suggestion was made to change this line in PushButton.py from:
`
:param function command:
A string containing the image to display, defaults to `None`.
`
to:
`
:param Callable command:
A string containing the image to display, defaults to `None`.
`

This eliminated the PyCharm warning.  Also, note the description of this parameter is incorrect.

Similarly, you get a warning on the "width" and "height" parameters when either is set to "'fill'".  PyCharm says an "int" was expected.

**Comment by martinohanlon** [comment]
Thanks for reporting the issue. The change is in branch v1-1-1.

I replaced a few other instances as well.
