### ISSUE TITLE
Re-Render for text change? 

### ISSUE THREAD

**Issue by SirVectrex** [lawsie/guizero#383]
**Is your feature request related to a problem? Please describe.**
I am currently building a GUI with GUIzero for my raspberry pi trying to build a function, that on call, will start a countdown and take a photo with a display of the . However my idea won`t work due to the text only being changed with "app.display()". Does anyone have any ideas or tipps?

```
def myfunction():
    mytext.value = "3"
    sleep(1)
    mytext.value = "2"
    sleep(1)
    mytext.value = "1"

#Main App
app = app(Title="my app")
mytext = Text(app, "Taking a photo aye?"
app.display()
```

Can I somehow make the code above work with the text being changed as wanted with the small delay before changing the text?

**Describe the solution you'd like**
The possibility to re-render a single component.

**Describe alternatives you've considered**
I am out of ideas. Maybe anyone else has an idea?

**Comment by martinohanlon** [comment]
There is advice regarding 'loops and sleeping' in the documentation https://lawsie.github.io/guizero/blocking/

Have a look at App.repeat or App.after

**Comment by SirVectrex** [comment]
I have already used that to trigger my event and functions. However it doesn`t resolve the issue of only being able to make changes to the GUI with every iteration of the app.display() function? 

If I would want to trigger a function to start a countdown I would always have to use conditional clauses?

**Comment by martinohanlon** [comment]
You can force an update to the GUI using App.update() 

https://lawsie.github.io/guizero/app/

I would advise against using sleep() in a GUI (or any event based application) and restructure your program to use app.after or app.repeat.
