### ISSUE TITLE
Python installation with MacPorts and guizero via pip have no success

### ISSUE THREAD

**Issue by maitrenageur** [lawsie/guizero#385]
I try to start with guizero together with the documentation and examples.
In short:
~~~
from guizero import App
app = App(title="Hello world")
app.display()
~~~

But i get the error:

_Traceback (most recent call last):
  File "gui_guizero_1.py", line 1, in <module>
    from guizero import App
ModuleNotFoundError: No module named 'guizero'_

## To Reproduce on macOS 10.15.7
1. Python 3.9 installation with MacPorts.
2. pip3 installation with MacPorts.
3. guizero installation with pip.
4. No errors.

## Expected behaviour
The simple example shows a GUI window and title "Hello world". 

## System information
 - macOS 10.15.7
 - guizero version: Version: 1.1.0
 - Location: /users/<username>/Library/Python/3.9/lib/python/site-packages

## Additional Information
MacPorts install everthing in /opt/local/ . The $PATH varable is expanded for MacPorts, to find installed BSD tools at first, instead to use the pre-installed tools by Apple. Standard python programs are still running.

From my point of view is a standard environment missing, that Python can consider installed modules with pip at the special location.

**Comment by martinohanlon** [comment]
I have no knowledge of macports or its use, so you will have to us with this. A have had a quick read but this is the extent of my knowledge.

I'm not sure why this is an issue with guizero? 

The error suggests that python cannot find the guizero library wherever macports has installed it.

Is there anything we can do to / have to do to make the install work with macports.

This post(https://apple.stackexchange.com/questions/282839/using-pip-vs-macports-for-installing-python-packages) suggests:

The Gotcha
If you do use pip with Macports, you need to make sure that it's the pip that is installed through Macports and associated with that python version. So, for example, you will see a py35-pip, py36-pip, etc.

Is you provide more advice re the issue or a potential resolution for guizero then I would be happy to look at it.

**Comment by maitrenageur** [comment]
You have right, there is no issue in context with MacPorts. My Hope was, that anybody could help me with guizero and a Python installation steered with the package manager MacPorts for macOS.

Python is still running and i considered all remarks, but i have only a problem with guizero.

If i find a solution i will report it here.

**Comment by kcarnold** [comment]
This seems like an instance of a common issue of getting packages installed in the correct Python environment, rather than something specific to `guizero`. To debug, you should check which `python` is being used (type `which python` at the terminal, assuming you're starting Python from there instead of an IDE), which `pip` (or `pip3`) is being used (same), and, once you start Python, what `sys.path` is (e.g., run `python -c 'import sys; print(sys.path)'`). This should help you find the installation error. 

If you want a simpler solution, install Thonny and use Tools -> Manage Packages to search for and then install `guizero`.

**Comment by martinohanlon** [comment]
Closing. If anyone has any advice for @maitrenageur please post it here.
