### ISSUE TITLE
Clicking to the right of the last element in a Waffle causes invalid index to be passed to associated command

### ISSUE THREAD

**Issue by aajshaw** [lawsie/guizero#388]
**Describe the bug**
Two problems that are related:

1. When the area to the right of the last waffle element in a row or the area under the last waffle element in a column is clicked the values passed to the associated command function are invalid. 

2. The canvas that the waffle is built on to is too big by one padding size on the right and bottom as well

A program that demonstrates the issues is

```python
from guizero import App, Waffle

def clicked(x, y):
    print(x, y)

app = App("Waffle test")

waffle = Waffle(app, width = 5, height = 5, pad = 20, command = clicked, bg = "yellow")

app.display()
```
![waffle](https://user-images.githubusercontent.com/11177450/97484127-432c8000-1950-11eb-8118-697fe2548be3.jpg)

As can be seen above the yellow waffle background is too big on the right and underneath.

Clicking on the yellow areas on the right and bottom generates invalid x and y values in the command function.

I will be able to generate a PR soon to fix these problems or can supply source code locations where the fixes can be applied.

**Comment by martinohanlon** [comment]
Thanks. If you are able to raise a PR, would be happy to review and pull in the next release.

There are notes relating to contributing code at https://lawsie.github.io/guizero/contributing/ and for developing changes at https://lawsie.github.io/guizero/development/

**Comment by martinohanlon** [comment]
Thanks a lot for the PR. Merged into branch v1-1-1 for release :)
