### ISSUE TITLE
TextBox widget description text doesn't update when text is entered

### ISSUE THREAD

**Issue by scotty3785** [lawsie/guizero#392]
**Describe the bug**
If a user creates a text box and prints the instance of the text box the __repr__ method shows the self.description text. For example.

    [TextBox] object with text ""

If the user then enters some text in the widget, the expectation seems to be that the repr of the widget will update to show the current value.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter the following code to a python file

```
from guizero import App, Text, PushButton, TextBox

app = App("Testing")
          
def test():
    global testing
    print(testing)
    print(testing.value)

button = PushButton(app,test, text = "press to test")

title = Text(app, "Testing input here")
testing = TextBox(app, text= "" )
app.display()
```

2. Run the code and enter some random text in to the TextBox widget.
3. Press the "press to test" button
4. Look in the console and notice that the output is 
`[TextBox] object with text ""`

**Expected behaviour**
TextBox desciption/repr should update the show the current contents of the TextBox rather than just the initial description created when the TextBox instance is created

**Screenshots**
N/A

**System information:**
- Platform independent

**Additional context**
See lines 

https://github.com/lawsie/guizero/blob/965cc55f9342300c2d248fe8e1cceb74002dd1b0/guizero/base.py#L149

https://github.com/lawsie/guizero/blob/master/guizero/TextBox.py#L23
for the relevant code

**Comment by martinohanlon** [comment]
Some brief investigation suggests most widgets have the same issue.

Maybe `.description` could be dynamically built from the class name and its potential value (if its has one)?

**Comment by martinohanlon** [comment]
>most widgets have the same issue.
this isnt the case.

Most widgets update the description as the value (or whatever else makes up the description) changes. 

TextBox is unusual in that what changes the '.value' is when users "type" into the TextBox. This would have to be captured as an event and the .description property updated everytime a key is pressed (or more accurately when the key is released).

I am tempted to refactor this and make `.description` a read-only property of `Component` which returns the `class name` which can then be overriden by a widget if a more sophisticated description is required.

^ it seems a lot of work though for such a minor bug. 

If I was going to progress this I would also replace the use of `__repr__` with `__str__` as `__repr__` should be the object definition and `__str__` should be the user definition.

**Comment by martinohanlon** [comment]
Refactored description throughout guizero in branch https://github.com/lawsie/guizero/tree/v1-1-1

**Comment by scotty3785** [comment]
Brilliant! You are a super star.
The issue was noticed on a stackoverflow question https://stackoverflow.com/questions/64891407/python-guizero-textbox-textbox/64892264#64892264

Agree it would make sense to change it to __str__. 

Very minor bug but must have been an unexpected behaviour for an inexperienced user.
