### ISSUE TITLE
Add 'border' or 'borderwidth' property to Pushbutton

### ISSUE THREAD

**Issue by sevilnatas** [lawsie/guizero#399]
In using the Pushbutton, I tend to use the 'image' property more often than 'text' in order to create good looking UIs. Problem is that the Pushbutton doesn't seem to have a 'border' or 'borderwidth' property that would allow for removing the border and making image buttons look really good.

**Comment by aajshaw** [comment]
You can access the underlaying TK object and set its options, in this case the borderwidth (or bd) property

```python
from guizero import App, PushButton

app = App("A picture button")

picture_button = PushButton(app, image="guizero.gif")
picture_button.tk.config(borderwidth = 0)

app.display()
```

It would be nice to have the border width and border style directly accessible from the guizero object

**Comment by martinohanlon** [comment]
Thanks Anthony. I was going to suggest the same.

**Comment by martinohanlon** [comment]
I am going to close this issue. It feels like a specific requirement which can be met by using tk.
