### ISSUE TITLE
Store docs content in markdown not html

### ISSUE THREAD

**Issue by bennuttall** [lawsie/guizero#4]
I was just about to send a couple of PRs with docs fixes but found you don't store the markdown source on github!

If you keep the markdown in the docs folder, and set it to build html into another folder (or use a different branch for github pages) - would help people trying to contribute :)

**Comment by lawsie** [comment]
Added a docs-src folder with the .md files. You can only set up github pages in a docs folder and I want to keep docs for the current release separate to docs with extra bits that haven't been put into the release yet.
