### ISSUE TITLE
Problem with the OS version

### ISSUE THREAD

**Issue by RomoloPoliti** [lawsie/guizero#400]
**Describe the bug**
Importing the guizero lib I obtain the following error:

macOS 11 or later required !

My os version is 11.1 (tested using platform.mac_ver())

**System information:**
 - OS: MacOs 11.1
 - guizero version: 1.1.1

**Comment by martinohanlon** [comment]
This looks to be an issue with how brew installs Python.

There are details here, advice is to install using the official Python installer.

https://stackoverflow.com/questions/65315077/interpreter-crashes-trying-to-use-tkinter-library

Not a bug with guizero so closing.
