### ISSUE TITLE
Request: Windows System Tray / MacOS Menu Bar / Linux appindicator

### ISSUE THREAD

**Issue by ethanpil** [lawsie/guizero#401]
I'd like an easy way to be able to create a Windows System Tray or MacOS Menu Bar icon and menu. I'm sure there is a linux equivalent as well.

Perhaps a simple recipe to integrating with https://github.com/moses-palmer/pystray where I can capture window close/minimize and force to systray instead of quit, etc...

**Comment by yonghuming** [comment]
tk/tcl has tray extension: https://wiki.tcl-lang.org/page/system+tray.
guizero  hopes Works with standard Python Tkinter GUI library (and no need to install other libraries), so pystray maybe not a good choice. need to find better solution.
Of course it's easy to implent your request feature use pystray

**Comment by yonghuming** [comment]
guizero is an excellent education tools. we should make balance between features and accessiblity

**Comment by martinohanlon** [comment]
Thanks for the suggestion. I think there are other alternatives for creating applications which minimise to the system tray and I am not sure there is the benefit to adding it directly into guizero. 

Closing.
