### ISSUE TITLE
App.select_file

### ISSUE THREAD

**Issue by BruceMardle** [lawsie/guizero#402]
According to the documentation, App.select_file returns None if 'cancel' is pressed. I'm finding that it returns () instead.
`PS: It's not obvious how to put multiple patterns in the filetypes argument. "*.gif;*.png" doesn't work. "*.gif,*.png" doesn't work, but "*.gif *.png" works... and is displayed as *.gif,*.png!`

**Comment by aajshaw** [comment]
Multiple file types are specified as lists in lists, so to have multiple types of images or multiple ty7pes of documents you would use something like the following

```python
app.select_file(filetypes = [['imges', ['*.png', '*.bmp']],['docs', ['*.doc', '*.docx']]])
```

**Comment by BruceMardle** [comment]
Maybe, but using 1 string with a space as a separator works too!

**Comment by bsimmo** [comment]
following https://lawsie.github.io/guizero/alerts/

is it possible to have the filename filled in, if I've opened it I already have a file name.
i.e. pass file_name.value into it

**Comment by martinohanlon** [comment]
> is it possible to have the filename filled in, if I've opened it I already have a file name.

Currently no. I have added a `filename` parameter to the `select_file` method. The change is in dev
