### ISSUE TITLE
guizero installed with pip3 but crashes after "hello world" example

### ISSUE THREAD

**Issue by BelizSertcan** [lawsie/guizero#403]
I have MacOS Big Sur version 11.1. I installed guizero with `pip3 install guizero`, no problem so far. Then I ran the following code

    from guizero import App
  
    app = App(title="Hello world")
    app.display()

which resulted in the error

> macOS 11 or later required !
> Abort trap: 6

I have macos 11.1, I don't see why it crashes.

[crash_report.txt](https://github.com/lawsie/guizero/files/5912268/crash_report.txt)

**Comment by bsimmo** [comment]
While you wait for someone who may be able to read that

Does
```
#!/usr/bin/python3
import tkinter 
top = tkinter.Tk()
top.mainloop()
```

work ?

**Comment by BelizSertcan** [comment]
> While you wait for someone who may be able to read that
> 
> Does
> 
> ```
> #!/usr/bin/python3
> import tkinter 
> top = tkinter.Tk()
> top.mainloop()
> ```
> 
> work ?

no I get the same error... do you know why it could be?

**Comment by bsimmo** [comment]
Also, update your Python3 to 3.9.1, you're on 3.9.0
First part of it's Release says
_3.9.1 is the first version of Python to support macOS 11 Big Sur._

**Comment by BelizSertcan** [comment]
Yes actually updating to python 3.9.1 solved the problem, I see the hello world window. Thanks!

> Also, update your Python3 to 3.9.1, you're on 3.9.0
> First part of it's Release says
> _3.9.1 is the first version of Python to support macOS 11 Big Sur._

**Comment by martinohanlon** [comment]
Thanks @bsimmo :)

Closing issue as resolved.
