### ISSUE TITLE
How do we catch a GUIZeroException

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#404]
e.g.

if the file is missing, use try/except
If the image is missing then
```
    raise GUIZeroException(error_message)
guizero.utilities.GUIZeroException: 
------------------------------------------------------------
*** GUIZERO ERROR ***
Image import error - '[Errno 2] No such file or directory: 'B-Answer_to_Life.png''
Check the file path and image type is GIF/Animated GIF/BMP/ICO/PNG/JPG/TIF
------------------------------------------------------------
```
as expected,.

```
try:
    picture = Picture(app, image="a-picture.png")
except GUIZeroException:
    do_some_thing_else()
```

Fails (Not Defined)
guizero.utilities.GUIZeroException (fails)
or a simple
FileNotFound (seems to hang?)
2
"Error 2"
etc..

So how to we handle it ?
thanks :-)

**Comment by martinohanlon** [comment]
I haven't tried but you should be able to import the exception e.g.

```
from guizero.utilities import GUIZeroException
```

**Comment by bsimmo** [comment]
This worked, thankyou
I've passed it along to the person having the problem.
We're doing your Futurlearn course.

**Comment by martinohanlon** [comment]
Ok.

I'm sure Mac who is facilitating the course will be a big help.
