### ISSUE TITLE
Raspberry Pi OS (arm) apt version needs updating (v0.6.0

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#405]
I'm just working on an up to date PiOS on the Pi, and it has guizero v0.6.0 and that's two years old now.

So I have to override it with a pip3 install.

Any chance you could push an update out so they can benefit too (I'm guessing it's installed by default still.  Any attempt to remove it will remove mu also.) 

I don't know what your release principles are for the apt versions, or is that down to RPT/RPF ?

**Comment by martinohanlon** [comment]
We don't control the apt repositories. I think this version in particular is installed as a pre-requisite of the Mu editor.

Your approach to upgrade using pip is the correct one and generally a good idea for most Python libraries.
