### ISSUE TITLE
Add a note that colour should be None for default colour

### ISSUE THREAD

**Issue by bsimmo** [lawsie/guizero#409]
**Is your feature request related to a problem? Please describe.**
I was just trying to remember how to set the bg, text_color etc back to default.
The documents do not mention it. 
e.g.
app.bg = None

**Describe the solution you'd like**
I would like the notes on [Colors (or Colours)](https://lawsie.github.io/guizero/colors/) to list _None_ as an option and return it to default.  (default being the containers setting? app, window, box ? if I have that right)

I would like
>   File "utilities.py", line 436, in convert_color
>     raise ValueError("A color must be a list or tuple of 3 values (red, green, blue)")
to also include _None_

I would like [Recipes : Change your apps appearance](https://lawsie.github.io/guizero/recipes/) to have None shown as an option. 

**Describe alternatives you've considered**
Don't do recipe, since None will be text in the simple example (see additional)

**Additional context**
Recipe problem: I think this may add a layer of problem solving though, if you apply None as a string (for example appending to the Recipes example list), it fails with unknown colour name.  I know I have to program for this option separately.
Addition : Could "None" be interpreted as None before being sent. Looking at the error I'm guessing in tkmixins before being sent to utils.convert_color(color) in base.py 

Anyone else had this problem of not being able to find

**Comment by yonghuming** [comment]
Additional context
**Recipe problem**: I think this may add a layer of problem solving though, if you apply None as a string (for example appending to the Recipes example list), it fails with unknown colour name. I know I have to program for this option separately.
Addition : Could "None" be interpreted as None before being sent. Looking at the error I'm guessing in tkmixins before being sent to utils.convert_color(color) in base.py

**Comment by martinohanlon** [comment]
I have added a sentence to the documentation in `colors.md` stating that a color property can be reset to the default by setting it to `None`.

I havent added it to the recipe. Recipes are discrete and simple examples.

> Could "None" be interpreted as None before being sent.
I dont think adding this is a good idea, interpreting strings as types can often lead to problem and I dont believe is best practice. If desirable to a specific user this could be handled by the program using guizero.

Ready, In `dev`, for release 1.3.0
