### ISSUE TITLE
Port GuiZero over to use Brython instead of Tkinter

### ISSUE THREAD

**Issue by VictorNorman** [lawsie/guizero#417]
In our introductory CS course, we have transitioned from python + Tkinter to python + GuiZero, and we are very happy with it! Thanks for your work.

What we'd like to do is get rid of Tkinter altogether and move to GuiZero with [Brython](https://brython.info/) as the backend.  I have personally ported over some of our students' old Tkinter-based projects to Brython, so I know it can be done. (And, you can see an example of a projected I moved to brython [here](https://github.com/VictorNorman/frustration_solitaire), and running [here](https://cs.calvin.edu/courses/cs/108/vnorman/brython/cardgame/index.html).)

I am wondering what you think of this idea.

I am willing to work on this port over my summer. I wonder if you have any recommendations for how to start. Is there some part of your code I should get working first? 

Thanks for listening!

Vic Norman (Calvin University)

**Comment by martinohanlon** [comment]
Hi,

Thanks very much for your comments, I am really very pleased you have chosen to use guizero for your course :).

guizero and tkinter are inextricably linked. guizero is in many perspectives a wrapper to tkinter. tkinter has informed its design and approach. guizero doesnt really exist without tkinter, it is not architected in that way.

It is probably possible to create a "guizero like" API for something like brython but I think that is a different project. It is not a project have the time or inclination to progress, but would be willing to assess a prototype and provide some feedback if one was created.

I am going to close this issue as it isnt an issue we will progress.

Martin
