### ISSUE TITLE
can I get cursor position in textbox? 

### ISSUE THREAD

**Issue by Richard0610** [lawsie/guizero#419]
**Is your feature request related to a problem? Please describe.**

Hello, I am writing my virtual keyboard function.

~~~python
class BaseTextBox(TextBox):
    def virtualKeyPressed(self, key):
        self.value += str(key)
        length = len(self.value)
        tk: Entry = inputTextBox.tk
        tk.icursor(length)
~~~

and I just can place my cursor to the end of string. 
tk.icursor(position)   can put cursor to position.

but I would like to know if I can get the position? for ex:
position = tk.index()

the code would not work.

it seems tk's issue.
does it can't get position value?
or it cause by that I don't read the document cleaarly?

what is the correct sample code to get the position?

Thank you. ( and sorry for my poor english)

Richard 2021/04/29

**Comment by martinohanlon** [comment]
edited issue to include code tags

**Comment by martinohanlon** [comment]
This example works for me using tk to get the cursor position in a `TextBox`.

```python
from guizero import App, TextBox, Text
from tkinter import INSERT

def key_pressed(key):
    print("key pressed {}".format(key))
    print("textbox value = {}".format(textbox.value))
    print("cursor pos = {}".format(textbox.tk.index(INSERT)))

app = App()
text = Text(app, text="Enter some text")
textbox = TextBox(app, width=40, command=key_pressed)
app.display()
```

It would be relatively trivial (if a nice to have) to add a `cursor_position` property to the `TextBox` widget.

**Comment by Richard0610** [comment]
Thank you.

after I compare with your code,I got and understand the correct document
:)

https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/text-index.html



martinohanlon ***@***.***> 於 2021年4月29日 週四 下午10:35寫道：

**Comment by martinohanlon** [comment]
Added `cursor_position` to `TextBox` - the change is in `dev`. Ready for release 1.3.0
