### ISSUE TITLE
Lost Link for emojis Chapter

### ISSUE THREAD

**Issue by ekoray** [lawsie/guizero#424]
the link "magpi.cc/guizeroemojis" is missing so where can I find the emojis file to be used with the Chapter 9 of the book?

Thank you!

**Comment by lawsie** [comment]
Hi @ekoray - I just used that link and it worked OK, what happens when you try to load it? No page will load, just a direct download of a zip file so it might be that you have some kind of download blocker.

**Comment by bsimmo** [comment]
that link translates to https://github.com/lawsie/guizero-book/raw/master/08-Emojimatch/emojis.zip
It's a 404 for me.
I'm guessing it's a private link, hence lawsie can see it be we cannot.  Since there is no _guizero-book_ repository listed for @lawsie for me.

**Comment by bsimmo** [comment]
Just to help, I'm assuming it's the same emoji pack I used in futurelearn - teachcomputing.org
Use this link https://rpf.io/fl-guis-emojis

**Comment by ekoray** [comment]
> Just to help, I'm assuming it's the same emoji pack I used in futurelearn - teachcomputing.org
> Use this link https://rpf.io/fl-guis-emojis

Thank you, I used this download link. Otherwise it's a 404 for me also.

**Comment by lawsie** [comment]
Haha, oh dear, whoops! Yes, that is a private repo, I didn't realise they had done that. It should be the same emoji pack so please use the link above and I'll get the shortlink amended so that it goes somewhere not private :)

**Comment by martinohanlon** [comment]
It looks like the magpi.cc link has been fixed now.
