### ISSUE TITLE
Tkinter ListBox

### ISSUE THREAD

**Issue by Harlekuin** [lawsie/guizero#43]
Are there plans to add the Tkinter ListBox?

**Comment by lawsie** [comment]
Not really thought about it, but no reason why not!

**Comment by martinohanlon** [comment]
I am going to add `ListBox` into the next release.

This is what Im thinking:

- `ListBox` will inherit from `TextWidget`
- The interface will be very similar to `Combo` having a list of `options` a `selected` and the ability to add an option and clear
- tkinter doesnt provide a `command` for a Listbox so I will add an event to detect mouse clicks and use that to generate a command when the ListBox changes
- scrollbars will be needed, Ill make this a option on the constructor, like a multiline TextBox

Any thoughts, greatly received.

**Comment by Harlekuin** [comment]
Things to think about would be how the command parameter would deal with multi selection. Would it pass as argument one of the command function the selected items from the ListBox in a list?

To be honest I don't think you would need a command argument for the first crack at a ListBox. If the ListBox had a selected() function that returns a list of selected items, then you could use a PushButton with the ListBox as one of the <args> list parameter, and inside that command function linked to the button use ListBox.selected().

**Comment by martinohanlon** [comment]
@Harlekuin thanks for the input.

Im not sure about the command yet either... but I think its important that there is an event that fires when the selection of a ListBox changes, it doesnt necessarily have to return anything though.

Re a `selected()` function. I will implement a `value` property (to be consistent with other guizero widgets) which either returns single value if the ListBox is a "single select" listbox  or a tuple of values if the ListBox is "multi select" .

`multiselect` will be a parameter passed in at construction, defaulted to `False`.

e.g.

to create a single select list box:

```python
lb = ListBox(app)
```

or a multiselect listbox:

```python
lb = ListBox(app, multiselect=True)
```

**Comment by martinohanlon** [comment]
Ok, so update..

In regards to ListBox API.

Ignoring all the stuff which ListBox will inherit from TextWidget (`bg`, `text_color`, `font`, `after`, etc, etc) it will have the following properties and methods.

+ `__init__(self, master, items=None, selected=None, command=None, args = [], grid=None, align=None, visible=True, enabled=None, multiselect=False)`
  + master - container the widget is 'owned' by
  + items - a list of string for items to add into the ListBox
  + selected - item or items to select at init
  + command - a function which will get called when the ListBox selection changes
  + args - a list of arguments to pass to the command
  + grid - grid position
  + align - alignment in grid
  + visible - if visible at init
  + enabled = if enabled at init
  + multiselect - if the ListBox should allow multiple items to be selected
+ `value` - Sets or returns the items selected in a ListBox `None` if 0 items are selected. If the ListBox is a `multiselect`, `value` is a tuple of items selected, if not `value` is a single integer.
+ `insert(index, item)` - Insert a new `item` at `index`.
+ `append(item)` - Appends a new `item` to the end of the ListBox.
+ `remove(item)` - Removes an `item` from the ListBox.
+ `clear()` - Clears all the items from a ListBox
+ `items` - Returns a list of items in the ListBox

**Comment by martinohanlon** [comment]
My thoughts for including are command is to support knowing when the value within a ListBox has changed, not to return what the value is / was. I think this is the right approach as with a listbox its possible the change to the value could be that something has been deselected so there is no value. 
 Command will be optional so its a feature rather than a requirement.

My choice for multiselect = False is that it is consistent with tkinter and in-line with multiline in TextBox.

The `append`, `insert`, `remove` methods will be consistent with a Python list, so yes `remove` will remove the first instance of an item found.

**Comment by martinohanlon** [comment]
I am thinking perhaps `command` should return an optional parameter if the callback accepts it, similar to combo, buttongroup, etc. As @Harlekuin said it could just return the value of `value`.

**Comment by martinohanlon** [comment]
in 0.5.1 just released
