### ISSUE TITLE
Unsatisfactory appearance of ButtonGroup widget when used with non-default app background colour

### ISSUE THREAD

**Issue by markchik** [lawsie/guizero#433]
Changing the background colour of an app causes ugly boxes to appear around the text labels in any ButtonGroup widgets.
it is possible to minimize the ragged appearance of these by using a fixed-width font and padding the labels with extra spaces
but it would be better if they could be hidden completely.

The same thing happens with a simple PushButton widget but it is possible to alter the appearance of these with setting some extra
properties using tk.config, e.g.

app = App("Some app", bg="grey")
button_0 = PushButton(app, text="Press")
button_0.tk.config(highlightbackground="grey")
button_0.tk.config(borderwidth = 0)

I've tried similar with the ButtonGroup but have not been successful.

(I'm new to guizero/github etc. so I hope I'm following the correct procedure)

**Comment by martinohanlon** [comment]
It would be useful to have a screenshot to demonstrate what you mean.

Could you also include information about your operating system pls. 

Thanks

**Comment by markchik** [comment]
Here is a simple example to reproduce what I described. I've been working mostly on Fedora 35 but the same thing happens on Raspberry Pi OS. The stuff commented out shows what I have tried in an attempt to hide the boxes. The last two lines produce
error messages but they do work with a PushButton.

```
from guizero import App, ButtonGroup

app = App("Test", bg="grey", height=100, width=200)

choice = ButtonGroup(app, options=["cheese", "ham", "green salad"], selected="cheese")

#choice.bg = "grey"
#choice.tk.config(borderwidth = 0)
#choice.tk.config(highlightbackground="grey")
#choice.tk.config(activeforeground="yellow")
#choice.tk.config(activebackground="red")

app.display()
```


![test](https://user-images.githubusercontent.com/99260400/153045042-bd833085-fac8-4569-8a5c-728d463a0023.png)

**Comment by markchik** [comment]
Ok - I found something in the documentation which allows me to do what I want:-

```
from guizero import App, ButtonGroup

app = App("Test", bg="grey", height=100, width=200)

choice = ButtonGroup(app, options=["cheese", "ham", "green salad"], selected="cheese")

# This works!
for button in choice.children:
    button.tk.config(highlightbackground="grey")
    
app.display()
```


But I think there's an error in your web page for the Buttongroup widget. There's an example at the bottom:-

```
button_group = ButtonGroup(app)

for radio_button in ButtonGroup.children:
    tk_radio_button = radio_button.tk
```

Surely "ButtonGroup.children" should be "button_group.children"?
I guess this can be closed now. Thanks for guizero - it's very useful for me.
