### ISSUE TITLE
Background images for App objects

### ISSUE THREAD

**Issue by Usernames-Are-Not-Available** [lawsie/guizero#434]
Hiya all.
I've been working on a project that requires a background image for the app that I am using. The project relies partly on aesthetics, and a background image is needed (or at least encouraged).
I tried to make a background image by putting a picture in the main App() master object, but when I add something else, it doesn't go to background.

I would preferably want a feature added to the Picture object for when it is called, like `Picture(main, background=[boolean], ...)`, so that it can be moved behind whatever widgets are in use.

Another alternative is using the Drawing object and drawing parts of an image around widgets, but I don't see how feasible that would be.

Any feedback (or help) would be appreciated!

Thank you.

**Comment by lawsie** [comment]
Hi @Usernames-Are-Not-Available . I've had a quick peek and you can do this with the addition of some raw tkinter to make a background image BUT the text etc. widgets on top of it will still have a background colour.

`from guizero import App, Text, Box
from tkinter import Label, PhotoImage

app = App("I have a background image")

# Some raw tkinter to create the bg image
img = PhotoImage(file="bgimage.png")
label = Label(app.tk,image=img)
label.place(x=0, y=0)

# Text on top, but it will have a background
some_text = Text(app, "This is some text")

app.display()`

I think there is possibly another way to do this using a tkinter canvas too.
