### ISSUE TITLE
Add support for arrow keys in event_data.key

### ISSUE THREAD

**Issue by softstones** [lawsie/guizero#436]
**Is your feature request related to a problem? Please describe.**
Often I would like to use arrow keys, or the Page Up/Down keys to control my application, but that seems to be not possible with the `event_data.key` parameter.

**Describe the solution you'd like**
`event_data.key` returning something that can be used in an if statement, for example the capital letters A, B, C and D for the arrow keys, or just the key code.

**Describe alternatives you've considered**
There are no alternatives, because I would like to use specific keys of the keyboard. When unsupported keys are pressed, `print(event_data.key)` seems to return nothing, so there are no workarounds to my knowledge.

**Additional context**
-

**Comment by martinohanlon** [comment]
The key event data is returned directly from tkinter. If it isn't returned there is probably little which can be done to resolve this directly in guizero.

I am surprised that key codes aren't returned for page up, page down, etc though. What OS and version of tkinter are you using?
