### ISSUE TITLE
focus() does not appear to work for combo

### ISSUE THREAD

**Issue by putinsSockPuppet** [lawsie/guizero#438]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a bug or not.  I cannot get the combo widget focus method to actually do anything.  I was  expecting that setting the focus would select the combo so that a key press would open it and then the arrow keys could be used to select a choice.  This behavior does work with the slider but not with the combo

**Describe the solution you'd like**
I have a small data entry form that I would l like to use only the keyboard on.  Ideally, I would like to set a tab order and tab through the controls.  Several of the Combos are filled from database queries (to minimize errors when entering data) and it is possible to be much faster if you do not have to switch back and forth between the mouse and the keyboard.  This could be coded (although cumbersome) if I could get the combo focus to work.

**Describe alternatives you've considered**
To be fair I have a good deal of experience with line of business applications (Windows) and I realize this is not the best tool for that.  I can easily create this type of application using .net but I would rather not.  I use Linux at home and only run Windows in virtual machines any more.

**Additional context**
My development machine runs Ubuntu 20.04.3 and the latest guizero.

**Comment by martinohanlon** [comment]
I don't have any insight into why Combo.focus() doesn't appear to be
working for you. The method is really simple and just calls the equivalent
tkinter method.
https://github.com/lawsie/guizero/blob/master/guizero/tkmixins.py#L73

^ I did read that you have to press the space bar when a combo gets the
focus to open the menu before you can select the item?

However... have you tried using tkinter to set the tab order?

I found this tutorial which uses the tkinter lift method.
https://www.tutorialspoint.com/how-to-set-the-tab-order-in-a-tkinter-application#:~:text=The%20Tab%20order%20in%20any,and%20use%20lift()%20method
.

There are some guidelines to accessing tkinter from within guizero in the
docs https://lawsie.github.io/guizero/usingtk/

**Comment by putinsSockPuppet** [comment]
Thanks for the prompt response.  I did verify that setting the focus and then using the space bar does open the menu.  I suspect what was throwing me was that the first control I set focus to was a slider and doing that creates a box around the control that indicates it has the focus.  The combo does not do that (or at least it is not doing that for me).

I do not have any experience with tkinter so I will be exploring your link.  Thanks

**Comment by martinohanlon** [comment]
Can this issue be closed? The issue raised "focus doesnt appear for Combo" appears to have been resolved.

**Comment by martinohanlon** [comment]
I have added a new issue to discuss adding a taborder.

**Comment by martinohanlon** [comment]
Closing this issue.
