### ISSUE TITLE
Bug report - Documentation Fix

### ISSUE THREAD

**Issue by miyucode** [lawsie/guizero#440]
On the documentation, in **_"Using Guizero" > "Adding Widgets"_**, we can see a part of code like this:

![bug](https://user-images.githubusercontent.com/75862582/159114098-656bb0df-1119-40b8-89f1-2d15710846c5.png)

But **there is a error in it** at the end, there is two parentheses but we need only one, could you fix it ?

Regards,
Miyu.

**Comment by martinohanlon** [comment]
I am going to reopen the issue. They are left open until the change moves into a release. 

See PR #445

**Comment by miyucode** [comment]
Ok ! :P

Regards,
Miyu.

**Comment by martinohanlon** [comment]
Resolved with #446
