### ISSUE TITLE
Bug report in documentation - Widgets - Window - Creating a Window object

### ISSUE THREAD

**Issue by chema-hg** [lawsie/guizero#442]
**Describe the bug**
There is an error running the example:

 window = Window(title = "2nd Window", height=300, width=200)
TypeError: __init__() missing 1 required positional argument: 'master'

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to this page "https://lawsie.github.io/guizero/window/"
2. In the example of Creating a Window Object is missing a positional argument (master)
3. If you run the example you will get that error.

**Screenshots**
![image](https://user-images.githubusercontent.com/64953146/159133704-e2adc58e-a5c1-474e-97d3-ff9cbe715155.png)

**Comment by martinohanlon** [comment]
Resolved wih  #446
