### ISSUE TITLE
Request to have SVG image support.

### ISSUE THREAD

**Issue by ghost** [lawsie/guizero#444]
**Is your feature request related to a problem? Please describe.**
This feature request is not really related to a problem, but I was frustrated when I realised that I could not render svgs inside of guizero.

**Describe the solution you'd like**
I'd like to be able to render and display svgs inside of guizero for my project. It should be accessible through the Picture widget.

**Describe alternatives you've considered**
For now, I'll have to use non-scalable image types instead.

**Additional context**
I have the image support extenstion installed.

**Comment by martinohanlon** [comment]
Thanks for the feature request. I cant see this being progressed. guizero uses PIL (pillow) to convert bitmap images types into images tkinter can accept. PIL doesn't support vector graphics files (e.g. SVG).

I would suggest you consider looking for a python library that can render SVG to a bitmap file type (jpg, gif, BMP, etc) and use that before loading into guizero.

**Comment by martinohanlon** [comment]
I am going to close this issue. My original comment remains and I cant see it changing.
