### ISSUE TITLE
GUI ZERO centre text to the middle of the screen

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#45]
Gui zero is a great program just having trouble trying to center the text to the middle of the screen.
 Is there  another function that centers text to the middle of the screen.

Any help would be greatly appreciated.

Thanks

from guizero import App, Text, TextBox

def update_writing():
    
    A = ('World')
    writing.set(A)
    app.after(200, update_writing)

app = App(height=2000, width=2000,bgcolor="black")

writing = Text(app, text="", color="red",size=110,grid=[4,0], align="center")

app.after(200, update_writing)

app.display()

**Comment by lawsie** [comment]
The align property is for a grid layout and specifies where the item appears in the grid cell. If that's the whole app, you can just avoid using grid layout and use the auto pack instead and all of your components will be centered. 

```
from guizero import App, Text

def update_writing():
    writing.set("World")
    app.after(200, update_writing)

app = App(height=2000, width=2000, bgcolor="black")

writing = Text(app, text="", color="red", size=110)

app.after(200, update_writing)

app.display()
```

**Comment by James100000** [comment]
Thanks for the quick reply, I am having trouble using the auto="pack" function.

The program centers the text at top of the screen without any problems, it will not center the text in the middle of the screen.

Would I place the auto pack feature in the "app" or the "writing"


Thank you.

**Comment by lawsie** [comment]
Oh I see, I didn't realise you wanted it to be centered both ways. To do that you'll have to use some tkinter functionality since guizero can't do that at the moment.

You should be able to add this line to pack the writing widget manually in a way that will center it both horizontally and vertically.

```
writing.pack(fill="none", expand=True)
```

**Comment by James100000** [comment]
Problem solved!!!
Yes that is working very well, I did not realize that tkinter works in with Gui Zero.
Now I can commence finishing other projects with this problem solved, now everything is up and working.

Gui Zero is easy to work with once over the first hurdle.

I wish there was courses one good do with Gui Zero and tkinter?

Thank you so much for your help and input.

It has made my day.

Thank you.
