### ISSUE TITLE
guizero title font (not titlebox)

### ISSUE THREAD

**Issue by spyide** [lawsie/guizero#450]
I have searched for how to change the font of the title in App container or any other container created by using Window.
I am unable to find an answer and would appreciate any info on where to find it.
thank you
mp

**Comment by martinohanlon** [comment]
Can you expand on what you mean by the 'title in the App container'?

Do you mean the text which is shown in the top of the window? e.g. in the bar which runs across, where it says guizero in the screenshot below?

![image](https://user-images.githubusercontent.com/2329501/180666390-8d794442-72f8-4649-8cc5-a2d7c311b6f0.png)

If it's that you can't change the text, it is set by the operating system.

**Comment by spyide** [comment]
Sorry i wasn't clear.

[cid:c91003c3-bee8-4f02-ae91-0fa0ab81b03b]

here is a screen capture.
as you see, i have two windows and their title in the bar is different. (i.e. with different texts)
perhaps you mean the font in the bar is controlled by the system?
i would like to change the size of that font without resorting to having to change the system fonts.

thank you for reply.
mike

________________________________

**Comment by martinohanlon** [comment]
The screenshot isn't showing.

**Comment by spyide** [comment]
Sorry it didn't come through.
i attaching a new capture.
thanks
mike
________________________________

**Comment by martinohanlon** [comment]
Still no screenshot. I think you will have to upload it directly on GitHub.com.

Regardless if you are trying to change the menu bar font, I doubt there is anyway to do it with changing the system fonts. There is certainly no way through guizero. 

I don't know if it's important to you but there probably isn't a cross platform way of doing this either, macos windows for example don't have the menu bar at the top of the window.

**Comment by spyide** [comment]
![guizerotabex](https://user-images.githubusercontent.com/72161674/180846787-fd83e5fe-7c50-473b-89f2-f7701030d33b.jpg)
i hope this will get image through.
it seems that since we can change the text, we should somehow be able to cgange font properties, if we need to resort to tkinter.

**Comment by spyide** [comment]
i directly uploaded on github.
thanks
________________________________

**Comment by martinohanlon** [comment]
I haven't looked in-depth (maybe a search through tkinter docs will reveal something) but I don't think you can change the font on the window titlebar. It is set through system fonts.

**Comment by martinohanlon** [comment]
Closing this issue. Feel free to reopen if you have anything to add :)

**Comment by spyide** [comment]
hello, hope all is well with you.
i have been working on making a gui, and i have question/request

  1.  i am creating several Box widgets, all using app=App(etc as master.
  2.  i use grid layout for the master.
  3.  i also use grid layout for each box.
  4.  these are the difficulties i find:
     *   using the same keyword grid for both the box in the master and the widgets in box can become confusing. is there any way to have a different grid label for each widget in the combo?
     *   i am finding out the the grid coordinates do not create an absolute position within the grid, that is if for example i have 3 x 3 grid and if i want to place box (or widget) in grid [2,0] it will not place it there. it is at [0,0]. the only way i found to solve this problem is to create an empty widget in the grid positions before the one i want. The same occurs when widgets are placed in a Box. Is there something i missed in the instructions?
     *    i want to able to hide or make invisible a Box or widget. Again, the position is not absolute because the other widgets change their location.
     *   in (c) i have not figured out a way.
  5.  I have attached my program. Please do not make it public.
  6.
  7.  thanks
  8.  mike

  1.

**Comment by martinohanlon** [comment]
@spyide this is a closed issue and its not a great place to be asking for unrelated support and advice.

There is a section in the documentation with advice on where to get help - https://lawsie.github.io/guizero/gettinghelp/

Some general advice on your points. Using the grid layout is not a good strategy for absolute positioning as any empty "cell" will be resized to zero. guizero doesnt have a concept of creating absolute (fixed / placed) layouts, all guis being essentially dynamic and changing the size and contents of the window. My recommendation for most scenarios is to use an "auto" layout    and use boxes and aligns to configure where you want widgets to be. There is a section on how to create layouts in the documentation - https://lawsie.github.io/guizero/layout/

> using the same keyword grid for both the box in the master and the widgets in box can become confusing. is there any way to have a different grid label for each widget in the combo?

Not currently, although I suppose you could create variables / constants for the grid positions and use those to make the code simpler. If you have a feature request pls raise a new issue a code example of what you are hoping for would be useful.

**Comment by spyide** [comment]
please ignore my previous question.
i found the way to do what i need.
have a nice weekend
thanks
mike
