### ISSUE TITLE
Image resizing - cannot scale the image as PIL is not available

### ISSUE THREAD

**Issue by LevandeKokbok** [lawsie/guizero#453]
I get '*** GUIZERO WARNING *** Image resizing - cannot scale the image as PIL is not available.'
I have 
import PIL
from PIL import Image
and I have installed the extensions, why do I get this error?

Regards,
Richard

**Comment by martinohanlon** [comment]
Because python is raising an ImportError when running:

```python
from PIL import Image, ImageTk
```

I would check that pillow is actually installed for the version of Python
you are running this program as.

**Comment by LevandeKokbok** [comment]
I am running Python 3.9.2 and PIL 8.1.2 and according to information on the PIL Fork documentation that is a valid combination.
When I try 'from PIL import Image, ImageTk' it can't resolve 'ImageTk' so all I can assume is that something is not right with my environment.
The machine I am using is a Raspberry Pi 4 and all of the software is up to date.

Thanks for your response. Have you any ideas.

**Comment by LevandeKokbok** [comment]
Okay I have run 'python3 -m pip install --upgrade Pillow' and that updated my Pillow to 9.2.0.  Problem resolved thank you very much for your help

**Comment by martinohanlon** [comment]
No worries, I'm going to close the issue.
