### ISSUE TITLE
Color control - TextBox Background and Pushbutton

### ISSUE THREAD

**Issue by vader7071** [lawsie/guizero#459]
I have been working with the GUIZero module, and would like to be able to set the color of the pushbuttons based on an event state.

Additionally, I edited the app's background color, and when I called a textbox, the textbox was the same color as the background. It would be nice to be able to (as an example) set the app bg="green" and textbox bg="white"

**Comment by lawsie** [comment]
Hello! I think you can already set the colour of the button based on an event? e.g. 

```
from guizero import App, PushButton, CheckBox

def make_red():
    if cb.value == 1:
        bt.bg = "red"
    else:
        bt.bg = None

app = App()

bt = PushButton(app, text="A button")
cb = CheckBox(app, text="Tick me to make the button red", command=make_red)

app.display()
```

...but perhaps I have misunderstood? 

Also you can set a textbox background colour, just not in the constructor:

```
from guizero import App, TextBox

app = App(bg="green")

tb = TextBox(app)
tb.bg = "white"

app.display()
```

Does this help with what you wanted to do?
