### ISSUE TITLE
TextBox features

### ISSUE THREAD

**Issue by lawsie** [lawsie/guizero#46]
Perhaps add larger text, colours etc?

**Comment by martinohanlon** [comment]
Auto sizing based on text length.

**Comment by bsimmo** [comment]
multiline and adjustable height too

**Comment by scotty3785** [comment]
I had created a multiline capable version of the TextBox 
https://github.com/scotty3785/guizero/tree/multiline_textbox
This uses the tkinter Entry widget if multiline=False or the tkinter Text widget if multiline=True.
The Text widget has much better native support for 'rich text' but isn't as simple to use.

**Comment by martinohanlon** [comment]
Thanks @scotty3785, i used your version for the basis of adding multiline functionality to the textbox (https://github.com/lawsie/guizero/commit/6cffb1dd7d5eefc1267798135dc284f3fde08eeb)

It will be in v 0.5.0

**Comment by scotty3785** [comment]
Looks good. Nice usage of the scrolled text widget.

**Comment by martinohanlon** [comment]
resolved in v0.5.0
