### ISSUE TITLE
Destroying a container could destroy the widgets contained inside it.

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#460]
**Is your feature request related to a problem? Please describe.**
When you destroy a container, there is no code to destroy the widgets which are contained inside it. e.g.

```python
from guizero import App, Box, Text

app = App()
box = Box(app)
text = Text(box)

box.destroy()

app.display()
```

This code will call the tk `destroy` method of the `Box`, but not the `destroy` method of the `Text` widget. 

I dont know what state this would leave the application in. I suspect not a good one, with the `Text` which zombified (we should test this). You could argue that it isnt guizero's job to tidy up and Python / tk should do it... but....  I think it would be relatively easy to modify the `Component` class to call the `destroy` method on any children of a Container type class.

Maybe modifying this method - https://github.com/lawsie/guizero/blob/master/guizero/base.py#L181

**Comment by rdbende** [comment]
> This code will call the tk destroy method of the Box, but not the destroy method of the Text widget.

The Tkinter `.destroy()` methods also destroys all of the widget's descendants (recursively), so there's no need to call them in GuiZero.

**Comment by martinohanlon** [comment]
Thanks for the info. There are guizero widgets which override the tk destroy method. I still think it's worth looking into even if there is nothing to do.

**Comment by martinohanlon** [comment]
Closing. I look, I dont think there is anything to do :)
