### ISSUE TITLE
Guizero animation importing picture into a moving oval

### ISSUE THREAD

**Issue by pythonismysuperpower** [lawsie/guizero#462]
I'm making a game right now where a small oval is the player controlled by the user's keyboard to move around the canvas. However, I want to import a picture cropped in circular form into the oval player that is just in color black. 

the canvas is 500 in width, 500 in height. the oval is 20,20,40,40 in size. However, I also do not know how to implement the code for the size of the picture into the small oval. 

i'm using this code to import the picture into the oval. 

from guizero.utilities import GUIZeroImage

def add_image_to_drawing(drawing, image, x, y, anchor="nw", **kwargs):
    return drawing.tk.create_image(x, y, image=image.tk_image, anchor=anchor, **kwargs)

(this is the animation part)

 add_image_to_drawing(
            drawing=self.drawing,
            image=self.image,
            x=400, y=400
        )

i need help asap!

**Comment by lawsie** [comment]
Hi @pythonismysuperpower (I love your name). Can I suggest you have a look at pygame/[pygamezero](https://pygame-zero.readthedocs.io/en/stable/) instead? guizero isn't really meant for creating games of this format and I think you'll find it unnecessarily hard to make it do what you want, whereas this is exactly what pygame is for.

**Comment by martinohanlon** [comment]
Closing as there has been no movement. Feel free to reopen if you have more information.
