### ISSUE TITLE
Adhere to OOP concepts

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#47]
If we stick to OOP concepts, future development will be a *lot* easier. I suggest creating a widget class which instantiates an underlying `tkinter` widget of sorts when called:

```python
import tkinter as tk


class _Widget:
    """An abstract `tk` widget."""
    def __init__(self, widgettype, **kwargs):
        """Instantiate `widgettype(**kwargs`)."""
        self._widget = widgettype(**kwargs)

    def enable(self):
        """Enables the widget."""
        self._widget.configure(state="normal")

    def disable(self):
        """Disables the widget."""
        self._widget.configure(state="disabled")

```

We can then simply create `_Widget` subclasses, without the cluttered default Tcl options:

```python
import tkinter as tk

from _widget import _Widget


class Text(_Widget):
    """A Text widget displays text."""
    def __init__(self, text="", size=12, color="black", font="helvetica", grid=None, align=None):
        super().__init__(
            widgettype=tk.Label,
            text=text,
            size=size,
            foreground=color,
            font=font
        )
        # Do stuff with `grid` and `align`...
```
This has a couple of advantages:

* Methods that can be applied to all widgets (like `enable` / `disable` for switching state, `repeat` to repeat a callable every x milliseconds and display options for hiding, showing, aligning widgets) can be inherited from `_Widget`.

* Reusing methods means having to write only one docstring (e.g. `_Widget.enable`: 'enables the widget' instead of `Text.enable`: 'enables the text widget'; `Button.enable`: 'enables the button widget'; etc.)

* Validating argument types / values can be done within `_Widget.__init__` (or using helper functions) instead of doing this individually for each widget type.

What do you think?

**Comment by lawsie** [comment]
I've already implemented #38 on the version 0.4 branch as per @bennuttall 's suggestion, which puts the TK object inside the guizero object, so that any of the tk functionality people might want to access can be easily got at via `Object.tk.methodname`.  However it might be useful to have the functions that all widgets will need to use (e.g. after, enable, disable) written in one place and then inherited. I was actually thinking about this yesterday. Would combining the two be possible?

**Comment by bennuttall** [comment]
> However it might be useful to have the functions that all widgets will need to use (e.g. after, enable, disable) written in one place and then inherited. I was actually thinking about this yesterday. Would combining the two be possible?

Possibly, but you might find the implementations differ, and you end up writing them directly anyway.

**Comment by Coal0** [comment]
I know for a fact it will be very easy for most methods. Here's some examples:

* `enable` for switching state to 'normal'
* `disable` for switching state to 'disabled'
* `display`
* `destroy` or similar, for destroying widgets
* `hide` or similar, for hiding widgets (`grid_forget`, `pack_forget`)
* `focus` or similar for giving focus to widgets

Example implementations:

```python
import tkinter as tk


class _Widget:
    """An abstract `tk` widget."""

    def __init__(self, widgettype, **kwargs):
        """Instantiate `widgettype(**kwargs`)."""
        self._widget = widgettype(**kwargs)

    def enable(self):
        """Enables the widget."""
        self._widget.configure(state="normal")

    def disable(self):
        """Disables the widget."""
        self._widget.configure(state="disabled")

    def destroy(self):
        """Destroys the widget."""
        self._widget.destroy()

    def focus(self):
        """Delegates focus to the widget."""
        self._widget.focus_set()

    def hide(self):
        """Hides the widget. Call `_Widget.display` to show the widget
        again.
        """
        if <widget is packed>
            self._widget.pack_forget()
        else
            self._widget.grid_forget()
```

**Comment by lawsie** [comment]
This looks like a good idea, but instead of extending `_Widget` in exactly the same way, I'd like to keep my internal `tk` objects (since I spent a long time adding those), but potentially also have some methods like this that are available to all widgets. Could I still have each guizero widget inherit from `_Widget` to get to the properties but not use the `widgettype` as you do here?

**Comment by Coal0** [comment]
Absolutely, by removing the constructor and replacing `self._widget` with `self.tk`:

```python
class _Widget:
    """An abstract `tk` widget."""

    def enable(self):
        """Enables the widget."""
        self.tk.configure(state="normal")
    
    ...
```

**Comment by lawsie** [comment]
Pulled #57 and ready for testing across all widgets
