### ISSUE TITLE
TextBox command

### ISSUE THREAD

**Issue by romilly** [lawsie/guizero#471]
I'd welcome an extension to TextBox such that an optional command gets invoked whenever the text is changed.

I need it for automated application testing. I can do it by subclassing TextBox (thanks to ChatGPT4, which wrote the code for me!), but others might find it useful, in which case it would be great to have it as part of guizero.

I can submit a pull request for code and docs if you think it would be useful to others.

**Comment by martinohanlon** [comment]
Isn't this what the existing `command` does? 

Or maybe the `when_key_pressed` / `..._released` events?

**Comment by romilly** [comment]
Ooops - I somehow missed command for TextBox. Yes, that's what I need.
