### ISSUE TITLE
a issue on https://lawsie.github.io/guizero/about/

### ISSUE THREAD

**Issue by yingjie52** [lawsie/guizero#473]
https://lawsie.github.io/guizero/about/---using  guizero/widgets

steps:     clicking  using  guizero/widgets    
results:    no response

**Comment by martinohanlon** [comment]
The only link to using widgets I can see on https://lawsie.github.io/guizero/about/ is from the menu - is that right?

The link doesnt appear to be broken.

![vid](https://github.com/lawsie/guizero/assets/2329501/2d11a656-4a36-4505-9b43-70d93d1784b7)

**Comment by yingjie52** [comment]
It seems to happen on Google Chrome, and it's normal for me to use other browsers

**Comment by martinohanlon** [comment]
Suggest we leave it open for a little while to see if there are other reports but I can't reproduce.

**Comment by lawsie** [comment]
@martinohanlon It might be that the menu doesn't open! @yingjie52 said "Click using guizero/widgets" which you have translated as using guizero > using widgets in the submenu. Could be related to the jquery thing?

**Comment by martinohanlon** [comment]
> @martinohanlon It might be that the menu doesn't open! @yingjie52 said "Click using guizero/widgets" which you have translated as using guizero > using widgets in the submenu. Could be related to the jquery thing?

I don't think it relates to the jQuery issue as that change was never pushed to the live site.

**Comment by martinohanlon** [comment]
No further reports and the new docs theme has been launched so closing.
