### ISSUE TITLE
Using Drawing... 

### ISSUE THREAD

**Issue by WarrenLead** [lawsie/guizero#474]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System information:**
 - OS: [e.g. Windows]
 - guizero version: [Type `pip show guizero` in a terminal/command prompt]

**Additional context**

**Comment by WarrenLead** [comment]
I want to draw a circle then delete the previous circle and draw a new one in a different postion one at a time.  Manual says returns id?  How do i find the id of the circle I want to delete? using delete() statement?  Not much mention of this in the docs and examples.

**Comment by martinohanlon** [comment]
Using the example from the docs for drawing a rect. An oval (or circle) is the same.

```python
from guizero import App, Drawing
app = App()
drawing = Drawing(app)

rect_id = drawing.rectangle(10, 10, 60, 60, color="blue")
drawing.delete(rect_id)

app.display()
```

Providing a description and example in the issue text rather than the title is much more helpful.

Removing bug label.

**Comment by WarrenLead** [comment]
Mate, the bug is that the documentation is not very clearSent from my iPadOn 7 Jul 2023, at 4:47 pm, martinohanlon ***@***.***> wrote:﻿
Using the example from the docs for drawing a rect. An oval (or circle) is the same.
from guizero import App, Drawing
app = App()
drawing = Drawing(app)

rect_id = drawing.rectangle(10, 10, 60, 60, color="blue")
drawing.delete(rect_id)

app.display()

Providing a description and example in the issue text rather than the title is much more helpful.
Removing bug label.

**Comment by martinohanlon** [comment]
"mate" ?

The documentation describes the return values and parameters for all these classes and functions. This is how I was able to provide you with an example to fix your problem.

It is not the job of the documentation to cover every eventuality nor my job to provide you with solutions to your problems.

**Comment by WarrenLead** [comment]
Thank you this fixed my problem.
Best regards 
==================
 Warren Leadbeatter
==================

----- Original Message -----

**Comment by martinohanlon** [comment]
You're welcome

**Comment by martinohanlon** [comment]
Closing
