### ISSUE TITLE
WafflePixel properties doc bug

### ISSUE THREAD

**Issue by bgiobbe** [lawsie/guizero#475]
**Describe the bug**
'x' is listed twice in WafflePixel properties. Second occurrence should be 'y'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '(https://lawsie.github.io/guizero/waffle/)'
2. Scroll down to 'WafflePixel', then 'Properties'

**Screenshots**
<img width="588" alt="WafflePixel-doc-bug screenshot" src="https://github.com/lawsie/guizero/assets/1522307/8571e33b-6784-4658-9dac-5eba5d220e71">

**System information:**
 - OS: MacOS 12.6.7
 - Browser: Firefox 114.0.2
 - guizero version: 1.4.0

**Comment by martinohanlon** [comment]
Released. Thank you for your contribution,
