### ISSUE TITLE
Error (typo) on the book manual

### ISSUE THREAD

**Issue by naurojr** [lawsie/guizero#484]
**Describe the bug**
On page 151 on the book, text_size and text_color are missing the T. 
You have it as ext_size and ext_color. 

Not a big issue, but may confuse someone. 

**Screenshots**
<img width="1053" alt="Screenshot 2023-08-15 at 11 34 46 AM" src="https://github.com/lawsie/guizero/assets/2048228/ce618b48-ce28-4059-b90e-d9350459d22c">

**Comment by martinohanlon** [comment]
Thats annoying. Thank you for reporting. Unfortunately we dont have the ability to update and change the book anymore (it was published by Raspberry Pi Press.
