### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by dahleet** [lawsie/guizero#485]
Reference: https://lawsie.github.io/guizero/blocking/

The page states:
"The line of code app.display() doesn't just display the app - it enters an infinite event loop which is watching and waiting for events to happen on the GUI. Events include things like the user clicking on a button, moving a slider, typing in a text box etc. No code written after this line will ever execute because the event loop is infinite."

This is inaccurate.  It should state:
"The line of code app.display() doesn't just display the app - it enters an event loop which is watching and waiting for events to happen on the GUI. Events include things like the user clicking on a button, moving a slider, typing in a text box etc. Code written after this line will execute only if the display is destroyed either by the .destroy command or the user clicking the upper-right x to close the window."

**Comment by martinohanlon** [comment]
Resolved
