### ISSUE TITLE
GUI has a white background

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#50]
Program is working fine, the overall GUI has a black background not a problem,  with the print out there is a white border surrounding the print out, any way of changing that to black.

Thanks

`from guizero import App, Text

def update_writing():

A = 50

B = 60

C = 70

lst = ['WORLD',A,B,C,'HELLO'] # This line added

D = (' '.join((str(x) for x in lst))) # This line added

writing.set(D)

app.after(200, update_writing)

app = App(height=2000, width=2000, bgcolor="black")

writing = Text(app, text="", color="red", size=100)

app.after(200, update_writing)

writing.pack(fill="none", expand=True)

app.display()`

**Comment by lawsie** [comment]
This doesn't exist in the current version of guizero but in the forthcoming 0.4 version you can specify a background colour for text.

In the mean time, you can add this code after you create the Text object

```
writing.config(bg="black")
```

PS when you post code, please use three backticks (`) before and after so it is formatted properly :)
