### ISSUE TITLE
app.box_color, feature!

### ISSUE THREAD

**Issue by PythonRPG010** [lawsie/guizero#500]
You know, there has a app.text_color and a app.bg feature to change the color of all the texts and backgrounds of the application, and i'm making an app that the theme changes between light and dark, when i try to change to dark mode, all the box borders dissapear! _"well, make a set_border!"_ ok, make a set_border to ALL the boxes? so just a little feature request! :)

**Comment by martinohanlon** [comment]
I think it would be confusing to add a "set_border" method to App. What is it setting the border of? The `App` (which I am not sure you can do)?, The `Box` objects? Any widgets inside the app?

Box already has a `set_border` method, if I was looking to do this in a single call (rather than having to individually call each box, which is what I think you are trying to avoid (?), I would write a function a bit like this:

```python
def set_box_borders(app, thickness, color):
   # go through app widgets
    for child in app.children:
        # is widget a box
        if isinstance(child, Box):
            child.set_border(thickness, color)
```

^ I havent tested this but hopefully you get the idea

**Comment by PythonRPG010** [comment]
Yeah, this is what i needed, i'm just a newbie in python so i forgot about that :b

**Comment by PythonRPG010** [comment]
> I think it would be confusing to add a "set_border" method to App. What is it setting the border of? The `App` (which I am not sure you can do)?, The `Box` objects? Any widgets inside the app? Creating a set_box_borders feels oddly specific, would it set a precedent to also create other `set_thing_method` methods?
> 
> Box already has a `set_border` method, if I was looking to do this in a single call (rather than having to individually call each box, which is what I think you are trying to avoid (?), I would write a function a bit like this:
> 
> ```python
> def set_box_borders(app, thickness, color):
>    # go through app widgets
>     for child in app.children:
>         # is widget a box
>         if isinstance(child, Box):
>             child.set_border(thickness, color)
> ```
> 
> ^ I havent tested this but hopefully you get the idea

Ok... i tested and nothing! maybe i will need to do it manually ;(
i modified the code put this def in it and nothing...
and about the app.box_color feature, the idea was to be similar to the app.text_color, that changes every one of this objects color!

**Comment by martinohanlon** [comment]
I just wrote a test application. This works.

```python
from guizero import App, Box, Combo, PushButton, Text

def set_box_borders(app, thickness, color):
   # go through app widgets
    for child in app.children:
        # is widget a box
        if isinstance(child, Box):
            child.set_border(thickness, color)

app = App()
b1 = Box(app, border=True)
t = Text(b1, "Change box borders")

b2 = Box(app, border=True)
color = Combo(b2, options=["red", "green", "blue", "black"], selected="black")
change_button = PushButton(b2, text="Change", command=lambda: set_box_borders(app, 2, color.value))

app.display()
```

You can change the box code and thickness without needing a "redraw". guizero doesnt control when the application view is update. This is controlled by tkinter / the operating system. It could be that your application isnt giving enough "time" for this to happen. You can call app.update() which will force a screen update.

**Comment by PythonRPG010** [comment]
> I just wrote a test application. This works.
> 
> ```python
> from guizero import App, Box, Combo, PushButton, Text
> 
> def set_box_borders(app, thickness, color):
>    # go through app widgets
>     for child in app.children:
>         # is widget a box
>         if isinstance(child, Box):
>             child.set_border(thickness, color)
> 
> app = App()
> b1 = Box(app, border=True)
> t = Text(b1, "Change box borders")
> 
> b2 = Box(app, border=True)
> color = Combo(b2, options=["red", "green", "blue", "black"], selected="black")
> change_button = PushButton(b2, text="Change", command=lambda: set_box_borders(app, 2, color.value))
> 
> app.display()
> ```
> 
> You can change the box code and thickness without needing a "redraw". guizero doesnt control when the application view is update. This is controlled by tkinter / the operating system. It could be that your application isnt giving enough "time" for this to happen. You can call app.update() which will force a screen update.

Continue not working, but i don't know why... thanks for your help but i'm just gonna give up of trying to change the box border colors...
