### ISSUE TITLE
Is there a way to control the size of a button

### ISSUE THREAD

**Issue by LouisPi** [lawsie/guizero#53]
I can't see any way to control the size of a button. Is there a built-in method or any other method I can use to control the size of a button. Any help appreciated.

Thanks, LouisP

**Comment by LouisPi** [comment]
Maybe creating an image the size I want the button to be and using that as a button is the best approach.

**Comment by lawsie** [comment]
At the moment, the only way that's part of guizero is to add padding to the button. You can set padding either when you create the button, or afterwards using the `padding(padx, pady` method. See https://lawsie.github.io/guizero/pushbutton/

HOWEVER

You can combine some tkinter functionality to do this:

```
from guizero import App, PushButton

def do_stuff():
    print("Do nothing")


app = App("Hello")

button = PushButton(app, text="Hello", command=do_stuff)

# Make the button bigger
button.config(height=30, width=50)

app.display()
```

I have no idea why I haven't added this to guizero. I will add it to the 0.4 release. :)

**Comment by lawsie** [comment]
Added https://github.com/lawsie/guizero/commit/8b0d2e12ae1129e4ad212ef58d98f6f0f3bbfcc5

**Comment by LouisPi** [comment]
Thanks for the help. Out of interest though, any idea when guizero 0.4 will come out? Can't wait!

**Comment by lawsie** [comment]
Soon (TM)! It's been a bit tricky getting stuff done as I'm pretty exhausted after work. Hopefully before Christmas!

**Comment by LouisPi** [comment]
Okay!
