### ISSUE TITLE
Keep button size the same

### ISSUE THREAD

**Issue by LouisPi** [lawsie/guizero#56]
Hello again, I have been experimenting with different font sizes in buttons using the config option. However, when I change the font size the button changes size as well! How do I make it so the button maintains the same size even if I change the text size? 

Thanks in advance for any help,
LouisP

**Comment by LouisPi** [comment]
I have done more research and it looks like the best option is using this website: [](http://www.text2image.com/pit_t2i/saver) to create a gif image of the size I want the button to be with the text in the image and using that instead of text.

**Comment by Coal0** [comment]
Why would you want the text to be larger than the button? Please provide an example (drawing,).

**Comment by LouisPi** [comment]
I don't want the text to be larger than the button, I just want to be able to control the size of the button in pixels as I am going to have different font sizes in different buttons but I still want them all to fit together nicely.
