### ISSUE TITLE
Can the size of a button be controlled in pixels

### ISSUE THREAD

**Issue by LouisPi** [lawsie/guizero#59]
Please close my old issue.

Hello everyone, is there a way to control the size of a button in pixels not characters?

Thanks for any help,
LouisP

**Comment by lawsie** [comment]
Mmm...you're right! I just noticed that the sizing for buttons containing text is in terms of characters not pixels, which I hadn't spotted before.

There's a bit of a hacky fix here:
http://effbot.org/tkinterbook/button.htm

It's something I need to consider for guizero though. I suspect pixels is more intuitive.

**Comment by LouisPi** [comment]
Thanks for the help. Measuring button size in characters is a good idea but as everything else is measured in pixels in tkinter and guizero so it makes it difficult.

**Comment by martinohanlon** [comment]
I am closing this as I have created an issue about the ability to set all widgets width and height. #136
