### ISSUE TITLE
Suggestion: clarify this is a Python 3 package

### ISSUE THREAD

**Issue by carlosperate** [lawsie/guizero#6]
Since this package targets users that might have limited knowledge about Python versions it might be a good idea to clearly indicate on the README that this is a Python 3 only package.

I would probably go as far as to add this to the setup.py file:

```python
from sys import version_info
if version_info.major != 3:
    print("This package will only work with Python 3. \n" 
          "If you already have Python 3 installed try 'pip3 install guizero'.")
```

This way it will not break with cryptic messages during installation or first run.

**Comment by carlosperate** [comment]
Yes, between the imports and the first function will do.

**Comment by lawsie** [comment]
I added this in 0.3.0...I hope. Right after I did that I made a horrible merge conflict mess :)
