### ISSUE TITLE
Made a dice rolling app relying on guizero.

### ISSUE THREAD

**Issue by maskedmakrel** [lawsie/guizero#60]
It works pretty well.  The only thing I could not seem to get it to do was clear the text of the output, so I just wrote spaces over the text each time.  :)

Anyway, here is a guizero based dice roller for anyone interested.  It's a good way to understand the use of global variables.  I usually output everything to the terminal to have a history and validate the operations of the program.  

https://github.com/maskedmakrel/VirtualDicePy/blob/master/guiroller.py

Good luck with the guizero project.

**Comment by lawsie** [comment]
Cool program :) 

To clear the contents of a `Text` you can just call `clear()` on it, like this:
```
messagebox = Text(app, text="Some stuff")
messagebox.clear()
```

You need to create the `Text` object in the main bit of your program (where you make the buttons etc.) and then you can just refer to it in your functions. Don't redefine it inside the function. 

You can also add text to the end of whatever text is already inside, like this:

```
messagebox.append("Some more text")
