### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#63]
So I skimmed over the project directory but I couldn't find a 'tests' folder or similar. It's really helpful to have a way to test commits quickly, especially as the project grows larger. Do you mind if I set up a basic testing file that we can expand later (perhaps under a separate folder?)? Thanks.

**Comment by lawsie** [comment]
Yes please, that would be great. However, please could you explain how it works too so that I can learn something? I have done basic testing myself but to see how it's properly meant to be done would be really useful. :D Thanks for your work so far!

**Comment by Coal0** [comment]
Awesome. I'm not an expert in writing unittests myself, but I'm currently working on a side project that can (hopefully) simplify testing tkinter GUIs, that may prove useful here.

**Comment by Coal0** [comment]
@lawsie Testing's looking good, but only works for v0.4 and upward. I tried writing backward-compatible code but it was a ton of work and still ended up failing (of course). I'm sick of writing unit tests for today, but I'll see if I can finish off and open a PR tomorrow.

**Comment by martinohanlon** [comment]
Excellent. Is the code committed? It would be good to see.

**Comment by Coal0** [comment]
Not yet. I want to get some major issues out of the way before putting it up for review. I'm currently tackling problems with `tk.update` calls in the `App` properties, I'll open a separate issue for that.

**Comment by martinohanlon** [comment]
Ok, it would be good to see your framework when ready, perhaps we can share the burden of creating tests?

**Comment by Coal0** [comment]
That would be great. I'm going crazy trying to come up with reasonable test cases. I'll add a `tests` directory with the related files.

**Comment by martinohanlon** [comment]
Hi @Coal0 

How did you get on with creating some tests for guizero? Is there a branch I could see? I am going to start implementing tests into guizero and its seems fruitless starting from scratch if there is something already built.

Thanks

**Comment by martinohanlon** [comment]
I have created a suite of unit tests which cover all the existing widgets. 

Certainly not perfect and I doubt there is 100% coverage, but it should significantly reduce the risk of introducing errors in future release.

I am going to close this issue, if a better alternative is available in the future, I would be really interested in seeing it.
