### ISSUE TITLE
enable / disable widgets

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#64]
Simple methods and properties to enable or disable widgets could be useful.

Rather than the setting of state

```
mycontrol.state(["disabled"])   # Disable the button.
mycontrol.state(["!disabled"])
```

create properties and methods to simplify e.g.:

```
mycontrol.enable()
mycontrol.disable()
```

or create it as a property
```
mycontrol.enabled = True
mycontrol.enabled = False
```

A Mixin could be useful as there are multiple controls which could use the same code:

```
class EnableMixin(object):
    def enable(self):
        return self.state(["!disabled"])
    def disable(self):
        return self.state(["disabled"])
```

Then each control which needs it could inherit it, e.g.:

```
class PushButton(Button, EnableMixin)
class Combo(OptionMenu, EnableMixin)
```

**Comment by lawsie** [comment]
I think https://github.com/lawsie/guizero/commit/8ba8e869cd9440de4bcf592fbbdce9a4ac97b4fb does this already?

**Comment by martinohanlon** [comment]
Excellent
