### ISSUE TITLE
Documentation: Wrong class signatures

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#66]
I was taking a look at [the docs for `App`](https://lawsie.github.io/guizero/app/) and found the class signature is outdated:

> `class guizero.App(title="GUIzero", height=500, width=500, layout="auto", bgcolor=None)`

The correct class signature is 

> `__init__.py(self, title="guizero", width=500, height=500, layout="auto", bgcolor=None)`
<sup>Source: https://github.com/lawsie/guizero/blob/master/guizero/App.py</sup>

(Note the capitalization: `"GUIzero"` → `"guizero"`).
I guess this isn't a huge issue, but I got confused because some test cases were failing. I guess this should be fixed all at once in the 0.4 release? I don't know if this is true for other widgets too, but I'll take a look sometime soon.

This error persists in the <b>Parameters</b> section:

Parameter | Data type | Default | Compulsory | Description
-----------| ----------| --------| ------------ | ------------
title            | string       | "GUIzero" | No            | The title displayed in the bar at the top of the window.

**Comment by lawsie** [comment]
Yeah, I'm in the process of updating all of the docs (which is fun!)

**Comment by Coal0** [comment]
To be fixed.
