### ISSUE TITLE
`App` properties calling `tk.update`

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#67]
It's fine that the `App` properties call `tk.update`; in fact, that's required for automated testing. However, three things need to be changed for this to work properly:

* `App.__init__` should call `tk.update` once, to assure that the tests can initialize a new object and get its dimensions without interacting with the properties.
* The property getters should not call `tk.update`. It simply makes no sense.
* The property setters should call `tk.update` *after* calling `tk.geometry`. This way the window changes are applied just before returning.

If you don't mind, I'll open a PR with these changes.

**Comment by martinohanlon** [comment]
This looks like its fixed by PR #71  ?
