### ISSUE TITLE
Reading 2 sensors 

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#70]
This program that reads one sensor works very well but when using two sensors it stops working after about five minutes.

I am more then satisfied with this program just not sure what would cause the graphics program to stop  reading using two sensors.

`` `` ``
from guizero import App, Text
def update_writing():
          
          
          A = open ("/sys/bus/w1/devices/28-00000781336e/w1_slave")

          B = A.read()

          A.close()

          C = B.split("\n")[1].split(" ")[9]

          D = float(C[2:])

          E = D/1000

          A1 = open ("/sys/bus/w1/devices/28-0000079ee449/w1_slave")

          B1 = A1.read()

          A1.close()

          C1 = B1.split("\n")[1].split(" ")[9]

          D1 = float(C1[2:])

          E1 = D1/1000
          

          if E < 85:

           T = ('S1',E,'S2',E1)      

           print('SENSOR 1: ',E)

           print('SENSOR 2: ',E1)

           
                  
           writing.set(T)
           app.after(200, update_writing) 

app = App(height=1000, width=1000,bgcolor="black")

writing = Text(app, text="TEMP C", color="red",size=50)

writing = Text(app, text="", color="red",size=50)

writing.pack(fill="none", expand=True)

app.after(200, update_writing)
app.display()

``````

**Comment by lawsie** [comment]
I would imagine the answer is that reading the two sensors and processing the data takes more than 200ms, so your callbacks get backed up over time causing you to run out of memory. Try running the program with a longer callback time - I'm not sure you would even be able to notice the difference between updating every 200ms and every 1000ms. 

Not related to this issue, you seem to have two widget definitions called `writing`. If you want two different widgets, give them different names. I would also suggest using more descriptive variable names - trying to work out what someone else's program is doing when their variables are called A,B, C etc. is doable for programs of this size and complexity but would not be a pleasant experience for a larger program! :)
