### ISSUE TITLE
App enable, disable, hide, show

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#75]
The functions enable, disable, hide, show within _Widget dont work with App.

I would suggest we refactor _Widget to group the functions into a number of Mixins e.g. 
- after, repeat, cancel
- enable, disable
- show, hide
- destroy
- focus

these can be inherited into the guizero components as appropriate e.g.
- PushButton(AfterRepeatCancel, EnableDisable, ShowHide, Destroy, Focus)
- App(AfterRepeatCancel, Destroy)

Happy to pick this up.

**Comment by Coal0** [comment]
+1 Yes, please. Would you mind changing the names to `<name>MixIn` for clarity (like `threadingMixIn`, I believe, in `SocketServer`)?

**Comment by martinohanlon** [comment]
Yes, they would follow the [name]Mixin standard, this was just for illustration.

**Comment by lawsie** [comment]
That sounds good. I was thinking that some of them probably don't apply to `App` (and probably `Box` too). 

I've started writing up the new documentation so I'll have to change some of it, but that's not a problem!

**Comment by martinohanlon** [comment]
Ill create a new branch for this as there will be a lot of change so its worth merging this in the version-0.4 branch separately so we can get visibility of the change

**Comment by martinohanlon** [comment]
Create tkmixins branch to do this work in and have updated App as an example of how I propose to do it.

[commit updating App](https://github.com/lawsie/guizero/commit/1e488573375d87efa356c3f6bb1a48be3bc46fc2)

Please comment if you have any views

**Comment by martinohanlon** [comment]
I have committed the changes to refactor _Widget into the tkmixins branch.

[commit](https://github.com/lawsie/guizero/commit/1d3d715cc0359e1558c7bbab80fae8db97ad9fb9)

**Comment by martinohanlon** [comment]
Complete, in v0.4 and docs updated
