### ISSUE TITLE
Implement Common Interface

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#84]
Refactor components to have a common 'interface'.

Implementation of interface mixins to support common methods and properties (description, repr, etc).

Starting point for other x widget interfaces (on_press, on_release, on_mouse_over, etc).

**Comment by martinohanlon** [comment]
Some thoughts?

Are there 3 types of component?
 - app (or window)
 - container (e.g. window / box)
 - widget (a component which is added to a container)

all 3 have:
 - description
 - color?
 - events (on_press, on_release, mouse-over, etc)

all but the app have:
 - master

Containers have:
 - layout
 - children
 
Widgets have:
 - grid position
 - alignment
 - command

**Comment by martinohanlon** [comment]
Should all containers and widgets describe their master and children?

**Comment by martinohanlon** [comment]
Implementing Master, Widget & Container mixins in 0.4.2

**Comment by Coal0** [comment]
This seems pretty complex to me. Kudos for pulling it off in the latest commit. I'm not too sure what to think yet.

**Comment by martinohanlon** [comment]
The concept is very simple, as guizero moves towards production I want to create as much consistency in the api as possible. e.g. If a user knows how to use PushButton it should be second nature to use Slider.

**Comment by Coal0** [comment]
Sounds cool. If I can help out, let me know. I've picked up on testing again, you can hopefully expect an update on that soon.

I think color should definitely be part of this (sparked by [this issue](https://github.com/lawsie/guizero/issues/94)). Should this be handled separately for text color?

**Comment by martinohanlon** [comment]
Thanks for the comments and all the work you have done. I have raised a seperate issue re setting text_color and bg_color.

**Comment by martinohanlon** [comment]
Now all widgets support the same set of methods and properties, I think I can create an class hierarchy...  Happy days,

**Comment by martinohanlon** [comment]
I have refactored guizero and created a class hierarchy 

![guizero_class_hierarchy](https://user-images.githubusercontent.com/2329501/38178125-e34bb3a4-3603-11e8-8f98-e21c47af4571.jpg)

This will be useful when adding guizero wide features such as events.

**Comment by martinohanlon** [comment]
resolved in v0.5.0
