### ISSUE TITLE
Speed Dial, RPM Guage, Instument Guage

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#89]
With GUI Zero is it possible to create GUI gauges like below for showing sensor output or similar.

Industry now uses GUI graphics to represent sensor readings.

Thanks

![guage1](https://user-images.githubusercontent.com/33335919/34436000-c0b394e0-eccc-11e7-88a7-c61f84b5abe3.png)
![guage3](https://user-images.githubusercontent.com/33335919/34436002-c0f62ae4-eccc-11e7-8e2d-91baa9b5b7d2.png)
![guage](https://user-images.githubusercontent.com/33335919/34436003-c137ff6e-eccc-11e7-943a-152d1ea6e669.jpg)

**Comment by Coal0** [comment]
As far as I'm aware you could only implement this using [the tkinter `Canvas` widget](http://effbot.org/tkinterbook/canvas.htm). There's no drag 'n drop gauge widget available in either Guizero or the tkinter library.

**Comment by martinohanlon** [comment]
As @Coal0 says there is no gauge like widget in guizero or tkinter.  One could be built but it would be low down the priority list and it would be unlikely to be the high resolution type you seem to be after.

If I was looking to build these using python, I would lean towards something built in pygame.

**Comment by abetterautomation** [comment]
There is a dial widget on my github that is drawn using Tkinter canvas. A tester module is included that shows an example of the dial being used as a speedometer.
