### ISSUE TITLE
Suggestion: Remove try...catch on the import of tkinter in the controls

### ISSUE THREAD

**Issue by drussell1974** [lawsie/guizero#9]
Each control has a try...catch to handle failure to import tkinter. However, this is handled in the App and Box classes, whose instances are passed to the controls. To save the expense on performance, having try...catch in the controls should not be necessary for this, if already checked when initiating it in the respective container classes.

**Comment by lawsie** [comment]
Fixed by PR from @carlosperate - thank you :)
