### ISSUE TITLE
Update python to 3.5.3 has errors.

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#92]
This program was working perfectly using Python 3.5.2
Using Raspberry pi which updated to python 3.5.3 it has a error that repeats on shell,

The error is
d.
*** DEPRECATED: Text set() is deprecated. Please use the value property instead.
*** DEPRECATED: Text set() is deprecated. Please use the value property instead.

Thanks

``````
import datetime
from datetime import datetime, date, time
import time
from guizero import App, Text
def update_writing():    

    

    C = ('LOCAL TIME')
    D = (time.strftime("%H:%M:%S"))
    E = ('UTC')
    F = datetime.utcnow().strftime("%H:%M:%S")


    
    writing3.set(C)
    writing4.set(D)
    writing5.set(E)
    writing6.set(F)
    
    
    app.after(200, update_writing)

app = App(height=500, width=500,bg="black")

writing3 = Text(app, text="C", color="green",size=30,bg="black")
writing4 = Text(app, text="D", color="green",size=30,bg="black")
writing5 = Text(app, text="E", color="green",size=30,bg="black")
writing6 = Text(app, text="F", color="green",size=30,bg="black")

app.after(200, update_writing)
app.display()
  
``````

**Comment by martinohanlon** [comment]
Its not the change to Python 3.5.3 but the upgrade of guizero to 0.4 which caused the warning messages.

0.4 depreciated a number of old methods in favour of using properties.

Your program will still work but as the warning says you should use the `value` property instead of the `set` method.

i.e. 

```
writing3.set(C)
```

should become 

...
writing3.value = C
```

**Comment by James100000** [comment]
That saved the day.
Just getting to know GUI Zero and that change had occurred had me worried.
That is just a sample program that I use as the basic core for other more complex programs.

Thanks
