### ISSUE TITLE
Implement text_color & bg properties for widgets

### ISSUE THREAD

**Issue by martinohanlon** [lawsie/guizero#95]
`text_color` & `bg` are implemented for `PushButton` but not for other widgets which support it (Text, TextBox, Combo) etc. 

Issue #94 suggests its a gap.

**Comment by martinohanlon** [comment]
Should setting the text_color / bg for a container also set the color for all child components?

**Comment by Coal0** [comment]
Conform to the design philosophy (thanks @lawsie):

> keep things as simple as possible

I think this would make sense, after all, the whole purpose of a 'container' is to group elements together (thus enforcing a single style). Or perhaps we should allow users to disable this, for example, as a global function:

```python
_inherit_style_from_container = True

def inherit_container_style(boolean):
    """Whether or not children should inherit the style of a parent container."""
    global _inherit_style_from_container
    _inherit_style_from_container = boolean


class Container:
    """An abstract class representing a widget container."""
    ...


class Child:
    """An abstract class representing a child widget."""

    def __init__(self, master, ...):
        # Initialize stuff here

        if _inherit_style_from_container:
            background = master.cget("background")
            self.tk.configure(background=background)
```

Or for a more general case:

```python
class Child:
    """An abstract class representing a child widget."""

    def __init__(self, master, ...):
        # Initialize stuff here

        if _inherit_style_from_container:
            container_style = master.configure()
            self.tk.configure(**container_style)
```

The last snippet will obviously break, since it will also set width, height and a bunch of other attributes that should not be inherited from the container.

**Comment by yeyeto2788** [comment]
Might it be possible to add another enhancement to this? I'm trying to set the width of the Combo but I cannot find any possible solution for it. 

Do I open a new issue or this will also handle it?

Regards.

**Comment by martinohanlon** [comment]
Hi, can you open a seperate issue please. Thanks

**Comment by yeyeto2788** [comment]
@martinohanlon thanks for the reply, I have opened issue #132

**Comment by martinohanlon** [comment]
I have:
- refactored text_color, text_size and font properties and added them to:
  - ButtonGroup
  - Combo
  - CheckBox
  - PushButton
  - Text
  - TextBox
- refactored bg (background) and added to:
  - Box
  - ButtonGroup
  - CheckBox
  - Combo
  - Picture
  - PushButton
  - Slider
  - Text
  - TextBox

This will be in 0.4.4

I havent made the changes to make containers 'cascade' colors. I am going to raise a seperate issue for this as I want to review what other properties should be cascaded from containers for their widgets and a mechanism for containers to know which widgets are children (whether those widgets are tk widgets or 'guizero' widgets).
