### ISSUE TITLE
Updating GUI ZERO on Ubuntu 16.04

### ISSUE THREAD

**Issue by James100000** [lawsie/guizero#96]
Tried updating Gui Zero from the website without any success.
 
Is there any particular command that is different for Ubuntu 16.04

It worked for the Raspberry pi with success.

    Open a terminal
    Install tkinter using your distribution's package manager, e.g. sudo apt install python3-tk
    Install guizero using pip by typing sudo pip3 install guizero

This is the error I received.

The directory '/home/ladyhawk/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ladyhawk/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: guizero in /usr/local/lib/python3.5/dist-packages

Thanks

**Comment by Coal0** [comment]
What exactly did you run? We need the full traceback. Please use code markdown:

\`\`\`shell
< traceback here >
\`\`\`

**Comment by martinohanlon** [comment]
This looks to be a permissions problem with the setup of your PC.

I would either suggest, either running as without sudo (i.e. as your user) 

```
pip3 install guizero
```

or as sudo using the -H option as the error suggests:

```
sudo -H pip3 install guizero
```

as a quick google suggests the -H option forces sudo to use the users %HOME% directory.

Having said all that though - its seem as though you already have guizero installed... Note -

```
Requirement already satisfied: guizero in /usr/local/lib/python3.5/dist-packages
```

Were you trying to upgrade to the latest version of guizero? If so, use:

```
pip3 install guizero --upgrade
```

I will update the install instructions for Linux to note that you may not have to use sudo for pip if your local user has superuser rights.

**Comment by martinohanlon** [comment]
updated linux install instructions, ill include in v0.4.2

**Comment by James100000** [comment]
pip3 install guizero --upgrade

Yes that worked fine.

Just making all the computers I have compatible.

Thanks
