### ISSUE TITLE
Readme: Installation guide may need to be updated 

### ISSUE THREAD

**Issue by Coal0** [lawsie/guizero#97]
Running `pip` with `sudo` is insecure<sup>1</sup>.
Should we replace `sudo pip *` code blocks with `pip * --user`?

There's an active discussion on that [here](https://github.com/pypa/pip/issues/1668) too.

<sup>1</sup> https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip

**Comment by martinohanlon** [comment]
The downside is that this would only installed for the logged in user.

I have just updated the linux install instructions anyway, as I think for the majority of distro's, the 'default user' ends up being a root user anyway.

**Comment by lawsie** [comment]
Please can you also get rid of the "On..." - it's been annoying me that it says Windows and Raspberry Pi but "On Linux" and "On Mac" :D (my fault!)

**Comment by martinohanlon** [comment]
Ok

**Comment by martinohanlon** [comment]
Remove 'on' - in 0.4.2
